Projekt Ei: HardwareLife/Lcd/Content/Content.h File Reference
Content.h File Reference
#include <stdint.h>
#include "Face/IFace.h"
#include "Line/ILine.h"
#include "../../../../components/tft/tft.h"
Classes
class Content
Functions
void TftDisplayBackend ()
Function Documentation
TftDisplayBackend()
void TftDisplayBackend ()
References spi_lobo_device_interface_config_t::clock_speed_hz, DEFAULT_SPI_CLOCK, DEJAVU24_FONT, find_rd_speed(), LB_SPI_DEVICE_HALFDUPLEX, max_rdclock, spi_lobo_bus_config_t::miso_io_num, SPI_BUS, SPI_DISPLAY_CS, SPI_DISPLAY_MISO, SPI_DISPLAY_MOSI, SPI_DISPLAY_SCLK, spi_lobo_bus_add_device(), spi_lobo_device_deselect(), spi_lobo_device_select(), spi_lobo_set_speed(), TFT_display_init(), TFT_invertDisplay(), TFT_PinsInit(), TFT_setFont(), TFT_setRotation(), and vfs_spiffs_register().
Referenced by Content::Content().