Projekt Ei: HardwareLife/Lcd/ESP32_TFT_library/components/mkspiffs/src/main.cpp File Reference
main.cpp File Reference
#include <iostream>
#include "spiffs/spiffs.h"
#include <vector>
#include <dirent.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <cstring>
#include <string>
#include <time.h>
#include <memory>
#include <cstdlib>
#include "tclap/CmdLine.h"
#include "tclap/UnlabeledValueArg.h"
Classes
struct spiffs_metadata_t
Macros
#define TCLAP_SETBASE_ZERO 1
#define VERSION "0.3.6"
Enumerations
enum Action {
ACTION_NONE, ACTION_PACK, ACTION_UNPACK, ACTION_LIST,
ACTION_VISUALIZE
}
Functions
int spiffsTryMount ()
bool spiffsMount ()
bool spiffsFormat ()
void spiffsUnmount ()
int addDir (const char *name)
int addFile (char *name, const char *path)
int addFiles (const char *dirname, const char *subPath)
void listFiles ()
bool dirExists (const char *path)
Check if directory exists.
bool dirCreate (const char *path)
Create directory if it not exists.
bool unpackFile (spiffs_dirent *spiffsFile, const char *destPath)
Unpack file from file system.
bool unpackFiles (std::string sDest)
Unpack files from file system.
int actionPack ()
int actionUnpack (void)
Unpack action.
int actionList ()
int actionVisualize ()
void processArgs (int argc, const char **argv)
int main (int argc, const char *argv[])
Variables
int g_debugLevel = 0
Class Documentation
spiffs_metadata_t
struct spiffs_metadata_t
Class Members
time_t atime
time_t ctime
time_t mtime
uint8_t spare[SPIFFS_OBJ_META_LEN -(sizeof(time_t) *3)]
Macro Definition Documentation
TCLAP_SETBASE_ZERO
#define TCLAP_SETBASE_ZERO 1
Referenced by TCLAP::ExtractValue().
VERSION
#define VERSION "0.3.6"
Referenced by processArgs().
Enumeration Type Documentation
Action
enum Action
Enumerator
ACTION_NONE
ACTION_PACK
ACTION_UNPACK
ACTION_LIST
ACTION_VISUALIZE
Function Documentation
actionList()
int actionList ()
actionPack()
int actionPack ()
actionUnpack()
int actionUnpack (void)
Unpack action.
Returns
0 success, 1 error
Author
Pascal Gollor (http://www.pgollor.de/cms/)
actionVisualize()
int actionVisualize ()
addDir()
int addDir (const char * name)
References spiffs_metadata_t::atime, spiffs_metadata_t::ctime, spiffs_t::err_code, spiffs_metadata_t::mtime, SPIFFS_close(), SPIFFS_CREAT, SPIFFS_ERR_FULL, SPIFFS_open(), and SPIFFS_update_meta().
Referenced by addFiles().
addFile()
int addFile (char * name, const char * path)
References spiffs_metadata_t::atime, spiffs_metadata_t::ctime, spiffs_t::err_code, g_debugLevel, left, spiffs_metadata_t::mtime, SPIFFS_close(), SPIFFS_CREAT, SPIFFS_ERR_FULL, SPIFFS_open(), SPIFFS_RDWR, SPIFFS_TRUNC, SPIFFS_update_meta(), and SPIFFS_write().
Referenced by addFiles().
addFiles()
int addFiles (const char * dirname, const char * subPath)
References addDir(), addFile(), and g_debugLevel.
dirCreate()
bool dirCreate (const char * path)
Create directory if it not exists.
Parameters
path Directory path.
Returns
True or false.
Author
Pascal Gollor (http://www.pgollor.de/cms/)
References dirExists().
Referenced by unpackFiles().
dirExists()
bool dirExists (const char * path)
Check if directory exists.
Parameters
path Directory path.
Returns
True if exists otherwise false.
Author
Pascal Gollor (http://www.pgollor.de/cms/)
Referenced by dirCreate(), and unpackFiles().
listFiles()
void listFiles ()
References spiffs_dirent::name, spiffs_dirent::size, SPIFFS_closedir(), SPIFFS_opendir(), and SPIFFS_readdir().
main()
int main (int argc, const char * argv[])
References processArgs().
processArgs()
void processArgs (int argc, const char ** argv)
References TCLAP::CmdLine::add(), g_debugLevel, TCLAP::ValueArg< T >::getValue(), TCLAP::Arg::isSet(), TCLAP::CmdLine::parse(), VERSION, and TCLAP::CmdLine::xorAdd().
Referenced by main().
spiffsFormat()
bool spiffsFormat ()
References SPIFFS_format(), SPIFFS_OK, SPIFFS_unmount(), spiffsMount(), and spiffsTryMount().
spiffsMount()
bool spiffsMount ()
References SPIFFS_mounted(), SPIFFS_OK, and spiffsTryMount().
Referenced by spiffsFormat().
spiffsTryMount()
int spiffsTryMount ()
References spiffs_config::phys_addr, and spiffs_config::phys_size.
Referenced by spiffsFormat(), and spiffsMount().
spiffsUnmount()
void spiffsUnmount ()
References SPIFFS_mounted(), and SPIFFS_unmount().
unpackFile()
bool unpackFile (spiffs_dirent * spiffsFile, const char * destPath)
Unpack file from file system.
Parameters
spiffsFile SPIFFS dir entry pointer.
destPath Destination file path path.
Returns
True or false.
Author
Pascal Gollor (http://www.pgollor.de/cms/)
References spiffs_dirent::name, spiffs_dirent::size, SPIFFS_close(), SPIFFS_open(), SPIFFS_RDONLY, and SPIFFS_read().
Referenced by unpackFiles().
unpackFiles()
bool unpackFiles (std::string sDest)
Unpack files from file system.
Parameters
sDest Directory path as std::string.
Returns
True or false.
Author
Pascal Gollor (http://www.pgollor.de/cms/)
todo: Do unpack stuff for directories.
References dirCreate(), dirExists(), spiffs_dirent::name, spiffs_dirent::size, SPIFFS_closedir(), SPIFFS_opendir(), SPIFFS_readdir(), spiffs_dirent::type, and unpackFile().
Variable Documentation
g_debugLevel
int g_debugLevel = 0
Referenced by addFile(), addFiles(), and processArgs().