Projekt Ei: HardwareLife/Lcd/TftDisplayBackend.c File Reference
TftDisplayBackend.c File Reference
#include <time.h>
#include <errno.h>
#include <sys/fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "esp_system.h"
#include "driver/gpio.h"
#include "esp_heap_caps.h"
#include "../../../components/tft/tftspi.h"
#include "../../../components/tft/tft.h"
#include "../../../components/spiffs/spiffs_vfs.h"
#include "../../../components/spidriver/spi_master_lobo.h"
#include "driver/uart.h"
#include "Defines_Lcd.h"
Functions
void TftDisplayBackend (void)
Variables
spi_lobo_device_handle_t disp_spi
Function Documentation
TftDisplayBackend()
void TftDisplayBackend (void)
References spi_lobo_device_interface_config_t::clock_speed_hz, DEFAULT_SPI_CLOCK, DEJAVU24_FONT, find_rd_speed(), LB_SPI_DEVICE_HALFDUPLEX, max_rdclock, spi_lobo_bus_config_t::miso_io_num, SPI_BUS, SPI_DISPLAY_CS, SPI_DISPLAY_MISO, SPI_DISPLAY_MOSI, SPI_DISPLAY_SCLK, spi_lobo_bus_add_device(), spi_lobo_device_deselect(), spi_lobo_device_select(), spi_lobo_set_speed(), TFT_display_init(), TFT_invertDisplay(), TFT_PinsInit(), TFT_setFont(), TFT_setRotation(), and vfs_spiffs_register().
Referenced by Content::Content().
Variable Documentation
disp_spi
spi_lobo_device_handle_t disp_spi
Referenced by app_main().