Projekt Ei: HardwareLife/Uart/Uart.h File Reference
Uart.h File Reference
#include "driver/uart.h"
#include "driver/gpio.h"
Classes
class Uart
Macros
#define BAUDRATE 115200
#define BUF_SIZE 128
Functions
esp_err_t uart_driver_install (uart_port_t uart_num, int rx_buffer_size, int tx_buffer_size, int queue_size, QueueHandle_t *uart_queue, int intr_alloc_flags)
int uart_write_bytes (uart_port_t uart_num, const char *src, size_t size)
esp_err_t uart_param_config (uart_port_t uart_num, const uart_config_t *uart_config)
esp_err_t uart_set_pin (uart_port_t uart_num, int tx_io_num, int rx_io_num, int rts_io_num, int cts_io_num)
int uart_read_bytes (uart_port_t uart_num, uint8_t *buf, uint32_t length, TickType_t ticks_to_wait)
Macro Definition Documentation
BAUDRATE
#define BAUDRATE 115200
Referenced by Uart::Uart().
BUF_SIZE
#define BUF_SIZE 128
Referenced by Uart::Uart().
Function Documentation
uart_driver_install()
esp_err_t uart_driver_install (uart_port_t uart_num, int rx_buffer_size, int tx_buffer_size, int queue_size, QueueHandle_t * uart_queue, int intr_alloc_flags)
Referenced by Uart::Uart().
uart_param_config()
esp_err_t uart_param_config (uart_port_t uart_num, const uart_config_t * uart_config)
Referenced by Uart::Uart().
uart_read_bytes()
int uart_read_bytes (uart_port_t uart_num, uint8_t * buf, uint32_t length, TickType_t ticks_to_wait)
Referenced by Uart::read().
uart_set_pin()
esp_err_t uart_set_pin (uart_port_t uart_num, int tx_io_num, int rx_io_num, int rts_io_num, int cts_io_num)
Referenced by Uart::Uart().
uart_write_bytes()
int uart_write_bytes (uart_port_t uart_num, const char * src, size_t size)
Referenced by Uart::write().