var annotated_dup =
[
    [ "TCLAP", null, [
      [ "Arg", "class_t_c_l_a_p_1_1_arg.html", "class_t_c_l_a_p_1_1_arg" ],
      [ "ArgException", "class_t_c_l_a_p_1_1_arg_exception.html", "class_t_c_l_a_p_1_1_arg_exception" ],
      [ "ArgParseException", "class_t_c_l_a_p_1_1_arg_parse_exception.html", "class_t_c_l_a_p_1_1_arg_parse_exception" ],
      [ "ArgTraits", "struct_t_c_l_a_p_1_1_arg_traits.html", "struct_t_c_l_a_p_1_1_arg_traits" ],
      [ "ArgTraits< bool >", "struct_t_c_l_a_p_1_1_arg_traits_3_01bool_01_4.html", "struct_t_c_l_a_p_1_1_arg_traits_3_01bool_01_4" ],
      [ "ArgTraits< char >", "struct_t_c_l_a_p_1_1_arg_traits_3_01char_01_4.html", "struct_t_c_l_a_p_1_1_arg_traits_3_01char_01_4" ],
      [ "ArgTraits< double >", "struct_t_c_l_a_p_1_1_arg_traits_3_01double_01_4.html", "struct_t_c_l_a_p_1_1_arg_traits_3_01double_01_4" ],
      [ "ArgTraits< float >", "struct_t_c_l_a_p_1_1_arg_traits_3_01float_01_4.html", "struct_t_c_l_a_p_1_1_arg_traits_3_01float_01_4" ],
      [ "ArgTraits< int >", "struct_t_c_l_a_p_1_1_arg_traits_3_01int_01_4.html", "struct_t_c_l_a_p_1_1_arg_traits_3_01int_01_4" ],
      [ "ArgTraits< long >", "struct_t_c_l_a_p_1_1_arg_traits_3_01long_01_4.html", "struct_t_c_l_a_p_1_1_arg_traits_3_01long_01_4" ],
      [ "ArgTraits< short >", "struct_t_c_l_a_p_1_1_arg_traits_3_01short_01_4.html", "struct_t_c_l_a_p_1_1_arg_traits_3_01short_01_4" ],
      [ "ArgTraits< std::string >", "struct_t_c_l_a_p_1_1_arg_traits_3_01std_1_1string_01_4.html", "struct_t_c_l_a_p_1_1_arg_traits_3_01std_1_1string_01_4" ],
      [ "ArgTraits< unsigned char >", "struct_t_c_l_a_p_1_1_arg_traits_3_01unsigned_01char_01_4.html", "struct_t_c_l_a_p_1_1_arg_traits_3_01unsigned_01char_01_4" ],
      [ "ArgTraits< unsigned int >", "struct_t_c_l_a_p_1_1_arg_traits_3_01unsigned_01int_01_4.html", "struct_t_c_l_a_p_1_1_arg_traits_3_01unsigned_01int_01_4" ],
      [ "ArgTraits< unsigned long >", "struct_t_c_l_a_p_1_1_arg_traits_3_01unsigned_01long_01_4.html", "struct_t_c_l_a_p_1_1_arg_traits_3_01unsigned_01long_01_4" ],
      [ "ArgTraits< unsigned short >", "struct_t_c_l_a_p_1_1_arg_traits_3_01unsigned_01short_01_4.html", "struct_t_c_l_a_p_1_1_arg_traits_3_01unsigned_01short_01_4" ],
      [ "ArgTraits< wchar_t >", "struct_t_c_l_a_p_1_1_arg_traits_3_01wchar__t_01_4.html", "struct_t_c_l_a_p_1_1_arg_traits_3_01wchar__t_01_4" ],
      [ "CmdLine", "class_t_c_l_a_p_1_1_cmd_line.html", "class_t_c_l_a_p_1_1_cmd_line" ],
      [ "CmdLineInterface", "class_t_c_l_a_p_1_1_cmd_line_interface.html", "class_t_c_l_a_p_1_1_cmd_line_interface" ],
      [ "CmdLineOutput", "class_t_c_l_a_p_1_1_cmd_line_output.html", "class_t_c_l_a_p_1_1_cmd_line_output" ],
      [ "CmdLineParseException", "class_t_c_l_a_p_1_1_cmd_line_parse_exception.html", "class_t_c_l_a_p_1_1_cmd_line_parse_exception" ],
      [ "Constraint", "class_t_c_l_a_p_1_1_constraint.html", "class_t_c_l_a_p_1_1_constraint" ],
      [ "DocBookOutput", "class_t_c_l_a_p_1_1_doc_book_output.html", "class_t_c_l_a_p_1_1_doc_book_output" ],
      [ "ExitException", "class_t_c_l_a_p_1_1_exit_exception.html", "class_t_c_l_a_p_1_1_exit_exception" ],
      [ "HelpVisitor", "class_t_c_l_a_p_1_1_help_visitor.html", "class_t_c_l_a_p_1_1_help_visitor" ],
      [ "IgnoreRestVisitor", "class_t_c_l_a_p_1_1_ignore_rest_visitor.html", "class_t_c_l_a_p_1_1_ignore_rest_visitor" ],
      [ "MultiArg", "class_t_c_l_a_p_1_1_multi_arg.html", "class_t_c_l_a_p_1_1_multi_arg" ],
      [ "MultiSwitchArg", "class_t_c_l_a_p_1_1_multi_switch_arg.html", "class_t_c_l_a_p_1_1_multi_switch_arg" ],
      [ "OptionalUnlabeledTracker", "class_t_c_l_a_p_1_1_optional_unlabeled_tracker.html", null ],
      [ "SpecificationException", "class_t_c_l_a_p_1_1_specification_exception.html", "class_t_c_l_a_p_1_1_specification_exception" ],
      [ "StdOutput", "class_t_c_l_a_p_1_1_std_output.html", "class_t_c_l_a_p_1_1_std_output" ],
      [ "StringLike", "struct_t_c_l_a_p_1_1_string_like.html", "struct_t_c_l_a_p_1_1_string_like" ],
      [ "StringLikeTrait", "struct_t_c_l_a_p_1_1_string_like_trait.html", "struct_t_c_l_a_p_1_1_string_like_trait" ],
      [ "SwitchArg", "class_t_c_l_a_p_1_1_switch_arg.html", "class_t_c_l_a_p_1_1_switch_arg" ],
      [ "UnlabeledMultiArg", "class_t_c_l_a_p_1_1_unlabeled_multi_arg.html", "class_t_c_l_a_p_1_1_unlabeled_multi_arg" ],
      [ "UnlabeledValueArg", "class_t_c_l_a_p_1_1_unlabeled_value_arg.html", "class_t_c_l_a_p_1_1_unlabeled_value_arg" ],
      [ "ValueArg", "class_t_c_l_a_p_1_1_value_arg.html", "class_t_c_l_a_p_1_1_value_arg" ],
      [ "ValueLike", "struct_t_c_l_a_p_1_1_value_like.html", "struct_t_c_l_a_p_1_1_value_like" ],
      [ "ValueLikeTrait", "struct_t_c_l_a_p_1_1_value_like_trait.html", "struct_t_c_l_a_p_1_1_value_like_trait" ],
      [ "ValuesConstraint", "class_t_c_l_a_p_1_1_values_constraint.html", "class_t_c_l_a_p_1_1_values_constraint" ],
      [ "VersionVisitor", "class_t_c_l_a_p_1_1_version_visitor.html", "class_t_c_l_a_p_1_1_version_visitor" ],
      [ "Visitor", "class_t_c_l_a_p_1_1_visitor.html", "class_t_c_l_a_p_1_1_visitor" ],
      [ "XorHandler", "class_t_c_l_a_p_1_1_xor_handler.html", "class_t_c_l_a_p_1_1_xor_handler" ],
      [ "ZshCompletionOutput", "class_t_c_l_a_p_1_1_zsh_completion_output.html", "class_t_c_l_a_p_1_1_zsh_completion_output" ]
    ] ],
    [ "Abstractor", "class_abstractor.html", "class_abstractor" ],
    [ "Authenticator", "class_authenticator.html", "class_authenticator" ],
    [ "Combinator", "class_combinator.html", "class_combinator" ],
    [ "Content", "class_content.html", "class_content" ],
    [ "dispWin_t", "structdisp_win__t.html", "structdisp_win__t" ],
    [ "Face", "class_face.html", "class_face" ],
    [ "FileItem", "class_file_item.html", "class_file_item" ],
    [ "Font", "struct_font.html", "struct_font" ],
    [ "Gpio", "class_gpio.html", "class_gpio" ],
    [ "IAbstractor", "class_i_abstractor.html", "class_i_abstractor" ],
    [ "Id", "class_id.html", "class_id" ],
    [ "IFace", "class_i_face.html", "class_i_face" ],
    [ "IFileItem", "class_i_file_item.html", "class_i_file_item" ],
    [ "IGpio", "class_i_gpio.html", "class_i_gpio" ],
    [ "IId", "class_i_id.html", "class_i_id" ],
    [ "IKiss", "class_i_kiss.html", "class_i_kiss" ],
    [ "ILifeCycle", "class_i_life_cycle.html", "class_i_life_cycle" ],
    [ "ILine", "class_i_line.html", "class_i_line" ],
    [ "IPublisher", "class_i_publisher.html", null ],
    [ "ISubscriber", "class_i_subscriber.html", null ],
    [ "ITechDevice", "class_i_tech_device.html", "class_i_tech_device" ],
    [ "ItemBits", "class_item_bits.html", "class_item_bits" ],
    [ "ITransportAccess", "class_i_transport_access.html", "class_i_transport_access" ],
    [ "Kiss", "class_kiss.html", "class_kiss" ],
    [ "LifeCycle", "class_life_cycle.html", "class_life_cycle" ],
    [ "list", "structlist.html", "structlist" ],
    [ "list_index", "structlist__index.html", "structlist__index" ],
    [ "mtx", "structmtx.html", "structmtx" ],
    [ "OLED", "class_o_l_e_d.html", "class_o_l_e_d" ],
    [ "point", "structpoint.html", "structpoint" ],
    [ "Prozessor", "class_prozessor.html", "class_prozessor" ],
    [ "Requester", "class_requester.html", "class_requester" ],
    [ "spi_lobo_bus_config_t", "structspi__lobo__bus__config__t.html", "structspi__lobo__bus__config__t" ],
    [ "spi_lobo_device_interface_config_t", "structspi__lobo__device__interface__config__t.html", "structspi__lobo__device__interface__config__t" ],
    [ "spi_lobo_device_t", "structspi__lobo__device__t.html", "structspi__lobo__device__t" ],
    [ "spi_lobo_host_t", "structspi__lobo__host__t.html", "structspi__lobo__host__t" ],
    [ "spi_lobo_transaction_t", "structspi__lobo__transaction__t.html", "structspi__lobo__transaction__t" ],
    [ "spiffs_config", "structspiffs__config.html", "structspiffs__config" ],
    [ "spiffs_DIR", "structspiffs___d_i_r.html", "structspiffs___d_i_r" ],
    [ "spiffs_dirent", "structspiffs__dirent.html", "structspiffs__dirent" ],
    [ "spiffs_fd", "structspiffs__fd.html", "structspiffs__fd" ],
    [ "spiffs_ix_map", "structspiffs__ix__map.html", "structspiffs__ix__map" ],
    [ "spiffs_metadata_t", "structspiffs__metadata__t.html", "structspiffs__metadata__t" ],
    [ "spiffs_stat", "structspiffs__stat.html", "structspiffs__stat" ],
    [ "spiffs_t", "structspiffs__t.html", "structspiffs__t" ],
    [ "TechDevice", "class_tech_device.html", "class_tech_device" ],
    [ "TopLine", "class_top_line.html", "class_top_line" ],
    [ "u8g2_esp32_hal_t", "structu8g2__esp32__hal__t.html", "structu8g2__esp32__hal__t" ],
    [ "Uart", "class_uart.html", "class_uart" ],
    [ "WiFi", "class_wi_fi.html", "class_wi_fi" ]
];