var dir_50d16c5b83c6623d97b87907ede1d6ac =
[
    [ "brownout.d", "brownout_8d.html", null ],
    [ "cache_err_int.d", "cache__err__int_8d.html", null ],
    [ "cache_sram_mmu.d", "cache__sram__mmu_8d.html", null ],
    [ "clk.d", "clk_8d.html", null ],
    [ "cpu_start.d", "cpu__start_8d.html", null ],
    [ "crosscore_int.d", "crosscore__int_8d.html", null ],
    [ "dport_access.d", "dport__access_8d.html", null ],
    [ "dport_panic_highint_hdl.d", "dport__panic__highint__hdl_8d.html", null ],
    [ "esp_adapter.d", "esp__adapter_8d.html", null ],
    [ "esp_himem.d", "esp__himem_8d.html", null ],
    [ "esp_timer_esp32.d", "esp__timer__esp32_8d.html", null ],
    [ "hw_random.d", "hw__random_8d.html", null ],
    [ "int_wdt.d", "int__wdt_8d.html", null ],
    [ "intr_alloc.d", "intr__alloc_8d.html", null ],
    [ "panic.d", "panic_8d.html", null ],
    [ "pm_esp32.d", "pm__esp32_8d.html", null ],
    [ "pm_trace.d", "pm__trace_8d.html", null ],
    [ "reset_reason.d", "reset__reason_8d.html", null ],
    [ "sleep_modes.d", "sleep__modes_8d.html", null ],
    [ "spiram.d", "spiram_8d.html", null ],
    [ "spiram_psram.d", "spiram__psram_8d.html", null ],
    [ "system_api.d", "system__api_8d.html", null ],
    [ "task_wdt.d", "task__wdt_8d.html", null ]
];