Projekt Ei: HardwareLife/Lcd/ESP32_TFT_library/components/spiffs/list.c File Reference
list.c File Reference
#include "esp_attr.h"
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include "list.h"
#include "mutex.h"
Functions
void list_init (struct list *list, int first_index)
int list_add (struct list *list, void *item, int *item_index)
int IRAM_ATTR list_get (struct list *list, int index, void **item)
int list_remove (struct list *list, int index, int destroy)
int IRAM_ATTR list_first (struct list *list)
int IRAM_ATTR list_next (struct list *list, int index)
void list_destroy (struct list *list, int items)
Function Documentation
list_add()
int list_add (struct list * list, void * item, int * item_index)
References list_index::deleted, list::first_index, list::free, list::index, list_index::index, list::indexes, list_index::item, mtx_lock(), mtx_unlock(), list::mutex, and list_index::next.
list_destroy()
void list_destroy (struct list * list, int items)
References list_index::deleted, list::index, list_index::index, list::indexes, list_index::item, mtx_destroy(), mtx_lock(), mtx_unlock(), and list::mutex.
list_first()
int IRAM_ATTR list_first (struct list * list)
References list_index::deleted, list::first_index, list::index, list_index::index, list::indexes, mtx_lock(), mtx_unlock(), and list::mutex.
list_get()
int IRAM_ATTR list_get (struct list * list, int index, void ** item)
References list_index::deleted, list::first_index, list::index, list::indexes, list_index::item, mtx_lock(), mtx_unlock(), and list::mutex.
list_init()
void list_init (struct list * list, int first_index)
References list::first_index, list::free, list::index, list::indexes, mtx_init(), mtx_lock(), mtx_unlock(), and list::mutex.
list_next()
int IRAM_ATTR list_next (struct list * list, int index)
References list_index::deleted, list::first_index, list::index, list::indexes, mtx_lock(), mtx_unlock(), and list::mutex.
list_remove()
int list_remove (struct list * list, int index, int destroy)
References list_index::deleted, list::first_index, list::free, list::index, list::indexes, list_index::item, mtx_lock(), mtx_unlock(), list::mutex, and list_index::next.