Projekt Ei: HardwareLife/Lcd/ESP32_TFT_library/components/mkspiffs/src/spiffs/spiffs_gc.c File Reference
spiffs_gc.c File Reference
#include "spiffs.h"
#include "spiffs_nucleus.h"
Classes
struct spiffs_gc
Enumerations
enum spiffs_gc_clean_state {
FIND_OBJ_DATA, MOVE_OBJ_DATA, MOVE_OBJ_IX, FINISHED,
FIND_OBJ_DATA, MOVE_OBJ_DATA, MOVE_OBJ_IX, FINISHED
}
Functions
s32_t spiffs_gc_quick (spiffs *fs, u16_t max_free_pages)
s32_t spiffs_gc_check (spiffs *fs, u32_t len)
s32_t spiffs_gc_erase_page_stats (spiffs *fs, spiffs_block_ix bix)
s32_t spiffs_gc_find_candidate (spiffs *fs, spiffs_block_ix **block_candidates, int *candidate_count, char fs_crammed)
s32_t spiffs_gc_clean (spiffs *fs, spiffs_block_ix bix)
Class Documentation
spiffs_gc
struct spiffs_gc
Class Members
spiffs_page_ix cur_data_pix
spiffs_obj_id cur_obj_id
spiffs_page_ix cur_objix_pix
spiffs_span_ix cur_objix_spix
u8_t obj_id_found
spiffs_gc_clean_state state
int stored_scan_entry_index
Enumeration Type Documentation
spiffs_gc_clean_state
enum spiffs_gc_clean_state
Enumerator
FIND_OBJ_DATA
MOVE_OBJ_DATA
MOVE_OBJ_IX
FINISHED
FIND_OBJ_DATA
MOVE_OBJ_DATA
MOVE_OBJ_IX
FINISHED
Function Documentation
spiffs_gc_check()
s32_t spiffs_gc_check (spiffs * fs, u32_t len)
Referenced by SPIFFS_gc(), spiffs_object_append(), spiffs_object_create(), spiffs_object_modify(), and spiffs_object_truncate().
spiffs_gc_clean()
s32_t spiffs_gc_clean (spiffs * fs, spiffs_block_ix bix)
Referenced by spiffs_gc_check().
spiffs_gc_erase_page_stats()
s32_t spiffs_gc_erase_page_stats (spiffs * fs, spiffs_block_ix bix)
Referenced by spiffs_gc_check().
spiffs_gc_find_candidate()
s32_t spiffs_gc_find_candidate (spiffs * fs, spiffs_block_ix ** block_candidates, int * candidate_count, char fs_crammed)
Referenced by spiffs_gc_check().
spiffs_gc_quick()
s32_t spiffs_gc_quick (spiffs * fs, u16_t max_free_pages)
Referenced by SPIFFS_gc_quick(), and spiffs_obj_lu_find_free().