Projekt Ei: HardwareLife/Lcd/ESP32_TFT_library/components/mkspiffs/src/spiffs/spiffs_check.c File Reference
spiffs_check.c File Reference
#include "spiffs.h"
#include "spiffs_nucleus.h"
Macros
#define CHECK_CB(_fs, _type, _rep, _arg1, _arg2)
Functions
s32_t spiffs_lookup_consistency_check (spiffs *fs, u8_t check_all_objects)
s32_t spiffs_page_consistency_check (spiffs *fs)
s32_t spiffs_object_index_consistency_check (spiffs *fs)
Macro Definition Documentation
CHECK_CB
#define CHECK_CB (_fs, _type, _rep, _arg1, _arg2)
Value:
do { \
    if ((_fs)->check_cb_f) (_fs)->check_cb_f((_type), (_rep), (_arg1), (_arg2)); \
  } while (0)
Referenced by spiffs_lookup_consistency_check(), spiffs_object_index_consistency_check(), and spiffs_page_consistency_check().
Function Documentation
spiffs_lookup_consistency_check()
s32_t spiffs_lookup_consistency_check (spiffs * fs, u8_t check_all_objects)
Referenced by SPIFFS_check().
spiffs_object_index_consistency_check()
s32_t spiffs_object_index_consistency_check (spiffs * fs)
Referenced by SPIFFS_check().
spiffs_page_consistency_check()
s32_t spiffs_page_consistency_check (spiffs * fs)
Referenced by SPIFFS_check().