Projekt Ei: HardwareLife/Lcd/ESP32_TFT_library/components/mkspiffs/src/spiffs/spiffs_nucleus.c File Reference
spiffs_nucleus.c File Reference
#include "spiffs.h"
#include "spiffs_nucleus.h"
Classes
struct spiffs_ix_map_populate_state
struct spiffs_free_obj_id_state
Functions
s32_t spiffs_phys_cpy (spiffs *fs, spiffs_file fh, u32_t dst, u32_t src, u32_t len)
s32_t spiffs_obj_lu_find_entry_visitor (spiffs *fs, spiffs_block_ix starting_block, int starting_lu_entry, u8_t flags, spiffs_obj_id obj_id, spiffs_visitor_f v, const void *user_const_p, void *user_var_p, spiffs_block_ix *block_ix, int *lu_entry)
s32_t spiffs_erase_block (spiffs *fs, spiffs_block_ix bix)
s32_t spiffs_probe (spiffs_config *cfg)
s32_t spiffs_obj_lu_scan (spiffs *fs)
s32_t spiffs_obj_lu_find_free (spiffs *fs, spiffs_block_ix starting_block, int starting_lu_entry, spiffs_block_ix *block_ix, int *lu_entry)
s32_t spiffs_obj_lu_find_id (spiffs *fs, spiffs_block_ix starting_block, int starting_lu_entry, spiffs_obj_id obj_id, spiffs_block_ix *block_ix, int *lu_entry)
s32_t spiffs_obj_lu_find_id_and_span (spiffs *fs, spiffs_obj_id obj_id, spiffs_span_ix spix, spiffs_page_ix exclusion_pix, spiffs_page_ix *pix)
s32_t spiffs_obj_lu_find_id_and_span_by_phdr (spiffs *fs, spiffs_obj_id obj_id, spiffs_span_ix spix, spiffs_page_ix exclusion_pix, spiffs_page_ix *pix)
s32_t spiffs_populate_ix_map (spiffs *fs, spiffs_fd *fd, u32_t vec_entry_start, u32_t vec_entry_end)
s32_t spiffs_page_allocate_data (spiffs *fs, spiffs_obj_id obj_id, spiffs_page_header *ph, u8_t *data, u32_t len, u32_t page_offs, u8_t finalize, spiffs_page_ix *pix)
s32_t spiffs_page_move (spiffs *fs, spiffs_file fh, u8_t *page_data, spiffs_obj_id obj_id, spiffs_page_header *page_hdr, spiffs_page_ix src_pix, spiffs_page_ix *dst_pix)
s32_t spiffs_page_delete (spiffs *fs, spiffs_page_ix pix)
s32_t spiffs_object_create (spiffs *fs, spiffs_obj_id obj_id, const u8_t name[], const u8_t meta[], spiffs_obj_type type, spiffs_page_ix *objix_hdr_pix)
s32_t spiffs_object_update_index_hdr (spiffs *fs, spiffs_fd *fd, spiffs_obj_id obj_id, spiffs_page_ix objix_hdr_pix, u8_t *new_objix_hdr_data, const u8_t name[], const u8_t meta[], u32_t size, spiffs_page_ix *new_pix)
void spiffs_cb_object_event (spiffs *fs, spiffs_page_object_ix *objix, int ev, spiffs_obj_id obj_id_raw, spiffs_span_ix spix, spiffs_page_ix new_pix, u32_t new_size)
s32_t spiffs_object_open_by_id (spiffs *fs, spiffs_obj_id obj_id, spiffs_fd *fd, spiffs_flags flags, spiffs_mode mode)
s32_t spiffs_object_open_by_page (spiffs *fs, spiffs_page_ix pix, spiffs_fd *fd, spiffs_flags flags, spiffs_mode mode)
s32_t spiffs_object_append (spiffs_fd *fd, u32_t offset, u8_t *data, u32_t len)
s32_t spiffs_object_modify (spiffs_fd *fd, u32_t offset, u8_t *data, u32_t len)
s32_t spiffs_object_find_object_index_header_by_name (spiffs *fs, const u8_t name[SPIFFS_OBJ_NAME_LEN], spiffs_page_ix *pix)
s32_t spiffs_object_truncate (spiffs_fd *fd, u32_t new_size, u8_t remove_full)
s32_t spiffs_object_read (spiffs_fd *fd, u32_t offset, u32_t len, u8_t *dst)
s32_t spiffs_obj_lu_find_free_obj_id (spiffs *fs, spiffs_obj_id *obj_id, const u8_t *conflicting_name)
s32_t spiffs_fd_find_new (spiffs *fs, spiffs_fd **fd, const char *name)
s32_t spiffs_fd_return (spiffs *fs, spiffs_file f)
s32_t spiffs_fd_get (spiffs *fs, spiffs_file f, spiffs_fd **fd)
void spiffs_fd_temporal_cache_rehash (spiffs *fs, const char *old_path, const char *new_path)
Class Documentation
spiffs_ix_map_populate_state
struct spiffs_ix_map_populate_state
Class Members
spiffs_fd * fd
spiffs_span_ix map_objix_end_spix
spiffs_span_ix map_objix_start_spix
u32_t remaining_objix_pages_to_visit
spiffs_free_obj_id_state
struct spiffs_free_obj_id_state
Class Members
u32_t compaction
const u8_t * conflicting_name
spiffs_obj_id max_obj_id
spiffs_obj_id min_obj_id
Function Documentation
spiffs_cb_object_event()
void spiffs_cb_object_event (spiffs * fs, spiffs_page_object_ix * objix, int ev, spiffs_obj_id obj_id_raw, spiffs_span_ix spix, spiffs_page_ix new_pix, u32_t new_size)
Referenced by spiffs_gc_clean(), spiffs_object_create(), and spiffs_object_update_index_hdr().
spiffs_erase_block()
s32_t spiffs_erase_block (spiffs * fs, spiffs_block_ix bix)
Referenced by SPIFFS_format(), and spiffs_obj_lu_scan().
spiffs_fd_find_new()
s32_t spiffs_fd_find_new (spiffs * fs, spiffs_fd ** fd, const char * name)
Referenced by SPIFFS_open(), SPIFFS_open_by_dirent(), SPIFFS_open_by_page(), SPIFFS_remove(), SPIFFS_rename(), and SPIFFS_update_meta().
spiffs_fd_get()
s32_t spiffs_fd_get (spiffs * fs, spiffs_file f, spiffs_fd ** fd)
Referenced by SPIFFS_eof(), SPIFFS_fremove(), SPIFFS_fstat(), SPIFFS_fupdate_meta(), SPIFFS_ix_map(), SPIFFS_ix_remap(), SPIFFS_ix_unmap(), SPIFFS_lseek(), SPIFFS_tell(), and SPIFFS_write().
spiffs_fd_return()
s32_t spiffs_fd_return (spiffs * fs, spiffs_file f)
Referenced by SPIFFS_open(), SPIFFS_open_by_dirent(), SPIFFS_open_by_page(), SPIFFS_remove(), SPIFFS_rename(), and SPIFFS_update_meta().
spiffs_fd_temporal_cache_rehash()
void spiffs_fd_temporal_cache_rehash (spiffs * fs, const char * old_path, const char * new_path)
Referenced by SPIFFS_rename().
spiffs_obj_lu_find_entry_visitor()
s32_t spiffs_obj_lu_find_entry_visitor (spiffs * fs, spiffs_block_ix starting_block, int starting_lu_entry, u8_t flags, spiffs_obj_id obj_id, spiffs_visitor_f v, const void * user_const_p, void * user_var_p, spiffs_block_ix * block_ix, int * lu_entry)
Referenced by spiffs_lookup_consistency_check(), spiffs_obj_lu_find_free_obj_id(), spiffs_obj_lu_find_id(), spiffs_obj_lu_find_id_and_span(), spiffs_obj_lu_find_id_and_span_by_phdr(), spiffs_obj_lu_scan(), spiffs_object_find_object_index_header_by_name(), spiffs_object_index_consistency_check(), spiffs_populate_ix_map(), and SPIFFS_readdir().
spiffs_obj_lu_find_free()
s32_t spiffs_obj_lu_find_free (spiffs * fs, spiffs_block_ix starting_block, int starting_lu_entry, spiffs_block_ix * block_ix, int * lu_entry)
Referenced by spiffs_object_create(), spiffs_page_allocate_data(), and spiffs_page_move().
spiffs_obj_lu_find_free_obj_id()
s32_t spiffs_obj_lu_find_free_obj_id (spiffs * fs, spiffs_obj_id * obj_id, const u8_t * conflicting_name)
Referenced by SPIFFS_creat(), and SPIFFS_open().
spiffs_obj_lu_find_id()
s32_t spiffs_obj_lu_find_id (spiffs * fs, spiffs_block_ix starting_block, int starting_lu_entry, spiffs_obj_id obj_id, spiffs_block_ix * block_ix, int * lu_entry)
Referenced by spiffs_obj_lu_find_free().
spiffs_obj_lu_find_id_and_span()
s32_t spiffs_obj_lu_find_id_and_span (spiffs * fs, spiffs_obj_id obj_id, spiffs_span_ix spix, spiffs_page_ix exclusion_pix, spiffs_page_ix * pix)
Referenced by spiffs_gc_clean(), spiffs_object_open_by_id(), and spiffs_object_read().
spiffs_obj_lu_find_id_and_span_by_phdr()
s32_t spiffs_obj_lu_find_id_and_span_by_phdr (spiffs * fs, spiffs_obj_id obj_id, spiffs_span_ix spix, spiffs_page_ix exclusion_pix, spiffs_page_ix * pix)
spiffs_obj_lu_scan()
s32_t spiffs_obj_lu_scan (spiffs * fs)
Referenced by SPIFFS_check(), and SPIFFS_mount().
spiffs_object_append()
s32_t spiffs_object_append (spiffs_fd * fd, u32_t offset, u8_t * data, u32_t len)
spiffs_object_create()
s32_t spiffs_object_create (spiffs * fs, spiffs_obj_id obj_id, const u8_t name[], const u8_t meta[], spiffs_obj_type type, spiffs_page_ix * objix_hdr_pix)
Referenced by SPIFFS_creat(), and SPIFFS_open().
spiffs_object_find_object_index_header_by_name()
s32_t spiffs_object_find_object_index_header_by_name (spiffs * fs, const u8_t name[SPIFFS_OBJ_NAME_LEN], spiffs_page_ix * pix)
Referenced by SPIFFS_open(), SPIFFS_remove(), SPIFFS_rename(), SPIFFS_stat(), and SPIFFS_update_meta().
spiffs_object_modify()
s32_t spiffs_object_modify (spiffs_fd * fd, u32_t offset, u8_t * data, u32_t len)
spiffs_object_open_by_id()
s32_t spiffs_object_open_by_id (spiffs * fs, spiffs_obj_id obj_id, spiffs_fd * fd, spiffs_flags flags, spiffs_mode mode)
spiffs_object_open_by_page()
s32_t spiffs_object_open_by_page (spiffs * fs, spiffs_page_ix pix, spiffs_fd * fd, spiffs_flags flags, spiffs_mode mode)
Referenced by spiffs_object_open_by_id(), SPIFFS_open(), SPIFFS_open_by_dirent(), SPIFFS_open_by_page(), SPIFFS_remove(), SPIFFS_rename(), and SPIFFS_update_meta().
spiffs_object_read()
s32_t spiffs_object_read (spiffs_fd * fd, u32_t offset, u32_t len, u8_t * dst)
spiffs_object_truncate()
s32_t spiffs_object_truncate (spiffs_fd * fd, u32_t new_size, u8_t remove_full)
Referenced by SPIFFS_fremove(), SPIFFS_open(), SPIFFS_open_by_dirent(), SPIFFS_open_by_page(), and SPIFFS_remove().
spiffs_object_update_index_hdr()
s32_t spiffs_object_update_index_hdr (spiffs * fs, spiffs_fd * fd, spiffs_obj_id obj_id, spiffs_page_ix objix_hdr_pix, u8_t * new_objix_hdr_data, const u8_t name[], const u8_t meta[], u32_t size, spiffs_page_ix * new_pix)
Referenced by SPIFFS_fupdate_meta(), spiffs_gc_clean(), spiffs_object_modify(), SPIFFS_rename(), and SPIFFS_update_meta().
spiffs_page_allocate_data()
s32_t spiffs_page_allocate_data (spiffs * fs, spiffs_obj_id obj_id, spiffs_page_header * ph, u8_t * data, u32_t len, u32_t page_offs, u8_t finalize, spiffs_page_ix * pix)
spiffs_page_delete()
s32_t spiffs_page_delete (spiffs * fs, spiffs_page_ix pix)
Referenced by spiffs_gc_clean(), and spiffs_page_move().
spiffs_page_move()
s32_t spiffs_page_move (spiffs * fs, spiffs_file fh, u8_t * page_data, spiffs_obj_id obj_id, spiffs_page_header * page_hdr, spiffs_page_ix src_pix, spiffs_page_ix * dst_pix)
Referenced by spiffs_gc_clean(), and spiffs_object_update_index_hdr().
spiffs_phys_cpy()
s32_t spiffs_phys_cpy (spiffs * fs, spiffs_file fh, u32_t dst, u32_t src, u32_t len)
Referenced by spiffs_page_move().
spiffs_populate_ix_map()
s32_t spiffs_populate_ix_map (spiffs * fs, spiffs_fd * fd, u32_t vec_entry_start, u32_t vec_entry_end)
References spiffs_ix_map::end_spix, spiffs_ix_map_populate_state::fd, spiffs_ix_map_populate_state::map_objix_end_spix, spiffs_ix_map_populate_state::map_objix_start_spix, MAX, MIN, spiffs_fd::obj_id, spiffs_fd::objix_hdr_pix, spiffs_ix_map_populate_state::remaining_objix_pages_to_visit, SPIFFS_BLOCK_FOR_PAGE, SPIFFS_ERR_IX_MAP_BAD_RANGE, SPIFFS_OBJ_ID_IX_FLAG, SPIFFS_OBJ_IX_ENTRY_SPAN_IX, SPIFFS_OBJ_LOOKUP_ENTRY_FOR_PAGE, spiffs_obj_lu_find_entry_visitor(), SPIFFS_VIS_CHECK_ID, and spiffs_ix_map::start_spix.
Referenced by SPIFFS_ix_map(), and SPIFFS_ix_remap().
spiffs_probe()
s32_t spiffs_probe (spiffs_config * cfg)
References spiffs_t::block_count, spiffs_t::cfg, spiffs_config::hal_read_f, spiffs_config::log_block_size, SPIFFS_CHECK_RES, SPIFFS_ERR_PROBE_NOT_A_FS, SPIFFS_ERR_PROBE_TOO_FEW_BLOCKS, and SPIFFS_MAGIC_PADDR.
Referenced by SPIFFS_probe_fs().