Projekt Ei: HardwareLife/Lcd/ESP32_TFT_library/components/spiffs/mutex.h File Reference
mutex.h File Reference
#include "freertos/FreeRTOS.h"
#include "freertos/semphr.h"
Classes
struct mtx
Macros
#define MUTEX_INITIALIZER {.sem = 0}
Functions
void mtx_init (struct mtx *mutex, const char *name, const char *type, int opts)
void mtx_lock (struct mtx *mutex)
int mtx_trylock (struct mtx *mutex)
void mtx_unlock (struct mtx *mutex)
void mtx_destroy (struct mtx *mutex)
Class Documentation
mtx
struct mtx
Class Members
SemaphoreHandle_t sem
Macro Definition Documentation
MUTEX_INITIALIZER
#define MUTEX_INITIALIZER {.sem = 0}
Function Documentation
mtx_destroy()
void mtx_destroy (struct mtx * mutex)
References port_interruptNesting, portEND_SWITCHING_ISR, and mtx::sem.
Referenced by list_destroy().
mtx_init()
void mtx_init (struct mtx * mutex, const char * name, const char * type, int opts)
References port_interruptNesting, portEND_SWITCHING_ISR, and mtx::sem.
Referenced by list_init().
mtx_lock()
void mtx_lock (struct mtx * mutex)
References port_interruptNesting, portEND_SWITCHING_ISR, and mtx::sem.
Referenced by list_add(), list_destroy(), list_first(), list_get(), list_init(), list_next(), and list_remove().
mtx_trylock()
int mtx_trylock (struct mtx * mutex)
References mtx::sem.
mtx_unlock()
void mtx_unlock (struct mtx * mutex)
References port_interruptNesting, portEND_SWITCHING_ISR, and mtx::sem.
Referenced by list_add(), list_destroy(), list_first(), list_get(), list_init(), list_next(), and list_remove().