Projekt Ei: HardwareLife/Lcd/ESP32_TFT_library/components/spidriver/spi_master_lobo.c File Reference
spi_master_lobo.c File Reference
#include "freertos/FreeRTOS.h"
#include <string.h>
#include <stdio.h>
#include "soc/gpio_sig_map.h"
#include "soc/spi_reg.h"
#include "soc/dport_reg.h"
#include "soc/rtc_cntl_reg.h"
#include "esp32/rom/ets_sys.h"
#include "esp_types.h"
#include "esp_attr.h"
#include "esp_log.h"
#include "esp_err.h"
#include "freertos/semphr.h"
#include "freertos/xtensa_api.h"
#include "freertos/task.h"
#include "freertos/ringbuf.h"
#include "soc/soc.h"
#include "soc/uart_struct.h"
#include "driver/uart.h"
#include "driver/gpio.h"
#include "driver/periph_ctrl.h"
#include "esp_heap_caps.h"
#include "spi_master_lobo.h"
Classes
struct spi_signal_conn_t
Macros
#define SPI_CHECK(a, str, ret_val)
#define DMA_CHANNEL_ENABLED(dma_chan) (BIT(dma_chan-1))
Typedefs
typedef void(* dmaworkaround_cb_t) (void *arg)
Functions
void spi_lobo_setup_dma_desc_links (lldesc_t *dmadesc, int len, const uint8_t *data, bool isrx)
Setup a DMA link chain.
bool IRAM_ATTR spi_lobo_dmaworkaround_req_reset (int dmachan, dmaworkaround_cb_t cb, void *arg)
bool IRAM_ATTR spi_lobo_dmaworkaround_reset_in_progress ()
Check if a DMA reset is requested but has not completed yet.
void IRAM_ATTR spi_lobo_dmaworkaround_idle (int dmachan)
Mark a DMA channel as idle.
void IRAM_ATTR spi_lobo_dmaworkaround_transfer_active (int dmachan)
Mark a DMA channel as active.
bool spi_lobo_periph_claim (spi_lobo_host_device_t host)
bool spi_lobo_periph_free (spi_lobo_host_device_t host)
bool spi_lobo_dma_chan_claim (int dma_chan)
bool spi_lobo_dma_chan_free (int dma_chan)
esp_err_t spi_lobo_bus_add_device (spi_lobo_host_device_t host, spi_lobo_bus_config_t *bus_config, spi_lobo_device_interface_config_t *dev_config, spi_lobo_device_handle_t *handle)
Add a device. This allocates a CS line for the device, allocates memory for the device structure and hooks up the CS pin to whatever is specified.
esp_err_t spi_lobo_bus_remove_device (spi_lobo_device_handle_t handle)
Remove a device from the SPI bus. If after removal no other device is attached to the spi bus device, it is freed.
esp_err_t IRAM_ATTR spi_lobo_device_select (spi_lobo_device_handle_t handle, int force)
Select spi device for transmission.
esp_err_t IRAM_ATTR spi_lobo_device_deselect (spi_lobo_device_handle_t handle)
De-select spi device.
esp_err_t IRAM_ATTR spi_lobo_device_TakeSemaphore (spi_lobo_device_handle_t handle)
void IRAM_ATTR spi_lobo_device_GiveSemaphore (spi_lobo_device_handle_t handle)
uint32_t spi_lobo_get_speed (spi_lobo_device_handle_t handle)
Return the actuall SPI bus speed for the spi device in Hz.
uint32_t spi_lobo_set_speed (spi_lobo_device_handle_t handle, uint32_t speed)
Set the new clock speed for the device, return the actuall SPI bus speed set, in Hz This function can be used after the device is initialized.
bool spi_lobo_uses_native_pins (spi_lobo_device_handle_t handle)
Check if spi bus uses native spi pins.
void spi_lobo_get_native_pins (int host, int *sdi, int *sdo, int *sck)
Get spi bus native spi pins.
esp_err_t IRAM_ATTR spi_lobo_transfer_data (spi_lobo_device_handle_t handle, spi_lobo_transaction_t *trans)
Transimit and receive data to/from spi device based on transaction data.
Class Documentation
spi_signal_conn_t
struct spi_signal_conn_t
Class Members
spi_dev_t * hw
const uint8_t irq
const uint8_t irq_dma
const periph_module_t module
const uint8_t spiclk_native
const uint8_t spiclk_out
const uint8_t spics0_native
const uint8_t spics_out[3]
const uint8_t spid_in
const uint8_t spid_native
const uint8_t spid_out
const uint8_t spihd_in
const uint8_t spihd_native
const uint8_t spihd_out
const uint8_t spiq_in
const uint8_t spiq_native
const uint8_t spiq_out
const uint8_t spiwp_in
const uint8_t spiwp_native
const uint8_t spiwp_out
Macro Definition Documentation
DMA_CHANNEL_ENABLED
#define DMA_CHANNEL_ENABLED (dma_chan) (BIT(dma_chan-1))
SPI_CHECK
#define SPI_CHECK (a, str, ret_val)
Value:
if (!(a)) { \
        ESP_LOGE(SPI_TAG,"%s(%d): %s", __FUNCTION__, __LINE__, str); \
        return (ret_val); \
    }
Typedef Documentation
dmaworkaround_cb_t
typedef void(* dmaworkaround_cb_t) (void *arg)
Function Documentation
spi_lobo_bus_add_device()
esp_err_t spi_lobo_bus_add_device (spi_lobo_host_device_t host, spi_lobo_bus_config_t * bus_config, spi_lobo_device_interface_config_t * dev_config, spi_lobo_device_handle_t * handle)
Add a device. This allocates a CS line for the device, allocates memory for the device structure and hooks up the CS pin to whatever is specified.
This initializes the internal structures for a device, plus allocates a CS pin on the indicated SPI master peripheral and routes it to the indicated GPIO. All SPI master devices have three hw CS pins and can thus control up to three devices. Software handled CS pin can also be used for additional devices on the same SPI bus.
If selected SPI host device bus is not yet initialized, it is initialized first with 'bus_config' function
Note
While in general, speeds up to 80MHz on the dedicated SPI pins and 40MHz on GPIO-matrix-routed pins are supported, full-duplex transfers routed over the GPIO matrix only support speeds up to 26MHz.
Parameters
host SPI peripheral to allocate device on (HSPI or VSPI)
dev_config SPI interface protocol config for the device
bus_config Pointer to a spi_lobo_bus_config_t struct specifying how the host device bus should be initialized
handle Pointer to variable to hold the device handle
Returns
ESP_ERR_INVALID_ARG if parameter is invalid
ESP_ERR_NOT_FOUND if host doesn't have any free CS slots
ESP_ERR_NO_MEM if out of memory
ESP_OK on success
References TFT_SPI_HOST, and TFT_VSPI_HOST.
Referenced by app_main(), and TftDisplayBackend().
spi_lobo_bus_remove_device()
esp_err_t spi_lobo_bus_remove_device (spi_lobo_device_handle_t handle)
Remove a device from the SPI bus. If after removal no other device is attached to the spi bus device, it is freed.
Parameters
handle Device handle to free
Returns
ESP_ERR_INVALID_ARG if parameter is invalid
ESP_ERR_INVALID_STATE if device already is freed
ESP_OK on success
References spi_lobo_host_t::device, spi_lobo_device_t::host, spi_lobo_device_t::host_dev, and NO_DEV.
spi_lobo_device_deselect()
esp_err_t IRAM_ATTR spi_lobo_device_deselect (spi_lobo_device_handle_t handle)
De-select spi device.
If device's spics_io_num=-1 and spics_ext_io_num > 0 'spics_ext_io_num' pin is set to inactive state (high)
spi bus device's semaphore is given after selecting the device
Parameters
handle Device handle obtained using spi_lobo_bus_add_device
Returns
ESP_ERR_INVALID_ARG if parameter is invalid
ESP_OK on success
References spi_lobo_device_t::cfg, spi_lobo_host_t::cur_device, spi_lobo_host_t::device, spi_lobo_device_t::host, NO_DEV, spi_lobo_device_interface_config_t::selected, spi_lobo_host_t::spi_lobo_bus_mutex, spi_lobo_device_interface_config_t::spics_ext_io_num, and spi_lobo_device_interface_config_t::spics_io_num.
Referenced by app_main(), disp_deselect(), spi_lobo_get_speed(), spi_lobo_set_speed(), spi_lobo_transfer_data(), TFT_bmp_image(), and TftDisplayBackend().
spi_lobo_device_GiveSemaphore()
void IRAM_ATTR spi_lobo_device_GiveSemaphore (spi_lobo_device_handle_t handle)
References spi_lobo_device_t::host, and spi_lobo_host_t::spi_lobo_bus_mutex.
spi_lobo_device_select()
esp_err_t IRAM_ATTR spi_lobo_device_select (spi_lobo_device_handle_t handle, int force)
Select spi device for transmission.
It configures spi bus with selected spi device parameters if previously selected device was different than the current If device's spics_io_num=-1 and spics_ext_io_num > 0 'spics_ext_io_num' pin is set to active state (low)
spi bus device's semaphore is taken before selecting the device
Parameters
handle Device handle obtained using spi_lobo_bus_add_device
force configure spi bus even if the previous device was the same
Returns
ESP_ERR_INVALID_ARG if parameter is invalid
ESP_OK on success
References spi_lobo_device_t::bus_config, spi_lobo_device_t::cfg, spi_lobo_host_t::cur_bus_config, spi_lobo_host_t::device, spi_lobo_device_t::host, NO_DEV, spi_lobo_device_interface_config_t::selected, spi_lobo_host_t::spi_lobo_bus_mutex, and SPI_SEMAPHORE_WAIT.
Referenced by app_main(), disp_select(), spi_lobo_get_speed(), spi_lobo_set_speed(), spi_lobo_transfer_data(), TFT_bmp_image(), TftDisplayBackend(), and touch_get_data().
spi_lobo_device_TakeSemaphore()
esp_err_t IRAM_ATTR spi_lobo_device_TakeSemaphore (spi_lobo_device_handle_t handle)
References spi_lobo_device_t::host, spi_lobo_host_t::spi_lobo_bus_mutex, and SPI_SEMAPHORE_WAIT.
spi_lobo_dma_chan_claim()
bool spi_lobo_dma_chan_claim (int dma_chan)
spi_lobo_dma_chan_free()
bool spi_lobo_dma_chan_free (int dma_chan)
spi_lobo_dmaworkaround_idle()
void IRAM_ATTR spi_lobo_dmaworkaround_idle (int dmachan)
Mark a DMA channel as idle.
A call to this function tells the workaround logic that this channel will not be affected by a global SPI DMA reset.
spi_lobo_dmaworkaround_req_reset()
bool IRAM_ATTR spi_lobo_dmaworkaround_req_reset (int dmachan, dmaworkaround_cb_t cb, void * arg)
spi_lobo_dmaworkaround_reset_in_progress()
bool IRAM_ATTR spi_lobo_dmaworkaround_reset_in_progress ()
Check if a DMA reset is requested but has not completed yet.
Returns
True when a DMA reset is requested but hasn't completed yet. False otherwise.
spi_lobo_dmaworkaround_transfer_active()
void IRAM_ATTR spi_lobo_dmaworkaround_transfer_active (int dmachan)
Mark a DMA channel as active.
A call to this function tells the workaround logic that this channel will be affected by a global SPI DMA reset, and a reset like that should not be attempted.
spi_lobo_get_native_pins()
void spi_lobo_get_native_pins (int host, int * sdi, int * sdo, int * sck)
Get spi bus native spi pins.
Parameters
handle Device handle obtained using spi_lobo_bus_add_device
Returns
places spi bus native pins in provided pointers
References spi_signal_conn_t::spiclk_native, spi_signal_conn_t::spid_native, and spi_signal_conn_t::spiq_native.
spi_lobo_get_speed()
uint32_t spi_lobo_get_speed (spi_lobo_device_handle_t handle)
Return the actuall SPI bus speed for the spi device in Hz.
Some frequencies cannot be set, for example 30000000 will actually set SPI clock to 26666666 Hz
Parameters
handle Device handle obtained using spi_lobo_bus_add_device
Returns
actuall SPI clock
References spi_lobo_device_t::host, spi_lobo_host_t::hw, spi_lobo_device_deselect(), and spi_lobo_device_select().
Referenced by app_main(), find_rd_speed(), and read_data().
spi_lobo_periph_claim()
bool spi_lobo_periph_claim (spi_lobo_host_device_t host)
spi_lobo_periph_free()
bool spi_lobo_periph_free (spi_lobo_host_device_t host)
spi_lobo_set_speed()
uint32_t spi_lobo_set_speed (spi_lobo_device_handle_t handle, uint32_t speed)
Set the new clock speed for the device, return the actuall SPI bus speed set, in Hz This function can be used after the device is initialized.
Some frequencies cannot be set, for example 30000000 will actually set SPI clock to 26666666 Hz
Parameters
handle Device handle obtained using spi_lobo_bus_add_device
speed New device spi clock to be set in Hz
Returns
actuall SPI clock
0 if speed cannot be set
References spi_lobo_device_t::cfg, spi_lobo_device_interface_config_t::clock_speed_hz, spi_lobo_device_t::host, spi_lobo_host_t::hw, spi_lobo_device_deselect(), and spi_lobo_device_select().
Referenced by app_main(), find_rd_speed(), read_data(), and TftDisplayBackend().
spi_lobo_setup_dma_desc_links()
void spi_lobo_setup_dma_desc_links (lldesc_t * dmadesc, int len, const uint8_t * data, bool isrx)
Setup a DMA link chain.
This routine will set up a chain of linked DMA descriptors in the array pointed to by dmadesc. Enough DMA descriptors will be used to fit the buffer of len bytes in, and the descriptors will point to the corresponding positions in buffer and linked together. The end result is that feeding dmadesc[0] into DMA hardware results in the entirety len bytes of data being read or written.
Parameters
dmadesc Pointer to array of DMA descriptors big enough to be able to convey len bytes
len Length of buffer
data Data buffer to use for DMA transfer
isrx True if data is to be written into data, false if it's to be read from data.
References SPI_MAX_DMA_LEN.
spi_lobo_transfer_data()
esp_err_t IRAM_ATTR spi_lobo_transfer_data (spi_lobo_device_handle_t handle, spi_lobo_transaction_t * trans)
Transimit and receive data to/from spi device based on transaction data.
TRANSMIT 8-bit data to spi device from 'trans->tx_buffer' or 'trans->tx_data' (trans->lenght/8 bytes) and RECEIVE data to 'trans->rx_buffer' or 'trans->rx_data' (trans->rx_length/8 bytes) Lengths must be 8-bit multiples! If trans->rx_buffer is NULL or trans->rx_length is 0, only transmits data If trans->tx_buffer is NULL or trans->length is 0, only receives data If the device is in duplex mode (LB_SPI_DEVICE_HALFDUPLEX flag NOT set), data are transmitted and received simultaneously. If the device is in half duplex mode (LB_SPI_DEVICE_HALFDUPLEX flag IS set), data are received after transmission 'address', 'command' and 'dummy bits' are transmitted before data phase IF set in device's configuration and IF 'trans->length' and 'trans->rx_length' are NOT both 0 If device was not previously selected, it will be selected before transmission and deselected after transmission.
Parameters
handle Device handle obtained using spi_lobo_bus_add_device
trans Pointer to variable containing the description of the transaction that is executed
Returns
ESP_ERR_INVALID_ARG if parameter is invalid
ESP error code if device cannot be selected
ESP_OK on success
References spi_lobo_transaction_t::address, spi_lobo_device_interface_config_t::address_bits, spi_lobo_device_t::cfg, spi_lobo_transaction_t::command, spi_lobo_device_interface_config_t::flags, spi_lobo_transaction_t::flags, spi_lobo_device_t::host, spi_lobo_host_t::hw, LB_SPI_DEVICE_HALFDUPLEX, LB_SPI_TRANS_USE_RXDATA, LB_SPI_TRANS_USE_TXDATA, spi_lobo_transaction_t::length, spi_lobo_device_interface_config_t::post_cb, spi_lobo_device_interface_config_t::pre_cb, spi_lobo_transaction_t::rxlength, spi_lobo_device_interface_config_t::selected, spi_lobo_device_deselect(), and spi_lobo_device_select().
spi_lobo_uses_native_pins()
bool spi_lobo_uses_native_pins (spi_lobo_device_handle_t handle)
Check if spi bus uses native spi pins.
Parameters
handle Device handle obtained using spi_lobo_bus_add_device
Returns
true if native spi pins are used
false if spi pins are routed through gpio matrix
References spi_lobo_device_t::host, and spi_lobo_host_t::no_gpio_matrix.
Referenced by app_main().