Projekt Ei: HardwareLife/Lcd/ESP32_TFT_library/components/spiffs/spiffs_vfs.h File Reference
spiffs_vfs.h File Reference
Macros
#define SPIFFS_BASE_PATH "/spiffs"
Functions
void vfs_spiffs_register ()
int spiffs_mount ()
int spiffs_unmount (int unreg)
void spiffs_fs_stat (uint32_t *total, uint32_t *used)
Variables
int spiffs_is_registered
int spiffs_is_mounted
Macro Definition Documentation
SPIFFS_BASE_PATH
#define SPIFFS_BASE_PATH "/spiffs"
Function Documentation
spiffs_fs_stat()
void spiffs_fs_stat (uint32_t * total, uint32_t * used)
References SPIFFS_info(), and SPIFFS_OK.
spiffs_mount()
int spiffs_mount ()
References spiffs_is_mounted, and spiffs_is_registered.
spiffs_unmount()
int spiffs_unmount (int unreg)
References spiffs_is_mounted, spiffs_is_registered, and SPIFFS_unmount().
vfs_spiffs_register()
void vfs_spiffs_register ()
References spiffs_is_registered, and spiffs_mutex.
Referenced by TftDisplayBackend().
Variable Documentation
spiffs_is_mounted
int spiffs_is_mounted
spiffs_is_registered
int spiffs_is_registered