Projekt Ei: HardwareLife/Lcd/ESP32_TFT_library/components/spiffs/spiffs_vfs.c File Reference
spiffs_vfs.c File Reference
#include <freertos/FreeRTOS.h>
#include <string.h>
#include <stdio.h>
#include <limits.h>
#include "esp_log.h"
#include <sys/stat.h>
#include "esp_vfs.h"
#include "esp_attr.h"
#include <errno.h>
#include <spiffs_vfs.h>
#include <spiffs.h>
#include <esp_spiffs.h>
#include <spiffs_nucleus.h>
#include "list.h"
#include <sys/fcntl.h>
#include <sys/dirent.h>
#include "sdkconfig.h"
Classes
struct vfs_spiffs_dir_t
struct vfs_spiffs_file_t
struct spiffs_metadata_t
Macros
#define PATH_MAX MAXNAMLEN+8
#define SPIFFS_ERASE_SIZE 4096
Functions
void spiffs_fs_stat (uint32_t *total, uint32_t *used)
int spiffs_mount ()
void vfs_spiffs_register ()
int spiffs_unmount (int unreg)
Variables
int spiffs_is_registered = 0
int spiffs_is_mounted = 0
QueueHandle_t spiffs_mutex = NULL
Class Documentation
vfs_spiffs_dir_t
struct vfs_spiffs_dir_t
Class Members
DIR dir
struct dirent ent
char path[MAXNAMLEN+1]
uint8_t read_mount
spiffs_DIR spiffs_dir
vfs_spiffs_file_t
struct vfs_spiffs_file_t
Class Members
uint8_t is_dir
char path[MAXNAMLEN+1]
spiffs_file spiffs_file
spiffs_metadata_t
struct spiffs_metadata_t
Class Members
time_t atime
time_t ctime
time_t mtime
uint8_t spare[SPIFFS_OBJ_META_LEN -(sizeof(time_t) *3)]
Macro Definition Documentation
PATH_MAX
#define PATH_MAX MAXNAMLEN+8
SPIFFS_ERASE_SIZE
#define SPIFFS_ERASE_SIZE 4096
Function Documentation
spiffs_fs_stat()
void spiffs_fs_stat (uint32_t * total, uint32_t * used)
References SPIFFS_info(), and SPIFFS_OK.
spiffs_mount()
int spiffs_mount ()
References spiffs_is_mounted, and spiffs_is_registered.
spiffs_unmount()
int spiffs_unmount (int unreg)
References spiffs_is_mounted, spiffs_is_registered, and SPIFFS_unmount().
vfs_spiffs_register()
void vfs_spiffs_register ()
References spiffs_is_registered, and spiffs_mutex.
Referenced by TftDisplayBackend().
Variable Documentation
spiffs_is_mounted
int spiffs_is_mounted = 0
Referenced by spiffs_mount(), and spiffs_unmount().
spiffs_is_registered
int spiffs_is_registered = 0
Referenced by spiffs_mount(), spiffs_unmount(), and vfs_spiffs_register().
spiffs_mutex
QueueHandle_t spiffs_mutex = NULL
Referenced by vfs_spiffs_register().