Projekt Ei: HardwareLife/Lcd/ESP32_TFT_library/components/spiffs/spiffs_nucleus.c File Reference
spiffs_nucleus.c File Reference
#include "spiffs.h"
#include "spiffs_nucleus.h"
Classes
struct spiffs_ix_map_populate_state
struct spiffs_free_obj_id_state
Functions
s32_t spiffs_phys_cpy (spiffs *fs, spiffs_file fh, u32_t dst, u32_t src, u32_t len)
s32_t spiffs_obj_lu_find_entry_visitor (spiffs *fs, spiffs_block_ix starting_block, int starting_lu_entry, u8_t flags, spiffs_obj_id obj_id, spiffs_visitor_f v, const void *user_const_p, void *user_var_p, spiffs_block_ix *block_ix, int *lu_entry)
s32_t spiffs_erase_block (spiffs *fs, spiffs_block_ix bix)
s32_t spiffs_probe (spiffs_config *cfg)
s32_t spiffs_obj_lu_scan (spiffs *fs)
s32_t spiffs_obj_lu_find_free (spiffs *fs, spiffs_block_ix starting_block, int starting_lu_entry, spiffs_block_ix *block_ix, int *lu_entry)
s32_t spiffs_obj_lu_find_id (spiffs *fs, spiffs_block_ix starting_block, int starting_lu_entry, spiffs_obj_id obj_id, spiffs_block_ix *block_ix, int *lu_entry)
s32_t spiffs_obj_lu_find_id_and_span (spiffs *fs, spiffs_obj_id obj_id, spiffs_span_ix spix, spiffs_page_ix exclusion_pix, spiffs_page_ix *pix)
s32_t spiffs_obj_lu_find_id_and_span_by_phdr (spiffs *fs, spiffs_obj_id obj_id, spiffs_span_ix spix, spiffs_page_ix exclusion_pix, spiffs_page_ix *pix)
s32_t spiffs_populate_ix_map (spiffs *fs, spiffs_fd *fd, u32_t vec_entry_start, u32_t vec_entry_end)
s32_t spiffs_page_allocate_data (spiffs *fs, spiffs_obj_id obj_id, spiffs_page_header *ph, u8_t *data, u32_t len, u32_t page_offs, u8_t finalize, spiffs_page_ix *pix)
s32_t spiffs_page_move (spiffs *fs, spiffs_file fh, u8_t *page_data, spiffs_obj_id obj_id, spiffs_page_header *page_hdr, spiffs_page_ix src_pix, spiffs_page_ix *dst_pix)
s32_t spiffs_page_delete (spiffs *fs, spiffs_page_ix pix)
s32_t spiffs_object_create (spiffs *fs, spiffs_obj_id obj_id, const u8_t name[], const u8_t meta[], spiffs_obj_type type, spiffs_page_ix *objix_hdr_pix)
s32_t spiffs_object_update_index_hdr (spiffs *fs, spiffs_fd *fd, spiffs_obj_id obj_id, spiffs_page_ix objix_hdr_pix, u8_t *new_objix_hdr_data, const u8_t name[], const u8_t meta[], u32_t size, spiffs_page_ix *new_pix)
void spiffs_cb_object_event (spiffs *fs, spiffs_page_object_ix *objix, int ev, spiffs_obj_id obj_id_raw, spiffs_span_ix spix, spiffs_page_ix new_pix, u32_t new_size)
s32_t spiffs_object_open_by_id (spiffs *fs, spiffs_obj_id obj_id, spiffs_fd *fd, spiffs_flags flags, spiffs_mode mode)
s32_t spiffs_object_open_by_page (spiffs *fs, spiffs_page_ix pix, spiffs_fd *fd, spiffs_flags flags, spiffs_mode mode)
s32_t spiffs_object_append (spiffs_fd *fd, u32_t offset, u8_t *data, u32_t len)
s32_t spiffs_object_modify (spiffs_fd *fd, u32_t offset, u8_t *data, u32_t len)
s32_t spiffs_object_find_object_index_header_by_name (spiffs *fs, const u8_t name[SPIFFS_OBJ_NAME_LEN], spiffs_page_ix *pix)
s32_t spiffs_object_truncate (spiffs_fd *fd, u32_t new_size, u8_t remove_full)
s32_t spiffs_object_read (spiffs_fd *fd, u32_t offset, u32_t len, u8_t *dst)
s32_t spiffs_obj_lu_find_free_obj_id (spiffs *fs, spiffs_obj_id *obj_id, const u8_t *conflicting_name)
s32_t spiffs_fd_find_new (spiffs *fs, spiffs_fd **fd, const char *name)
s32_t spiffs_fd_return (spiffs *fs, spiffs_file f)
s32_t spiffs_fd_get (spiffs *fs, spiffs_file f, spiffs_fd **fd)
void spiffs_fd_temporal_cache_rehash (spiffs *fs, const char *old_path, const char *new_path)
Class Documentation
spiffs_ix_map_populate_state
struct spiffs_ix_map_populate_state
Class Members
spiffs_fd * fd
spiffs_span_ix map_objix_end_spix
spiffs_span_ix map_objix_start_spix
u32_t remaining_objix_pages_to_visit
spiffs_free_obj_id_state
struct spiffs_free_obj_id_state
Class Members
u32_t compaction
const u8_t * conflicting_name
spiffs_obj_id max_obj_id
spiffs_obj_id min_obj_id
Function Documentation
spiffs_cb_object_event()
void spiffs_cb_object_event (spiffs * fs, spiffs_page_object_ix * objix, int ev, spiffs_obj_id obj_id_raw, spiffs_span_ix spix, spiffs_page_ix new_pix, u32_t new_size)
References _SPIPRIfd, _SPIPRIi, _SPIPRIid, _SPIPRIpg, _SPIPRIsp, spiffs_fd::cursor_objix_pix, spiffs_fd::cursor_objix_spix, spiffs_t::fd_count, spiffs_t::fd_space, spiffs_fd::file_nbr, spiffs_dirent::obj_id, spiffs_fd::obj_id, spiffs_fd::objix_hdr_pix, spiffs_fd::size, SPIFFS_DBG, SPIFFS_EV_IX_DEL, SPIFFS_EV_IX_NEW, SPIFFS_EV_IX_UPD, SPIFFS_OBJ_ID_DELETED, and SPIFFS_OBJ_ID_IX_FLAG.
spiffs_erase_block()
s32_t spiffs_erase_block (spiffs * fs, spiffs_block_ix bix)
References _spiffs_wr, _SPIPRIad, _SPIPRIi, spiffs_t::free_blocks, spiffs_t::max_erase_count, spiffs_dirent::size, SPIFFS_BLOCK_TO_PADDR, SPIFFS_CFG_LOG_BLOCK_SZ, SPIFFS_CFG_PHYS_ERASE_SZ, SPIFFS_CHECK_RES, SPIFFS_DBG, SPIFFS_ERASE_COUNT_PADDR, SPIFFS_HAL_ERASE, SPIFFS_MAGIC_PADDR, SPIFFS_OBJ_ID_IX_FLAG, SPIFFS_OP_C_WRTHRU, and SPIFFS_OP_T_OBJ_LU2.
spiffs_fd_find_new()
s32_t spiffs_fd_find_new (spiffs * fs, spiffs_fd ** fd, const char * name)
spiffs_fd_get()
s32_t spiffs_fd_get (spiffs * fs, spiffs_file f, spiffs_fd ** fd)
References spiffs_t::fd_count, spiffs_t::fd_space, SPIFFS_ERR_BAD_DESCRIPTOR, SPIFFS_ERR_FILE_CLOSED, and SPIFFS_OK.
spiffs_fd_return()
s32_t spiffs_fd_return (spiffs * fs, spiffs_file f)
References spiffs_t::fd_count, spiffs_t::fd_space, spiffs_fd::file_nbr, SPIFFS_ERR_BAD_DESCRIPTOR, SPIFFS_ERR_FILE_CLOSED, and SPIFFS_OK.
spiffs_fd_temporal_cache_rehash()
void spiffs_fd_temporal_cache_rehash (spiffs * fs, const char * old_path, const char * new_path)
spiffs_obj_lu_find_entry_visitor()
s32_t spiffs_obj_lu_find_entry_visitor (spiffs * fs, spiffs_block_ix starting_block, int starting_lu_entry, u8_t flags, spiffs_obj_id obj_id, spiffs_visitor_f v, const void * user_const_p, void * user_var_p, spiffs_block_ix * block_ix, int * lu_entry)
References _spiffs_rd, spiffs_t::block_count, spiffs_t::lu_work, SPIFFS_CFG_LOG_BLOCK_SZ, SPIFFS_CFG_LOG_PAGE_SZ, SPIFFS_CHECK_RES, SPIFFS_OBJ_LOOKUP_MAX_ENTRIES, SPIFFS_OBJ_LOOKUP_PAGES, SPIFFS_OK, SPIFFS_OP_C_READ, SPIFFS_OP_T_OBJ_LU, SPIFFS_PAGE_TO_PADDR, SPIFFS_VIS_CHECK_ID, SPIFFS_VIS_CHECK_PH, SPIFFS_VIS_COUNTINUE, SPIFFS_VIS_COUNTINUE_RELOAD, SPIFFS_VIS_END, and SPIFFS_VIS_NO_WRAP.
spiffs_obj_lu_find_free()
s32_t spiffs_obj_lu_find_free (spiffs * fs, spiffs_block_ix starting_block, int starting_lu_entry, spiffs_block_ix * block_ix, int * lu_entry)
References spiffs_t::cleaning, spiffs_t::free_blocks, spiffs_t::free_cursor_block_ix, spiffs_t::free_cursor_obj_lu_entry, SPIFFS_CHECK_RES, SPIFFS_DBG, SPIFFS_ERR_FULL, SPIFFS_ERR_NO_DELETED_BLOCKS, spiffs_gc_quick(), SPIFFS_OBJ_ID_FREE, spiffs_obj_lu_find_id(), and SPIFFS_OK.
spiffs_obj_lu_find_free_obj_id()
s32_t spiffs_obj_lu_find_free_obj_id (spiffs * fs, spiffs_obj_id * obj_id, const u8_t * conflicting_name)
References _SPIPRIid, spiffs_t::block_count, spiffs_free_obj_id_state::compaction, spiffs_free_obj_id_state::conflicting_name, spiffs_free_obj_id_state::max_obj_id, spiffs_free_obj_id_state::min_obj_id, SPIFFS_CFG_LOG_PAGE_SZ, SPIFFS_DBG, SPIFFS_OBJ_ID_FREE, SPIFFS_OBJ_ID_IX_FLAG, SPIFFS_OBJ_LOOKUP_MAX_ENTRIES, spiffs_obj_lu_find_entry_visitor(), SPIFFS_OK, and spiffs_t::work.
spiffs_obj_lu_find_id()
s32_t spiffs_obj_lu_find_id (spiffs * fs, spiffs_block_ix starting_block, int starting_lu_entry, spiffs_obj_id obj_id, spiffs_block_ix * block_ix, int * lu_entry)
References SPIFFS_ERR_NOT_FOUND, spiffs_obj_lu_find_entry_visitor(), SPIFFS_VIS_CHECK_ID, and SPIFFS_VIS_END.
spiffs_obj_lu_find_id_and_span()
s32_t spiffs_obj_lu_find_id_and_span (spiffs * fs, spiffs_obj_id obj_id, spiffs_span_ix spix, spiffs_page_ix exclusion_pix, spiffs_page_ix * pix)
References spiffs_t::cursor_block_ix, spiffs_t::cursor_obj_lu_entry, spiffs_obj_lu_find_entry_visitor(), and SPIFFS_VIS_CHECK_ID.
spiffs_obj_lu_find_id_and_span_by_phdr()
s32_t spiffs_obj_lu_find_id_and_span_by_phdr (spiffs * fs, spiffs_obj_id obj_id, spiffs_span_ix spix, spiffs_page_ix exclusion_pix, spiffs_page_ix * pix)
References spiffs_t::cursor_block_ix, spiffs_t::cursor_obj_lu_entry, spiffs_obj_lu_find_entry_visitor(), and SPIFFS_VIS_CHECK_PH.
spiffs_obj_lu_scan()
s32_t spiffs_obj_lu_scan (spiffs * fs)
References _spiffs_rd, _SPIPRIbl, spiffs_t::free_blocks, MAX, spiffs_t::max_erase_count, MIN, SPIFFS_CHECK_RES, SPIFFS_DBG, spiffs_erase_block(), SPIFFS_ERASE_COUNT_PADDR, SPIFFS_ERR_NOT_A_FS, SPIFFS_ERR_RO_ABORTED_OPERATION, SPIFFS_MAGIC_PADDR, SPIFFS_OBJ_ID_FREE, spiffs_obj_lu_find_entry_visitor(), SPIFFS_OP_C_READ, SPIFFS_OP_T_OBJ_LU2, spiffs_t::stats_p_allocated, and spiffs_t::stats_p_deleted.
spiffs_object_append()
s32_t spiffs_object_append (spiffs_fd * fd, u32_t offset, u8_t * data, u32_t len)
References _SPIPRIi, _SPIPRIid, _SPIPRIpg, _SPIPRIsp, spiffs_fd::fs, spiffs_fd::obj_id, spiffs_fd::objix_hdr_pix, spiffs_fd::size, SPIFFS_CHECK_RES, SPIFFS_DATA_PAGE_SIZE, SPIFFS_DBG, spiffs_gc_check(), SPIFFS_OBJ_IX_ENTRY_SPAN_IX, SPIFFS_OK, spiffs_page_header, spiffs_page_object_ix, spiffs_page_object_ix_header, and spiffs_t::work.
spiffs_object_create()
s32_t spiffs_object_create (spiffs * fs, spiffs_obj_id obj_id, const u8_t name[], const u8_t meta[], spiffs_obj_type type, spiffs_page_ix * objix_hdr_pix)
References _spiffs_wr, _SPIPRIbl, _SPIPRIpg, _SPIPRIsp, spiffs_t::free_cursor_block_ix, spiffs_t::free_cursor_obj_lu_entry, spiffs_dirent::obj_id, SPIFFS_BLOCK_TO_PADDR, spiffs_cb_object_event(), SPIFFS_CHECK_RES, SPIFFS_DATA_PAGE_SIZE, SPIFFS_DBG, SPIFFS_EV_IX_NEW, spiffs_gc_check(), SPIFFS_OBJ_ID_IX_FLAG, SPIFFS_OBJ_LOOKUP_ENTRY_TO_PADDR, SPIFFS_OBJ_LOOKUP_ENTRY_TO_PIX, spiffs_obj_lu_find_free(), SPIFFS_OBJ_META_LEN, SPIFFS_OBJ_NAME_LEN, SPIFFS_OK, SPIFFS_OP_C_UPDT, SPIFFS_OP_T_OBJ_DA, SPIFFS_OP_T_OBJ_LU, spiffs_page_object_ix, spiffs_page_object_ix_header, SPIFFS_PH_FLAG_FINAL, SPIFFS_PH_FLAG_INDEX, SPIFFS_PH_FLAG_USED, SPIFFS_UNDEFINED_LEN, spiffs_t::stats_p_allocated, and spiffs_dirent::type.
spiffs_object_find_object_index_header_by_name()
s32_t spiffs_object_find_object_index_header_by_name (spiffs * fs, const u8_t name[SPIFFS_OBJ_NAME_LEN], spiffs_page_ix * pix)
References spiffs_t::cursor_block_ix, spiffs_t::cursor_obj_lu_entry, and spiffs_obj_lu_find_entry_visitor().
spiffs_object_modify()
s32_t spiffs_object_modify (spiffs_fd * fd, u32_t offset, u8_t * data, u32_t len)
References _SPIPRIi, _SPIPRIpg, _SPIPRIsp, spiffs_fd::fs, spiffs_fd::obj_id, spiffs_fd::objix_hdr_pix, SPIFFS_CHECK_RES, SPIFFS_DATA_PAGE_SIZE, SPIFFS_DBG, spiffs_gc_check(), SPIFFS_OBJ_IX_ENTRY_SPAN_IX, spiffs_object_update_index_hdr(), SPIFFS_OK, spiffs_page_header, spiffs_page_object_ix, spiffs_page_object_ix_header, and spiffs_t::work.
spiffs_object_open_by_id()
s32_t spiffs_object_open_by_id (spiffs * fs, spiffs_obj_id obj_id, spiffs_fd * fd, spiffs_flags flags, spiffs_mode mode)
References spiffs_dirent::pix, SPIFFS_CHECK_RES, SPIFFS_OBJ_ID_IX_FLAG, spiffs_obj_lu_find_id_and_span(), spiffs_object_open_by_page(), and SPIFFS_OK.
spiffs_object_open_by_page()
s32_t spiffs_object_open_by_page (spiffs * fs, spiffs_page_ix pix, spiffs_fd * fd, spiffs_flags flags, spiffs_mode mode)
References _spiffs_rd, spiffs_fd::file_nbr, spiffs_fd::fs, spiffs_dirent::obj_id, SPIFFS_BLOCK_FOR_PAGE, SPIFFS_BLOCK_TO_PADDR, SPIFFS_CHECK_RES, SPIFFS_OBJ_LOOKUP_ENTRY_FOR_PAGE, SPIFFS_OK, SPIFFS_OP_C_READ, SPIFFS_OP_T_OBJ_IX, SPIFFS_OP_T_OBJ_LU, spiffs_page_object_ix_header, and SPIFFS_PAGE_TO_PADDR.
spiffs_object_read()
s32_t spiffs_object_read (spiffs_fd * fd, u32_t offset, u32_t len, u8_t * dst)
References _spiffs_rd, _SPIPRIad, _SPIPRIi, _SPIPRIid, _SPIPRIpg, _SPIPRIsp, spiffs_fd::cursor_objix_pix, spiffs_fd::cursor_objix_spix, spiffs_fd::file_nbr, spiffs_fd::fs, MIN, spiffs_fd::obj_id, spiffs_fd::objix_hdr_pix, spiffs_fd::offset, spiffs_fd::size, SPIFFS_CFG_LOG_PAGE_SZ, SPIFFS_CHECK_RES, SPIFFS_DATA_PAGE_SIZE, SPIFFS_DBG, SPIFFS_ERR_END_OF_OBJECT, SPIFFS_OBJ_ID_IX_FLAG, SPIFFS_OBJ_IX_ENTRY, SPIFFS_OBJ_IX_ENTRY_SPAN_IX, spiffs_obj_lu_find_id_and_span(), SPIFFS_OK, SPIFFS_OP_C_READ, SPIFFS_OP_T_OBJ_IX, spiffs_page_header, spiffs_page_object_ix, spiffs_page_object_ix_header, SPIFFS_PAGE_TO_PADDR, SPIFFS_VALIDATE_OBJIX, and spiffs_t::work.
spiffs_object_truncate()
s32_t spiffs_object_truncate (spiffs_fd * fd, u32_t new_size, u8_t remove_full)
References _spiffs_wr, _SPIPRIpg, _SPIPRIsp, spiffs_fd::file_nbr, spiffs_fd::fs, spiffs_fd::objix_hdr_pix, spiffs_fd::size, SPIFFS_CHECK_RES, SPIFFS_DATA_PAGE_SIZE, SPIFFS_DBG, spiffs_gc_check(), SPIFFS_OBJ_IX_ENTRY_SPAN_IX, SPIFFS_OK, SPIFFS_OP_C_UPDT, SPIFFS_OP_T_OBJ_IX, spiffs_page_header, spiffs_page_object_ix, spiffs_page_object_ix_header, SPIFFS_PAGE_TO_PADDR, SPIFFS_PH_FLAG_FINAL, SPIFFS_PH_FLAG_INDEX, SPIFFS_PH_FLAG_IXDELE, SPIFFS_PH_FLAG_USED, SPIFFS_UNDEFINED_LEN, and spiffs_t::work.
spiffs_object_update_index_hdr()
s32_t spiffs_object_update_index_hdr (spiffs * fs, spiffs_fd * fd, spiffs_obj_id obj_id, spiffs_page_ix objix_hdr_pix, u8_t * new_objix_hdr_data, const u8_t name[], const u8_t meta[], u32_t size, spiffs_page_ix * new_pix)
References _spiffs_rd, spiffs_fd::file_nbr, spiffs_fd::objix_hdr_pix, spiffs_dirent::size, spiffs_cb_object_event(), SPIFFS_CFG_LOG_PAGE_SZ, SPIFFS_CHECK_RES, SPIFFS_EV_IX_UPD, SPIFFS_EV_IX_UPD_HDR, SPIFFS_OBJ_ID_IX_FLAG, SPIFFS_OBJ_META_LEN, SPIFFS_OBJ_NAME_LEN, SPIFFS_OK, SPIFFS_OP_C_READ, SPIFFS_OP_T_OBJ_IX, spiffs_page_move(), spiffs_page_object_ix, spiffs_page_object_ix_header, SPIFFS_PAGE_TO_PADDR, SPIFFS_VALIDATE_OBJIX, and spiffs_t::work.
spiffs_page_allocate_data()
s32_t spiffs_page_allocate_data (spiffs * fs, spiffs_obj_id obj_id, spiffs_page_header * ph, u8_t * data, u32_t len, u32_t page_offs, u8_t finalize, spiffs_page_ix * pix)
References _spiffs_wr, spiffs_t::free_cursor_block_ix, spiffs_t::free_cursor_obj_lu_entry, SPIFFS_BLOCK_TO_PADDR, SPIFFS_CHECK_RES, SPIFFS_OBJ_LOOKUP_ENTRY_TO_PADDR, SPIFFS_OBJ_LOOKUP_ENTRY_TO_PIX, spiffs_obj_lu_find_free(), SPIFFS_OK, SPIFFS_OP_C_UPDT, SPIFFS_OP_T_OBJ_DA, SPIFFS_OP_T_OBJ_LU, spiffs_page_header, SPIFFS_PH_FLAG_FINAL, SPIFFS_PH_FLAG_USED, and spiffs_t::stats_p_allocated.
spiffs_page_delete()
s32_t spiffs_page_delete (spiffs * fs, spiffs_page_ix pix)
References _spiffs_wr, SPIFFS_BLOCK_FOR_PAGE, SPIFFS_BLOCK_TO_PADDR, SPIFFS_CHECK_RES, SPIFFS_OBJ_ID_DELETED, SPIFFS_OBJ_LOOKUP_ENTRY_FOR_PAGE, SPIFFS_OP_C_DELE, SPIFFS_OP_T_OBJ_DA, SPIFFS_OP_T_OBJ_LU, spiffs_page_header, SPIFFS_PAGE_TO_PADDR, SPIFFS_PH_FLAG_DELET, SPIFFS_PH_FLAG_USED, spiffs_t::stats_p_allocated, and spiffs_t::stats_p_deleted.
spiffs_page_move()
s32_t spiffs_page_move (spiffs * fs, spiffs_file fh, u8_t * page_data, spiffs_obj_id obj_id, spiffs_page_header * page_hdr, spiffs_page_ix src_pix, spiffs_page_ix * dst_pix)
References _spiffs_wr, spiffs_t::free_cursor_block_ix, spiffs_t::free_cursor_obj_lu_entry, SPIFFS_BLOCK_FOR_PAGE, SPIFFS_BLOCK_TO_PADDR, SPIFFS_CFG_LOG_PAGE_SZ, SPIFFS_CHECK_RES, SPIFFS_OBJ_LOOKUP_ENTRY_FOR_PAGE, SPIFFS_OBJ_LOOKUP_ENTRY_TO_PIX, spiffs_obj_lu_find_free(), SPIFFS_OP_C_UPDT, SPIFFS_OP_T_OBJ_DA, SPIFFS_OP_T_OBJ_LU, spiffs_page_delete(), spiffs_page_header, SPIFFS_PAGE_TO_PADDR, SPIFFS_PH_FLAG_FINAL, SPIFFS_PH_FLAG_USED, spiffs_phys_cpy(), and spiffs_t::stats_p_allocated.
spiffs_phys_cpy()
s32_t spiffs_phys_cpy (spiffs * fs, spiffs_file fh, u32_t dst, u32_t src, u32_t len)
References _spiffs_rd, _spiffs_wr, MIN, SPIFFS_CHECK_RES, SPIFFS_COPY_BUFFER_STACK, SPIFFS_OK, SPIFFS_OP_C_MOVD, SPIFFS_OP_C_MOVS, and SPIFFS_OP_T_OBJ_DA.
spiffs_populate_ix_map()
s32_t spiffs_populate_ix_map (spiffs * fs, spiffs_fd * fd, u32_t vec_entry_start, u32_t vec_entry_end)
References spiffs_ix_map::end_spix, spiffs_ix_map_populate_state::fd, spiffs_ix_map_populate_state::map_objix_end_spix, spiffs_ix_map_populate_state::map_objix_start_spix, MAX, MIN, spiffs_fd::obj_id, spiffs_fd::objix_hdr_pix, spiffs_ix_map_populate_state::remaining_objix_pages_to_visit, SPIFFS_BLOCK_FOR_PAGE, SPIFFS_ERR_IX_MAP_BAD_RANGE, SPIFFS_OBJ_ID_IX_FLAG, SPIFFS_OBJ_IX_ENTRY_SPAN_IX, SPIFFS_OBJ_LOOKUP_ENTRY_FOR_PAGE, spiffs_obj_lu_find_entry_visitor(), SPIFFS_VIS_CHECK_ID, and spiffs_ix_map::start_spix.
spiffs_probe()
s32_t spiffs_probe (spiffs_config * cfg)
References spiffs_t::block_count, spiffs_t::cfg, spiffs_config::hal_read_f, spiffs_config::log_block_size, SPIFFS_CHECK_RES, SPIFFS_ERR_PROBE_NOT_A_FS, SPIFFS_ERR_PROBE_TOO_FEW_BLOCKS, and SPIFFS_MAGIC_PADDR.