Projekt Ei: HardwareLife/Lcd/ESP32_TFT_library/components/spiffs/spiffs_nucleus.h File Reference
spiffs_nucleus.h File Reference
Classes
struct spiffs_fd
Macros
#define _SPIFFS_ERR_CHECK_FIRST (SPIFFS_ERR_INTERNAL - 1)
#define SPIFFS_ERR_CHECK_OBJ_ID_MISM (SPIFFS_ERR_INTERNAL - 1)
#define SPIFFS_ERR_CHECK_SPIX_MISM (SPIFFS_ERR_INTERNAL - 2)
#define SPIFFS_ERR_CHECK_FLAGS_BAD (SPIFFS_ERR_INTERNAL - 3)
#define _SPIFFS_ERR_CHECK_LAST (SPIFFS_ERR_INTERNAL - 4)
#define SPIFFS_VIS_COUNTINUE (SPIFFS_ERR_INTERNAL - 20)
#define SPIFFS_VIS_COUNTINUE_RELOAD (SPIFFS_ERR_INTERNAL - 21)
#define SPIFFS_VIS_END (SPIFFS_ERR_INTERNAL - 22)
#define SPIFFS_EV_IX_UPD (0)
#define SPIFFS_EV_IX_NEW (1)
#define SPIFFS_EV_IX_DEL (2)
#define SPIFFS_EV_IX_MOV (3)
#define SPIFFS_EV_IX_UPD_HDR (4)
#define SPIFFS_OBJ_ID_IX_FLAG ((spiffs_obj_id)(1<<(8*sizeof(spiffs_obj_id)-1)))
#define SPIFFS_UNDEFINED_LEN (u32_t)(-1)
#define SPIFFS_OBJ_ID_DELETED ((spiffs_obj_id)0)
#define SPIFFS_OBJ_ID_FREE ((spiffs_obj_id)-1)
#define SPIFFS_CONFIG_MAGIC (0x20090315)
#define SPIFFS_CFG_LOG_PAGE_SZ(fs) ((fs)->cfg.log_page_size)
#define SPIFFS_CFG_LOG_BLOCK_SZ(fs) ((fs)->cfg.log_block_size)
#define SPIFFS_CFG_PHYS_SZ(fs) ((fs)->cfg.phys_size)
#define SPIFFS_CFG_PHYS_ERASE_SZ(fs) ((fs)->cfg.phys_erase_block)
#define SPIFFS_CFG_PHYS_ADDR(fs) ((fs)->cfg.phys_addr)
#define SPIFFS_MAX_PAGES(fs) (SPIFFS_CFG_PHYS_SZ(fs)/SPIFFS_CFG_LOG_PAGE_SZ(fs))
#define SPIFFS_PAGES_PER_BLOCK(fs) (SPIFFS_CFG_LOG_BLOCK_SZ(fs)/SPIFFS_CFG_LOG_PAGE_SZ(fs))
#define SPIFFS_OBJ_LOOKUP_PAGES(fs) (MAX(1, (SPIFFS_PAGES_PER_BLOCK(fs) * sizeof(spiffs_obj_id)) / SPIFFS_CFG_LOG_PAGE_SZ(fs)))
#define SPIFFS_IS_LOOKUP_PAGE(fs, pix) (((pix) % SPIFFS_PAGES_PER_BLOCK(fs)) < SPIFFS_OBJ_LOOKUP_PAGES(fs))
#define SPIFFS_OBJ_LOOKUP_MAX_ENTRIES(fs) (SPIFFS_PAGES_PER_BLOCK(fs)-SPIFFS_OBJ_LOOKUP_PAGES(fs))
#define SPIFFS_BLOCK_TO_PADDR(fs, block) (SPIFFS_CFG_PHYS_ADDR(fs) + (block)* SPIFFS_CFG_LOG_BLOCK_SZ(fs))
#define SPIFFS_OBJ_LOOKUP_ENTRY_TO_PIX(fs, block, entry) ((block)*SPIFFS_PAGES_PER_BLOCK(fs) + (SPIFFS_OBJ_LOOKUP_PAGES(fs) + entry))
#define SPIFFS_OBJ_LOOKUP_ENTRY_TO_PADDR(fs, block, entry) (SPIFFS_BLOCK_TO_PADDR(fs, block) + (SPIFFS_OBJ_LOOKUP_PAGES(fs) + entry) * SPIFFS_CFG_LOG_PAGE_SZ(fs))
#define SPIFFS_PAGE_TO_PADDR(fs, page) (SPIFFS_CFG_PHYS_ADDR(fs) + (page) * SPIFFS_CFG_LOG_PAGE_SZ(fs))
#define SPIFFS_PADDR_TO_PAGE(fs, addr) (((addr) - SPIFFS_CFG_PHYS_ADDR(fs)) / SPIFFS_CFG_LOG_PAGE_SZ(fs))
#define SPIFFS_PADDR_TO_PAGE_OFFSET(fs, addr) (((addr) - SPIFFS_CFG_PHYS_ADDR(fs)) % SPIFFS_CFG_LOG_PAGE_SZ(fs))
#define SPIFFS_BLOCK_FOR_PAGE(fs, page) ((page) / SPIFFS_PAGES_PER_BLOCK(fs))
#define SPIFFS_PAGE_FOR_BLOCK(fs, block) ((block) * SPIFFS_PAGES_PER_BLOCK(fs))
#define SPIFFS_OBJ_LOOKUP_ENTRY_FOR_PAGE(fs, page) ((page) % SPIFFS_PAGES_PER_BLOCK(fs) - SPIFFS_OBJ_LOOKUP_PAGES(fs))
#define SPIFFS_DATA_PAGE_SIZE(fs) (SPIFFS_CFG_LOG_PAGE_SZ(fs) - sizeof(spiffs_page_header))
#define SPIFFS_ERASE_COUNT_PADDR(fs, bix) (SPIFFS_BLOCK_TO_PADDR(fs, bix) + SPIFFS_OBJ_LOOKUP_PAGES(fs) * SPIFFS_CFG_LOG_PAGE_SZ(fs) - sizeof(spiffs_obj_id))
#define SPIFFS_MAGIC_PADDR(fs, bix) (SPIFFS_BLOCK_TO_PADDR(fs, bix) + SPIFFS_OBJ_LOOKUP_PAGES(fs) * SPIFFS_CFG_LOG_PAGE_SZ(fs) - sizeof(spiffs_obj_id)*2)
#define SPIFFS_CHECK_MAGIC_POSSIBLE(fs)
#define SPIFFS_OBJ_HDR_IX_LEN(fs) ((SPIFFS_CFG_LOG_PAGE_SZ(fs) - sizeof(spiffs_page_object_ix_header))/sizeof(spiffs_page_ix))
#define SPIFFS_OBJ_IX_LEN(fs) ((SPIFFS_CFG_LOG_PAGE_SZ(fs) - sizeof(spiffs_page_object_ix))/sizeof(spiffs_page_ix))
#define SPIFFS_OBJ_IX_ENTRY(fs, spix) ((spix) < SPIFFS_OBJ_HDR_IX_LEN(fs) ? (spix) : (((spix)-SPIFFS_OBJ_HDR_IX_LEN(fs))%SPIFFS_OBJ_IX_LEN(fs)))
#define SPIFFS_OBJ_IX_ENTRY_SPAN_IX(fs, spix) ((spix) < SPIFFS_OBJ_HDR_IX_LEN(fs) ? 0 : (1+((spix)-SPIFFS_OBJ_HDR_IX_LEN(fs))/SPIFFS_OBJ_IX_LEN(fs)))
#define SPIFFS_DATA_SPAN_IX_FOR_OBJ_IX_SPAN_IX(fs, spix) ((spix) == 0 ? 0 : (SPIFFS_OBJ_HDR_IX_LEN(fs) + (((spix)-1) * SPIFFS_OBJ_IX_LEN(fs))))
#define SPIFFS_OP_T_OBJ_LU (0<<0)
#define SPIFFS_OP_T_OBJ_LU2 (1<<0)
#define SPIFFS_OP_T_OBJ_IX (2<<0)
#define SPIFFS_OP_T_OBJ_DA (3<<0)
#define SPIFFS_OP_C_DELE (0<<2)
#define SPIFFS_OP_C_UPDT (1<<2)
#define SPIFFS_OP_C_MOVS (2<<2)
#define SPIFFS_OP_C_MOVD (3<<2)
#define SPIFFS_OP_C_FLSH (4<<2)
#define SPIFFS_OP_C_READ (5<<2)
#define SPIFFS_OP_C_WRTHRU (6<<2)
#define SPIFFS_OP_TYPE_MASK (3<<0)
#define SPIFFS_OP_COM_MASK (7<<2)
#define SPIFFS_PH_FLAG_USED (1<<0)
#define SPIFFS_PH_FLAG_FINAL (1<<1)
#define SPIFFS_PH_FLAG_INDEX (1<<2)
#define SPIFFS_PH_FLAG_DELET (1<<7)
#define SPIFFS_PH_FLAG_IXDELE (1<<6)
#define SPIFFS_CHECK_MOUNT(fs) ((fs)->mounted != 0)
#define SPIFFS_CHECK_CFG(fs) ((fs)->config_magic == SPIFFS_CONFIG_MAGIC)
#define SPIFFS_CHECK_RES(res)
#define SPIFFS_API_CHECK_MOUNT(fs)
#define SPIFFS_API_CHECK_CFG(fs)
#define SPIFFS_API_CHECK_RES(fs, res)
#define SPIFFS_API_CHECK_RES_UNLOCK(fs, res)
#define SPIFFS_VALIDATE_OBJIX(ph, objid, spix)
#define SPIFFS_VALIDATE_DATA(ph, objid, spix)
#define SPIFFS_VIS_CHECK_ID (1<<0)
#define SPIFFS_VIS_CHECK_PH (1<<1)
#define SPIFFS_VIS_NO_WRAP (1<<2)
#define SPIFFS_HAL_WRITE(_fs, _paddr, _len, _src) (_fs)->cfg.hal_write_f((_paddr), (_len), (_src))
#define SPIFFS_HAL_READ(_fs, _paddr, _len, _dst) (_fs)->cfg.hal_read_f((_paddr), (_len), (_dst))
#define SPIFFS_HAL_ERASE(_fs, _paddr, _len) (_fs)->cfg.hal_erase_f((_paddr), (_len))
#define _spiffs_rd(fs, op, fh, addr, len, dst) spiffs_phys_rd((fs), (addr), (len), (dst))
#define _spiffs_wr(fs, op, fh, addr, len, src) spiffs_phys_wr((fs), (addr), (len), (src))
#define MIN(a, b) ((a) < (b) ? (a) : (b))
#define MAX(a, b) ((a) > (b) ? (a) : (b))
Typedefs
typedef s32_t(* spiffs_visitor_f) (spiffs *fs, spiffs_obj_id id, spiffs_block_ix bix, int ix_entry, const void *user_const_p, void *user_var_p)
Functions
struct __attribute ((packed))
s32_t spiffs_phys_rd (spiffs *fs, u32_t addr, u32_t len, u8_t *dst)
s32_t spiffs_phys_wr (spiffs *fs, u32_t addr, u32_t len, u8_t *src)
s32_t spiffs_phys_cpy (spiffs *fs, spiffs_file fh, u32_t dst, u32_t src, u32_t len)
s32_t spiffs_phys_count_free_blocks (spiffs *fs)
s32_t spiffs_obj_lu_find_entry_visitor (spiffs *fs, spiffs_block_ix starting_block, int starting_lu_entry, u8_t flags, spiffs_obj_id obj_id, spiffs_visitor_f v, const void *user_const_p, void *user_var_p, spiffs_block_ix *block_ix, int *lu_entry)
s32_t spiffs_erase_block (spiffs *fs, spiffs_block_ix bix)
s32_t spiffs_obj_lu_scan (spiffs *fs)
s32_t spiffs_obj_lu_find_free_obj_id (spiffs *fs, spiffs_obj_id *obj_id, const u8_t *conflicting_name)
s32_t spiffs_obj_lu_find_free (spiffs *fs, spiffs_block_ix starting_block, int starting_lu_entry, spiffs_block_ix *block_ix, int *lu_entry)
s32_t spiffs_obj_lu_find_id (spiffs *fs, spiffs_block_ix starting_block, int starting_lu_entry, spiffs_obj_id obj_id, spiffs_block_ix *block_ix, int *lu_entry)
s32_t spiffs_obj_lu_find_id_and_span (spiffs *fs, spiffs_obj_id obj_id, spiffs_span_ix spix, spiffs_page_ix exclusion_pix, spiffs_page_ix *pix)
s32_t spiffs_obj_lu_find_id_and_span_by_phdr (spiffs *fs, spiffs_obj_id obj_id, spiffs_span_ix spix, spiffs_page_ix exclusion_pix, spiffs_page_ix *pix)
s32_t spiffs_page_allocate_data (spiffs *fs, spiffs_obj_id obj_id, spiffs_page_header *ph, u8_t *data, u32_t len, u32_t page_offs, u8_t finalize, spiffs_page_ix *pix)
s32_t spiffs_page_move (spiffs *fs, spiffs_file fh, u8_t *page_data, spiffs_obj_id obj_id, spiffs_page_header *page_hdr, spiffs_page_ix src_pix, spiffs_page_ix *dst_pix)
s32_t spiffs_page_delete (spiffs *fs, spiffs_page_ix pix)
s32_t spiffs_object_create (spiffs *fs, spiffs_obj_id obj_id, const u8_t name[], const u8_t meta[], spiffs_obj_type type, spiffs_page_ix *objix_hdr_pix)
s32_t spiffs_object_update_index_hdr (spiffs *fs, spiffs_fd *fd, spiffs_obj_id obj_id, spiffs_page_ix objix_hdr_pix, u8_t *new_objix_hdr_data, const u8_t name[], const u8_t meta[], u32_t size, spiffs_page_ix *new_pix)
void spiffs_cb_object_event (spiffs *fs, spiffs_page_object_ix *objix, int ev, spiffs_obj_id obj_id, spiffs_span_ix spix, spiffs_page_ix new_pix, u32_t new_size)
s32_t spiffs_object_open_by_id (spiffs *fs, spiffs_obj_id obj_id, spiffs_fd *f, spiffs_flags flags, spiffs_mode mode)
s32_t spiffs_object_open_by_page (spiffs *fs, spiffs_page_ix pix, spiffs_fd *f, spiffs_flags flags, spiffs_mode mode)
s32_t spiffs_object_append (spiffs_fd *fd, u32_t offset, u8_t *data, u32_t len)
s32_t spiffs_object_modify (spiffs_fd *fd, u32_t offset, u8_t *data, u32_t len)
s32_t spiffs_object_read (spiffs_fd *fd, u32_t offset, u32_t len, u8_t *dst)
s32_t spiffs_object_truncate (spiffs_fd *fd, u32_t new_len, u8_t remove_object)
s32_t spiffs_object_find_object_index_header_by_name (spiffs *fs, const u8_t name[SPIFFS_OBJ_NAME_LEN], spiffs_page_ix *pix)
s32_t spiffs_gc_check (spiffs *fs, u32_t len)
s32_t spiffs_gc_erase_page_stats (spiffs *fs, spiffs_block_ix bix)
s32_t spiffs_gc_find_candidate (spiffs *fs, spiffs_block_ix **block_candidate, int *candidate_count, char fs_crammed)
s32_t spiffs_gc_clean (spiffs *fs, spiffs_block_ix bix)
s32_t spiffs_gc_quick (spiffs *fs, u16_t max_free_pages)
s32_t spiffs_fd_find_new (spiffs *fs, spiffs_fd **fd, const char *name)
s32_t spiffs_fd_return (spiffs *fs, spiffs_file f)
s32_t spiffs_fd_get (spiffs *fs, spiffs_file f, spiffs_fd **fd)
s32_t spiffs_lookup_consistency_check (spiffs *fs, u8_t check_all_objects)
s32_t spiffs_page_consistency_check (spiffs *fs)
s32_t spiffs_object_index_consistency_check (spiffs *fs)
Variables
spiffs_page_header
spiffs_page_object_ix_header
spiffs_page_object_ix
Class Documentation
spiffs_fd
struct spiffs_fd
Class Members
spiffs_page_ix cursor_objix_pix
spiffs_span_ix cursor_objix_spix
u32_t fdoffset
spiffs_file file_nbr
spiffs_flags flags
spiffs * fs
spiffs_obj_id obj_id
spiffs_page_ix objix_hdr_pix
u32_t offset
u32_t size
Macro Definition Documentation
_SPIFFS_ERR_CHECK_FIRST
#define _SPIFFS_ERR_CHECK_FIRST (SPIFFS_ERR_INTERNAL - 1)
_SPIFFS_ERR_CHECK_LAST
#define _SPIFFS_ERR_CHECK_LAST (SPIFFS_ERR_INTERNAL - 4)
_spiffs_rd
#define _spiffs_rd (fs, op, fh, addr, len, dst) spiffs_phys_rd((fs), (addr), (len), (dst))
_spiffs_wr
#define _spiffs_wr (fs, op, fh, addr, len, src) spiffs_phys_wr((fs), (addr), (len), (src))
MAX
#define MAX (a, b) ((a) > (b) ? (a) : (b))
MIN
#define MIN (a, b) ((a) < (b) ? (a) : (b))
SPIFFS_API_CHECK_CFG
#define SPIFFS_API_CHECK_CFG (fs)
Value:
if (!SPIFFS_CHECK_CFG((fs))) { \
    (fs)->err_code = SPIFFS_ERR_NOT_CONFIGURED; \
    return SPIFFS_ERR_NOT_CONFIGURED; \
  }
SPIFFS_API_CHECK_MOUNT
#define SPIFFS_API_CHECK_MOUNT (fs)
Value:
if (!SPIFFS_CHECK_MOUNT((fs))) { \
    (fs)->err_code = SPIFFS_ERR_NOT_MOUNTED; \
    return SPIFFS_ERR_NOT_MOUNTED; \
  }
SPIFFS_API_CHECK_RES
#define SPIFFS_API_CHECK_RES (fs, res)
Value:
if ((res) < SPIFFS_OK) { \
    (fs)->err_code = (res); \
    return (res); \
  }
SPIFFS_API_CHECK_RES_UNLOCK
#define SPIFFS_API_CHECK_RES_UNLOCK (fs, res)
Value:
if ((res) < SPIFFS_OK) { \
    (fs)->err_code = (res); \
    SPIFFS_UNLOCK(fs); \
    return (res); \
  }
SPIFFS_BLOCK_FOR_PAGE
#define SPIFFS_BLOCK_FOR_PAGE (fs, page) ((page) / SPIFFS_PAGES_PER_BLOCK(fs))
SPIFFS_BLOCK_TO_PADDR
#define SPIFFS_BLOCK_TO_PADDR (fs, block) (SPIFFS_CFG_PHYS_ADDR(fs) + (block)* SPIFFS_CFG_LOG_BLOCK_SZ(fs))
SPIFFS_CFG_LOG_BLOCK_SZ
#define SPIFFS_CFG_LOG_BLOCK_SZ (fs) ((fs)->cfg.log_block_size)
SPIFFS_CFG_LOG_PAGE_SZ
#define SPIFFS_CFG_LOG_PAGE_SZ (fs) ((fs)->cfg.log_page_size)
SPIFFS_CFG_PHYS_ADDR
#define SPIFFS_CFG_PHYS_ADDR (fs) ((fs)->cfg.phys_addr)
SPIFFS_CFG_PHYS_ERASE_SZ
#define SPIFFS_CFG_PHYS_ERASE_SZ (fs) ((fs)->cfg.phys_erase_block)
SPIFFS_CFG_PHYS_SZ
#define SPIFFS_CFG_PHYS_SZ (fs) ((fs)->cfg.phys_size)
SPIFFS_CHECK_CFG
#define SPIFFS_CHECK_CFG (fs) ((fs)->config_magic == SPIFFS_CONFIG_MAGIC)
SPIFFS_CHECK_MAGIC_POSSIBLE
#define SPIFFS_CHECK_MAGIC_POSSIBLE (fs)
Value:
((SPIFFS_OBJ_LOOKUP_MAX_ENTRIES(fs) % (SPIFFS_CFG_LOG_PAGE_SZ(fs)/sizeof(spiffs_obj_id))) * sizeof(spiffs_obj_id) \
    <= (SPIFFS_CFG_LOG_PAGE_SZ(fs)-sizeof(spiffs_obj_id)*2) )
SPIFFS_CHECK_MOUNT
#define SPIFFS_CHECK_MOUNT (fs) ((fs)->mounted != 0)
SPIFFS_CHECK_RES
#define SPIFFS_CHECK_RES (res)
Value:
do { \
    if ((res) < SPIFFS_OK) return (res); \
  } while (0);
SPIFFS_CONFIG_MAGIC
#define SPIFFS_CONFIG_MAGIC (0x20090315)
SPIFFS_DATA_PAGE_SIZE
#define SPIFFS_DATA_PAGE_SIZE (fs) (SPIFFS_CFG_LOG_PAGE_SZ(fs) - sizeof(spiffs_page_header))
SPIFFS_DATA_SPAN_IX_FOR_OBJ_IX_SPAN_IX
#define SPIFFS_DATA_SPAN_IX_FOR_OBJ_IX_SPAN_IX (fs, spix) ((spix) == 0 ? 0 : (SPIFFS_OBJ_HDR_IX_LEN(fs) + (((spix)-1) * SPIFFS_OBJ_IX_LEN(fs))))
SPIFFS_ERASE_COUNT_PADDR
#define SPIFFS_ERASE_COUNT_PADDR (fs, bix) (SPIFFS_BLOCK_TO_PADDR(fs, bix) + SPIFFS_OBJ_LOOKUP_PAGES(fs) * SPIFFS_CFG_LOG_PAGE_SZ(fs) - sizeof(spiffs_obj_id))
SPIFFS_ERR_CHECK_FLAGS_BAD
#define SPIFFS_ERR_CHECK_FLAGS_BAD (SPIFFS_ERR_INTERNAL - 3)
SPIFFS_ERR_CHECK_OBJ_ID_MISM
#define SPIFFS_ERR_CHECK_OBJ_ID_MISM (SPIFFS_ERR_INTERNAL - 1)
SPIFFS_ERR_CHECK_SPIX_MISM
#define SPIFFS_ERR_CHECK_SPIX_MISM (SPIFFS_ERR_INTERNAL - 2)
SPIFFS_EV_IX_DEL
#define SPIFFS_EV_IX_DEL (2)
SPIFFS_EV_IX_MOV
#define SPIFFS_EV_IX_MOV (3)
SPIFFS_EV_IX_NEW
#define SPIFFS_EV_IX_NEW (1)
SPIFFS_EV_IX_UPD
#define SPIFFS_EV_IX_UPD (0)
SPIFFS_EV_IX_UPD_HDR
#define SPIFFS_EV_IX_UPD_HDR (4)
SPIFFS_HAL_ERASE
#define SPIFFS_HAL_ERASE (_fs, _paddr, _len) (_fs)->cfg.hal_erase_f((_paddr), (_len))
SPIFFS_HAL_READ
#define SPIFFS_HAL_READ (_fs, _paddr, _len, _dst) (_fs)->cfg.hal_read_f((_paddr), (_len), (_dst))
SPIFFS_HAL_WRITE
#define SPIFFS_HAL_WRITE (_fs, _paddr, _len, _src) (_fs)->cfg.hal_write_f((_paddr), (_len), (_src))
SPIFFS_IS_LOOKUP_PAGE
#define SPIFFS_IS_LOOKUP_PAGE (fs, pix) (((pix) % SPIFFS_PAGES_PER_BLOCK(fs)) < SPIFFS_OBJ_LOOKUP_PAGES(fs))
SPIFFS_MAGIC_PADDR
#define SPIFFS_MAGIC_PADDR (fs, bix) (SPIFFS_BLOCK_TO_PADDR(fs, bix) + SPIFFS_OBJ_LOOKUP_PAGES(fs) * SPIFFS_CFG_LOG_PAGE_SZ(fs) - sizeof(spiffs_obj_id)*2)
SPIFFS_MAX_PAGES
#define SPIFFS_MAX_PAGES (fs) (SPIFFS_CFG_PHYS_SZ(fs)/SPIFFS_CFG_LOG_PAGE_SZ(fs))
SPIFFS_OBJ_HDR_IX_LEN
#define SPIFFS_OBJ_HDR_IX_LEN (fs) ((SPIFFS_CFG_LOG_PAGE_SZ(fs) - sizeof(spiffs_page_object_ix_header))/sizeof(spiffs_page_ix))
SPIFFS_OBJ_ID_DELETED
#define SPIFFS_OBJ_ID_DELETED ((spiffs_obj_id)0)
SPIFFS_OBJ_ID_FREE
#define SPIFFS_OBJ_ID_FREE ((spiffs_obj_id)-1)
SPIFFS_OBJ_ID_IX_FLAG
#define SPIFFS_OBJ_ID_IX_FLAG ((spiffs_obj_id)(1<<(8*sizeof(spiffs_obj_id)-1)))
SPIFFS_OBJ_IX_ENTRY
#define SPIFFS_OBJ_IX_ENTRY (fs, spix) ((spix) < SPIFFS_OBJ_HDR_IX_LEN(fs) ? (spix) : (((spix)-SPIFFS_OBJ_HDR_IX_LEN(fs))%SPIFFS_OBJ_IX_LEN(fs)))
SPIFFS_OBJ_IX_ENTRY_SPAN_IX
#define SPIFFS_OBJ_IX_ENTRY_SPAN_IX (fs, spix) ((spix) < SPIFFS_OBJ_HDR_IX_LEN(fs) ? 0 : (1+((spix)-SPIFFS_OBJ_HDR_IX_LEN(fs))/SPIFFS_OBJ_IX_LEN(fs)))
SPIFFS_OBJ_IX_LEN
#define SPIFFS_OBJ_IX_LEN (fs) ((SPIFFS_CFG_LOG_PAGE_SZ(fs) - sizeof(spiffs_page_object_ix))/sizeof(spiffs_page_ix))
SPIFFS_OBJ_LOOKUP_ENTRY_FOR_PAGE
#define SPIFFS_OBJ_LOOKUP_ENTRY_FOR_PAGE (fs, page) ((page) % SPIFFS_PAGES_PER_BLOCK(fs) - SPIFFS_OBJ_LOOKUP_PAGES(fs))
SPIFFS_OBJ_LOOKUP_ENTRY_TO_PADDR
#define SPIFFS_OBJ_LOOKUP_ENTRY_TO_PADDR (fs, block, entry) (SPIFFS_BLOCK_TO_PADDR(fs, block) + (SPIFFS_OBJ_LOOKUP_PAGES(fs) + entry) * SPIFFS_CFG_LOG_PAGE_SZ(fs))
SPIFFS_OBJ_LOOKUP_ENTRY_TO_PIX
#define SPIFFS_OBJ_LOOKUP_ENTRY_TO_PIX (fs, block, entry) ((block)*SPIFFS_PAGES_PER_BLOCK(fs) + (SPIFFS_OBJ_LOOKUP_PAGES(fs) + entry))
SPIFFS_OBJ_LOOKUP_MAX_ENTRIES
#define SPIFFS_OBJ_LOOKUP_MAX_ENTRIES (fs) (SPIFFS_PAGES_PER_BLOCK(fs)-SPIFFS_OBJ_LOOKUP_PAGES(fs))
SPIFFS_OBJ_LOOKUP_PAGES
#define SPIFFS_OBJ_LOOKUP_PAGES (fs) (MAX(1, (SPIFFS_PAGES_PER_BLOCK(fs) * sizeof(spiffs_obj_id)) / SPIFFS_CFG_LOG_PAGE_SZ(fs)))
SPIFFS_OP_C_DELE
#define SPIFFS_OP_C_DELE (0<<2)
SPIFFS_OP_C_FLSH
#define SPIFFS_OP_C_FLSH (4<<2)
SPIFFS_OP_C_MOVD
#define SPIFFS_OP_C_MOVD (3<<2)
SPIFFS_OP_C_MOVS
#define SPIFFS_OP_C_MOVS (2<<2)
SPIFFS_OP_C_READ
#define SPIFFS_OP_C_READ (5<<2)
SPIFFS_OP_C_UPDT
#define SPIFFS_OP_C_UPDT (1<<2)
SPIFFS_OP_C_WRTHRU
#define SPIFFS_OP_C_WRTHRU (6<<2)
SPIFFS_OP_COM_MASK
#define SPIFFS_OP_COM_MASK (7<<2)
SPIFFS_OP_T_OBJ_DA
#define SPIFFS_OP_T_OBJ_DA (3<<0)
SPIFFS_OP_T_OBJ_IX
#define SPIFFS_OP_T_OBJ_IX (2<<0)
SPIFFS_OP_T_OBJ_LU
#define SPIFFS_OP_T_OBJ_LU (0<<0)
SPIFFS_OP_T_OBJ_LU2
#define SPIFFS_OP_T_OBJ_LU2 (1<<0)
SPIFFS_OP_TYPE_MASK
#define SPIFFS_OP_TYPE_MASK (3<<0)
SPIFFS_PADDR_TO_PAGE
#define SPIFFS_PADDR_TO_PAGE (fs, addr) (((addr) - SPIFFS_CFG_PHYS_ADDR(fs)) / SPIFFS_CFG_LOG_PAGE_SZ(fs))
SPIFFS_PADDR_TO_PAGE_OFFSET
#define SPIFFS_PADDR_TO_PAGE_OFFSET (fs, addr) (((addr) - SPIFFS_CFG_PHYS_ADDR(fs)) % SPIFFS_CFG_LOG_PAGE_SZ(fs))
SPIFFS_PAGE_FOR_BLOCK
#define SPIFFS_PAGE_FOR_BLOCK (fs, block) ((block) * SPIFFS_PAGES_PER_BLOCK(fs))
SPIFFS_PAGE_TO_PADDR
#define SPIFFS_PAGE_TO_PADDR (fs, page) (SPIFFS_CFG_PHYS_ADDR(fs) + (page) * SPIFFS_CFG_LOG_PAGE_SZ(fs))
SPIFFS_PAGES_PER_BLOCK
#define SPIFFS_PAGES_PER_BLOCK (fs) (SPIFFS_CFG_LOG_BLOCK_SZ(fs)/SPIFFS_CFG_LOG_PAGE_SZ(fs))
SPIFFS_PH_FLAG_DELET
#define SPIFFS_PH_FLAG_DELET (1<<7)
SPIFFS_PH_FLAG_FINAL
#define SPIFFS_PH_FLAG_FINAL (1<<1)
SPIFFS_PH_FLAG_INDEX
#define SPIFFS_PH_FLAG_INDEX (1<<2)
SPIFFS_PH_FLAG_IXDELE
#define SPIFFS_PH_FLAG_IXDELE (1<<6)
SPIFFS_PH_FLAG_USED
#define SPIFFS_PH_FLAG_USED (1<<0)
SPIFFS_UNDEFINED_LEN
#define SPIFFS_UNDEFINED_LEN (u32_t)(-1)
SPIFFS_VALIDATE_DATA
#define SPIFFS_VALIDATE_DATA (ph, objid, spix)
Value:
if (((ph).flags & SPIFFS_PH_FLAG_USED) != 0) return SPIFFS_ERR_IS_FREE; \
    if (((ph).flags & SPIFFS_PH_FLAG_DELET) == 0) return SPIFFS_ERR_DELETED; \
    if (((ph).flags & SPIFFS_PH_FLAG_FINAL) != 0) return SPIFFS_ERR_NOT_FINALIZED; \
    if (((ph).flags & SPIFFS_PH_FLAG_INDEX) == 0) return SPIFFS_ERR_IS_INDEX; \
    if ((objid) & SPIFFS_OBJ_ID_IX_FLAG) return SPIFFS_ERR_IS_INDEX; \
    if ((ph).span_ix != (spix)) return SPIFFS_ERR_DATA_SPAN_MISMATCH;
SPIFFS_VALIDATE_OBJIX
#define SPIFFS_VALIDATE_OBJIX (ph, objid, spix)
Value:
if (((ph).flags & SPIFFS_PH_FLAG_USED) != 0) return SPIFFS_ERR_IS_FREE; \
    if (((ph).flags & SPIFFS_PH_FLAG_DELET) == 0) return SPIFFS_ERR_DELETED; \
    if (((ph).flags & SPIFFS_PH_FLAG_FINAL) != 0) return SPIFFS_ERR_NOT_FINALIZED; \
    if (((ph).flags & SPIFFS_PH_FLAG_INDEX) != 0) return SPIFFS_ERR_NOT_INDEX; \
    if (((objid) & SPIFFS_OBJ_ID_IX_FLAG) == 0) return SPIFFS_ERR_NOT_INDEX; \
    if ((ph).span_ix != (spix)) return SPIFFS_ERR_INDEX_SPAN_MISMATCH;
SPIFFS_VIS_CHECK_ID
#define SPIFFS_VIS_CHECK_ID (1<<0)
SPIFFS_VIS_CHECK_PH
#define SPIFFS_VIS_CHECK_PH (1<<1)
SPIFFS_VIS_COUNTINUE
#define SPIFFS_VIS_COUNTINUE (SPIFFS_ERR_INTERNAL - 20)
SPIFFS_VIS_COUNTINUE_RELOAD
#define SPIFFS_VIS_COUNTINUE_RELOAD (SPIFFS_ERR_INTERNAL - 21)
SPIFFS_VIS_END
#define SPIFFS_VIS_END (SPIFFS_ERR_INTERNAL - 22)
SPIFFS_VIS_NO_WRAP
#define SPIFFS_VIS_NO_WRAP (1<<2)
Typedef Documentation
spiffs_visitor_f
typedef s32_t(* spiffs_visitor_f) (spiffs *fs, spiffs_obj_id id, spiffs_block_ix bix, int ix_entry, const void *user_const_p, void *user_var_p)
Function Documentation
__attribute()
struct __attribute ((packed))
spiffs_cb_object_event()
void spiffs_cb_object_event (spiffs * fs, spiffs_page_object_ix * objix, int ev, spiffs_obj_id obj_id, spiffs_span_ix spix, spiffs_page_ix new_pix, u32_t new_size)
References _SPIPRIfd, _SPIPRIi, _SPIPRIid, _SPIPRIpg, _SPIPRIsp, spiffs_fd::cursor_objix_pix, spiffs_fd::cursor_objix_spix, spiffs_t::fd_count, spiffs_t::fd_space, spiffs_fd::file_nbr, spiffs_dirent::obj_id, spiffs_fd::obj_id, spiffs_fd::objix_hdr_pix, spiffs_fd::size, SPIFFS_DBG, SPIFFS_EV_IX_DEL, SPIFFS_EV_IX_NEW, SPIFFS_EV_IX_UPD, SPIFFS_OBJ_ID_DELETED, and SPIFFS_OBJ_ID_IX_FLAG.
Referenced by spiffs_gc_clean(), spiffs_object_create(), and spiffs_object_update_index_hdr().
spiffs_erase_block()
s32_t spiffs_erase_block (spiffs * fs, spiffs_block_ix bix)
References _spiffs_wr, _SPIPRIad, _SPIPRIi, spiffs_t::free_blocks, spiffs_t::max_erase_count, spiffs_dirent::size, SPIFFS_BLOCK_TO_PADDR, SPIFFS_CFG_LOG_BLOCK_SZ, SPIFFS_CFG_PHYS_ERASE_SZ, SPIFFS_CHECK_RES, SPIFFS_DBG, SPIFFS_ERASE_COUNT_PADDR, SPIFFS_HAL_ERASE, SPIFFS_MAGIC_PADDR, SPIFFS_OBJ_ID_IX_FLAG, SPIFFS_OP_C_WRTHRU, and SPIFFS_OP_T_OBJ_LU2.
Referenced by SPIFFS_format(), and spiffs_obj_lu_scan().
spiffs_fd_find_new()
s32_t spiffs_fd_find_new (spiffs * fs, spiffs_fd ** fd, const char * name)
Referenced by SPIFFS_open(), SPIFFS_open_by_dirent(), SPIFFS_open_by_page(), SPIFFS_remove(), SPIFFS_rename(), and SPIFFS_update_meta().
spiffs_fd_get()
s32_t spiffs_fd_get (spiffs * fs, spiffs_file f, spiffs_fd ** fd)
References spiffs_t::fd_count, spiffs_t::fd_space, SPIFFS_ERR_BAD_DESCRIPTOR, SPIFFS_ERR_FILE_CLOSED, and SPIFFS_OK.
Referenced by SPIFFS_eof(), SPIFFS_fremove(), SPIFFS_fstat(), SPIFFS_fupdate_meta(), SPIFFS_ix_map(), SPIFFS_ix_remap(), SPIFFS_ix_unmap(), SPIFFS_lseek(), SPIFFS_tell(), and SPIFFS_write().
spiffs_fd_return()
s32_t spiffs_fd_return (spiffs * fs, spiffs_file f)
References spiffs_t::fd_count, spiffs_t::fd_space, spiffs_fd::file_nbr, SPIFFS_ERR_BAD_DESCRIPTOR, SPIFFS_ERR_FILE_CLOSED, and SPIFFS_OK.
Referenced by SPIFFS_open(), SPIFFS_open_by_dirent(), SPIFFS_open_by_page(), SPIFFS_remove(), SPIFFS_rename(), and SPIFFS_update_meta().
spiffs_gc_check()
s32_t spiffs_gc_check (spiffs * fs, u32_t len)
References _SPIPRIi, spiffs_t::block_count, spiffs_t::cleaning, spiffs_t::free_blocks, SPIFFS_CHECK_RES, SPIFFS_DATA_PAGE_SIZE, SPIFFS_ERR_FULL, spiffs_gc_clean(), SPIFFS_GC_DBG, spiffs_gc_erase_page_stats(), spiffs_gc_find_candidate(), SPIFFS_OBJ_LOOKUP_PAGES, SPIFFS_OK, SPIFFS_PAGES_PER_BLOCK, spiffs_t::stats_p_allocated, and spiffs_t::stats_p_deleted.
Referenced by SPIFFS_gc(), spiffs_object_append(), spiffs_object_create(), spiffs_object_modify(), and spiffs_object_truncate().
spiffs_gc_clean()
s32_t spiffs_gc_clean (spiffs * fs, spiffs_block_ix bix)
References _spiffs_rd, _SPIPRIbl, _SPIPRIi, _SPIPRIid, _SPIPRIpg, _SPIPRIsp, spiffs_t::block_count, FIND_OBJ_DATA, FINISHED, spiffs_t::free_cursor_block_ix, spiffs_t::free_cursor_obj_lu_entry, spiffs_t::lu_work, MOVE_OBJ_DATA, MOVE_OBJ_IX, spiffs_dirent::obj_id, spiffs_cb_object_event(), SPIFFS_CFG_LOG_BLOCK_SZ, SPIFFS_CFG_LOG_PAGE_SZ, SPIFFS_CHECK_RES, SPIFFS_ERR_NOT_FOUND, SPIFFS_EV_IX_DEL, SPIFFS_EV_IX_MOV, SPIFFS_EV_IX_UPD, SPIFFS_GC_DBG, SPIFFS_OBJ_ID_DELETED, SPIFFS_OBJ_ID_FREE, SPIFFS_OBJ_ID_IX_FLAG, SPIFFS_OBJ_IX_ENTRY, SPIFFS_OBJ_IX_ENTRY_SPAN_IX, SPIFFS_OBJ_LOOKUP_ENTRY_TO_PIX, SPIFFS_OBJ_LOOKUP_PAGES, spiffs_obj_lu_find_id_and_span(), spiffs_object_update_index_hdr(), SPIFFS_OK, SPIFFS_OP_C_READ, SPIFFS_OP_T_OBJ_LU, SPIFFS_OP_T_OBJ_LU2, spiffs_page_delete(), spiffs_page_header, spiffs_page_move(), spiffs_page_object_ix, spiffs_page_object_ix_header, SPIFFS_PAGE_TO_PADDR, SPIFFS_PAGES_PER_BLOCK, SPIFFS_PH_FLAG_DELET, SPIFFS_VALIDATE_OBJIX, and spiffs_t::work.
Referenced by spiffs_gc_check().
spiffs_gc_erase_page_stats()
s32_t spiffs_gc_erase_page_stats (spiffs * fs, spiffs_block_ix bix)
References _spiffs_rd, _SPIPRIi, spiffs_t::lu_work, spiffs_dirent::obj_id, SPIFFS_CFG_LOG_BLOCK_SZ, SPIFFS_CFG_LOG_PAGE_SZ, SPIFFS_GC_DBG, SPIFFS_OBJ_ID_DELETED, SPIFFS_OBJ_ID_FREE, SPIFFS_OBJ_LOOKUP_PAGES, SPIFFS_OK, SPIFFS_OP_C_READ, SPIFFS_OP_T_OBJ_LU, SPIFFS_PAGE_TO_PADDR, SPIFFS_PAGES_PER_BLOCK, spiffs_t::stats_p_allocated, and spiffs_t::stats_p_deleted.
Referenced by spiffs_gc_check().
spiffs_gc_find_candidate()
s32_t spiffs_gc_find_candidate (spiffs * fs, spiffs_block_ix ** block_candidate, int * candidate_count, char fs_crammed)
References _spiffs_rd, _SPIPRIbl, _SPIPRIi, spiffs_t::block_count, spiffs_t::lu_work, spiffs_t::max_erase_count, MIN, spiffs_dirent::obj_id, SPIFFS_CFG_LOG_BLOCK_SZ, SPIFFS_CFG_LOG_PAGE_SZ, SPIFFS_CHECK_RES, SPIFFS_ERASE_COUNT_PADDR, SPIFFS_GC_DBG, SPIFFS_GC_HEUR_W_DELET, SPIFFS_GC_HEUR_W_ERASE_AGE, SPIFFS_GC_HEUR_W_USED, SPIFFS_OBJ_ID_DELETED, SPIFFS_OBJ_ID_FREE, SPIFFS_OBJ_LOOKUP_PAGES, SPIFFS_OK, SPIFFS_OP_C_READ, SPIFFS_OP_T_OBJ_LU, SPIFFS_OP_T_OBJ_LU2, SPIFFS_PAGE_TO_PADDR, SPIFFS_PAGES_PER_BLOCK, and spiffs_t::work.
Referenced by spiffs_gc_check().
spiffs_gc_quick()
s32_t spiffs_gc_quick (spiffs * fs, u16_t max_free_pages)
References _spiffs_rd, spiffs_t::block_count, spiffs_t::lu_work, spiffs_dirent::obj_id, SPIFFS_CFG_LOG_PAGE_SZ, SPIFFS_GC_DBG, SPIFFS_OBJ_ID_DELETED, SPIFFS_OBJ_ID_FREE, SPIFFS_OBJ_LOOKUP_PAGES, SPIFFS_OK, SPIFFS_OP_C_READ, SPIFFS_OP_T_OBJ_LU, SPIFFS_PAGE_TO_PADDR, SPIFFS_PAGES_PER_BLOCK, and spiffs_t::stats_p_deleted.
Referenced by SPIFFS_gc_quick(), and spiffs_obj_lu_find_free().
spiffs_lookup_consistency_check()
s32_t spiffs_lookup_consistency_check (spiffs * fs, u8_t check_all_objects)
References CHECK_CB, SPIFFS_CHECK_LOOKUP, SPIFFS_CHECK_PROGRESS, spiffs_obj_lu_find_entry_visitor(), and SPIFFS_OK.
Referenced by SPIFFS_check().
spiffs_obj_lu_find_entry_visitor()
s32_t spiffs_obj_lu_find_entry_visitor (spiffs * fs, spiffs_block_ix starting_block, int starting_lu_entry, u8_t flags, spiffs_obj_id obj_id, spiffs_visitor_f v, const void * user_const_p, void * user_var_p, spiffs_block_ix * block_ix, int * lu_entry)
References _spiffs_rd, spiffs_t::block_count, spiffs_t::lu_work, SPIFFS_CFG_LOG_BLOCK_SZ, SPIFFS_CFG_LOG_PAGE_SZ, SPIFFS_CHECK_RES, SPIFFS_OBJ_LOOKUP_MAX_ENTRIES, SPIFFS_OBJ_LOOKUP_PAGES, SPIFFS_OK, SPIFFS_OP_C_READ, SPIFFS_OP_T_OBJ_LU, SPIFFS_PAGE_TO_PADDR, SPIFFS_VIS_CHECK_ID, SPIFFS_VIS_CHECK_PH, SPIFFS_VIS_COUNTINUE, SPIFFS_VIS_COUNTINUE_RELOAD, SPIFFS_VIS_END, and SPIFFS_VIS_NO_WRAP.
Referenced by spiffs_lookup_consistency_check(), spiffs_obj_lu_find_free_obj_id(), spiffs_obj_lu_find_id(), spiffs_obj_lu_find_id_and_span(), spiffs_obj_lu_find_id_and_span_by_phdr(), spiffs_obj_lu_scan(), spiffs_object_find_object_index_header_by_name(), spiffs_object_index_consistency_check(), spiffs_populate_ix_map(), and SPIFFS_readdir().
spiffs_obj_lu_find_free()
s32_t spiffs_obj_lu_find_free (spiffs * fs, spiffs_block_ix starting_block, int starting_lu_entry, spiffs_block_ix * block_ix, int * lu_entry)
References spiffs_t::cleaning, spiffs_t::free_blocks, spiffs_t::free_cursor_block_ix, spiffs_t::free_cursor_obj_lu_entry, SPIFFS_CHECK_RES, SPIFFS_DBG, SPIFFS_ERR_FULL, SPIFFS_ERR_NO_DELETED_BLOCKS, spiffs_gc_quick(), SPIFFS_OBJ_ID_FREE, spiffs_obj_lu_find_id(), and SPIFFS_OK.
Referenced by spiffs_object_create(), spiffs_page_allocate_data(), and spiffs_page_move().
spiffs_obj_lu_find_free_obj_id()
s32_t spiffs_obj_lu_find_free_obj_id (spiffs * fs, spiffs_obj_id * obj_id, const u8_t * conflicting_name)
References _SPIPRIid, spiffs_t::block_count, spiffs_free_obj_id_state::compaction, spiffs_free_obj_id_state::conflicting_name, spiffs_free_obj_id_state::max_obj_id, spiffs_free_obj_id_state::min_obj_id, SPIFFS_CFG_LOG_PAGE_SZ, SPIFFS_DBG, SPIFFS_OBJ_ID_FREE, SPIFFS_OBJ_ID_IX_FLAG, SPIFFS_OBJ_LOOKUP_MAX_ENTRIES, spiffs_obj_lu_find_entry_visitor(), SPIFFS_OK, and spiffs_t::work.
Referenced by SPIFFS_creat(), and SPIFFS_open().
spiffs_obj_lu_find_id()
s32_t spiffs_obj_lu_find_id (spiffs * fs, spiffs_block_ix starting_block, int starting_lu_entry, spiffs_obj_id obj_id, spiffs_block_ix * block_ix, int * lu_entry)
References SPIFFS_ERR_NOT_FOUND, spiffs_obj_lu_find_entry_visitor(), SPIFFS_VIS_CHECK_ID, and SPIFFS_VIS_END.
Referenced by spiffs_obj_lu_find_free().
spiffs_obj_lu_find_id_and_span()
s32_t spiffs_obj_lu_find_id_and_span (spiffs * fs, spiffs_obj_id obj_id, spiffs_span_ix spix, spiffs_page_ix exclusion_pix, spiffs_page_ix * pix)
References spiffs_t::cursor_block_ix, spiffs_t::cursor_obj_lu_entry, spiffs_obj_lu_find_entry_visitor(), and SPIFFS_VIS_CHECK_ID.
Referenced by spiffs_gc_clean(), spiffs_object_open_by_id(), and spiffs_object_read().
spiffs_obj_lu_find_id_and_span_by_phdr()
s32_t spiffs_obj_lu_find_id_and_span_by_phdr (spiffs * fs, spiffs_obj_id obj_id, spiffs_span_ix spix, spiffs_page_ix exclusion_pix, spiffs_page_ix * pix)
References spiffs_t::cursor_block_ix, spiffs_t::cursor_obj_lu_entry, spiffs_obj_lu_find_entry_visitor(), and SPIFFS_VIS_CHECK_PH.
spiffs_obj_lu_scan()
s32_t spiffs_obj_lu_scan (spiffs * fs)
References _spiffs_rd, _SPIPRIbl, spiffs_t::free_blocks, MAX, spiffs_t::max_erase_count, MIN, SPIFFS_CHECK_RES, SPIFFS_DBG, spiffs_erase_block(), SPIFFS_ERASE_COUNT_PADDR, SPIFFS_ERR_NOT_A_FS, SPIFFS_ERR_RO_ABORTED_OPERATION, SPIFFS_MAGIC_PADDR, SPIFFS_OBJ_ID_FREE, spiffs_obj_lu_find_entry_visitor(), SPIFFS_OP_C_READ, SPIFFS_OP_T_OBJ_LU2, spiffs_t::stats_p_allocated, and spiffs_t::stats_p_deleted.
Referenced by SPIFFS_check(), and SPIFFS_mount().
spiffs_object_append()
s32_t spiffs_object_append (spiffs_fd * fd, u32_t offset, u8_t * data, u32_t len)
References _SPIPRIi, _SPIPRIid, _SPIPRIpg, _SPIPRIsp, spiffs_fd::fs, spiffs_fd::obj_id, spiffs_fd::objix_hdr_pix, spiffs_fd::size, SPIFFS_CHECK_RES, SPIFFS_DATA_PAGE_SIZE, SPIFFS_DBG, spiffs_gc_check(), SPIFFS_OBJ_IX_ENTRY_SPAN_IX, SPIFFS_OK, spiffs_page_header, spiffs_page_object_ix, spiffs_page_object_ix_header, and spiffs_t::work.
spiffs_object_create()
s32_t spiffs_object_create (spiffs * fs, spiffs_obj_id obj_id, const u8_t name[], const u8_t meta[], spiffs_obj_type type, spiffs_page_ix * objix_hdr_pix)
References _spiffs_wr, _SPIPRIbl, _SPIPRIpg, _SPIPRIsp, spiffs_t::free_cursor_block_ix, spiffs_t::free_cursor_obj_lu_entry, spiffs_dirent::obj_id, SPIFFS_BLOCK_TO_PADDR, spiffs_cb_object_event(), SPIFFS_CHECK_RES, SPIFFS_DATA_PAGE_SIZE, SPIFFS_DBG, SPIFFS_EV_IX_NEW, spiffs_gc_check(), SPIFFS_OBJ_ID_IX_FLAG, SPIFFS_OBJ_LOOKUP_ENTRY_TO_PADDR, SPIFFS_OBJ_LOOKUP_ENTRY_TO_PIX, spiffs_obj_lu_find_free(), SPIFFS_OBJ_META_LEN, SPIFFS_OBJ_NAME_LEN, SPIFFS_OK, SPIFFS_OP_C_UPDT, SPIFFS_OP_T_OBJ_DA, SPIFFS_OP_T_OBJ_LU, spiffs_page_object_ix, spiffs_page_object_ix_header, SPIFFS_PH_FLAG_FINAL, SPIFFS_PH_FLAG_INDEX, SPIFFS_PH_FLAG_USED, SPIFFS_UNDEFINED_LEN, spiffs_t::stats_p_allocated, and spiffs_dirent::type.
Referenced by SPIFFS_creat(), and SPIFFS_open().
spiffs_object_find_object_index_header_by_name()
s32_t spiffs_object_find_object_index_header_by_name (spiffs * fs, const u8_t name[SPIFFS_OBJ_NAME_LEN], spiffs_page_ix * pix)
References spiffs_t::cursor_block_ix, spiffs_t::cursor_obj_lu_entry, and spiffs_obj_lu_find_entry_visitor().
Referenced by SPIFFS_open(), SPIFFS_remove(), SPIFFS_rename(), SPIFFS_stat(), and SPIFFS_update_meta().
spiffs_object_index_consistency_check()
s32_t spiffs_object_index_consistency_check (spiffs * fs)
References CHECK_CB, SPIFFS_CFG_LOG_PAGE_SZ, SPIFFS_CHECK_INDEX, SPIFFS_CHECK_PROGRESS, spiffs_obj_lu_find_entry_visitor(), SPIFFS_OK, and spiffs_t::work.
Referenced by SPIFFS_check().
spiffs_object_modify()
s32_t spiffs_object_modify (spiffs_fd * fd, u32_t offset, u8_t * data, u32_t len)
References _SPIPRIi, _SPIPRIpg, _SPIPRIsp, spiffs_fd::fs, spiffs_fd::obj_id, spiffs_fd::objix_hdr_pix, SPIFFS_CHECK_RES, SPIFFS_DATA_PAGE_SIZE, SPIFFS_DBG, spiffs_gc_check(), SPIFFS_OBJ_IX_ENTRY_SPAN_IX, spiffs_object_update_index_hdr(), SPIFFS_OK, spiffs_page_header, spiffs_page_object_ix, spiffs_page_object_ix_header, and spiffs_t::work.
spiffs_object_open_by_id()
s32_t spiffs_object_open_by_id (spiffs * fs, spiffs_obj_id obj_id, spiffs_fd * f, spiffs_flags flags, spiffs_mode mode)
References spiffs_dirent::pix, SPIFFS_CHECK_RES, SPIFFS_OBJ_ID_IX_FLAG, spiffs_obj_lu_find_id_and_span(), spiffs_object_open_by_page(), and SPIFFS_OK.
spiffs_object_open_by_page()
s32_t spiffs_object_open_by_page (spiffs * fs, spiffs_page_ix pix, spiffs_fd * f, spiffs_flags flags, spiffs_mode mode)
References _spiffs_rd, spiffs_fd::file_nbr, spiffs_fd::fs, spiffs_dirent::obj_id, SPIFFS_BLOCK_FOR_PAGE, SPIFFS_BLOCK_TO_PADDR, SPIFFS_CHECK_RES, SPIFFS_OBJ_LOOKUP_ENTRY_FOR_PAGE, SPIFFS_OK, SPIFFS_OP_C_READ, SPIFFS_OP_T_OBJ_IX, SPIFFS_OP_T_OBJ_LU, spiffs_page_object_ix_header, and SPIFFS_PAGE_TO_PADDR.
Referenced by spiffs_object_open_by_id(), SPIFFS_open(), SPIFFS_open_by_dirent(), SPIFFS_open_by_page(), SPIFFS_remove(), SPIFFS_rename(), and SPIFFS_update_meta().
spiffs_object_read()
s32_t spiffs_object_read (spiffs_fd * fd, u32_t offset, u32_t len, u8_t * dst)
References _spiffs_rd, _SPIPRIad, _SPIPRIi, _SPIPRIid, _SPIPRIpg, _SPIPRIsp, spiffs_fd::cursor_objix_pix, spiffs_fd::cursor_objix_spix, spiffs_fd::file_nbr, spiffs_fd::fs, MIN, spiffs_fd::obj_id, spiffs_fd::objix_hdr_pix, spiffs_fd::offset, spiffs_fd::size, SPIFFS_CFG_LOG_PAGE_SZ, SPIFFS_CHECK_RES, SPIFFS_DATA_PAGE_SIZE, SPIFFS_DBG, SPIFFS_ERR_END_OF_OBJECT, SPIFFS_OBJ_ID_IX_FLAG, SPIFFS_OBJ_IX_ENTRY, SPIFFS_OBJ_IX_ENTRY_SPAN_IX, spiffs_obj_lu_find_id_and_span(), SPIFFS_OK, SPIFFS_OP_C_READ, SPIFFS_OP_T_OBJ_IX, spiffs_page_header, spiffs_page_object_ix, spiffs_page_object_ix_header, SPIFFS_PAGE_TO_PADDR, SPIFFS_VALIDATE_OBJIX, and spiffs_t::work.
spiffs_object_truncate()
s32_t spiffs_object_truncate (spiffs_fd * fd, u32_t new_len, u8_t remove_object)
References _spiffs_wr, _SPIPRIpg, _SPIPRIsp, spiffs_fd::file_nbr, spiffs_fd::fs, spiffs_fd::objix_hdr_pix, spiffs_fd::size, SPIFFS_CHECK_RES, SPIFFS_DATA_PAGE_SIZE, SPIFFS_DBG, spiffs_gc_check(), SPIFFS_OBJ_IX_ENTRY_SPAN_IX, SPIFFS_OK, SPIFFS_OP_C_UPDT, SPIFFS_OP_T_OBJ_IX, spiffs_page_header, spiffs_page_object_ix, spiffs_page_object_ix_header, SPIFFS_PAGE_TO_PADDR, SPIFFS_PH_FLAG_FINAL, SPIFFS_PH_FLAG_INDEX, SPIFFS_PH_FLAG_IXDELE, SPIFFS_PH_FLAG_USED, SPIFFS_UNDEFINED_LEN, and spiffs_t::work.
Referenced by SPIFFS_fremove(), SPIFFS_open(), SPIFFS_open_by_dirent(), SPIFFS_open_by_page(), and SPIFFS_remove().
spiffs_object_update_index_hdr()
s32_t spiffs_object_update_index_hdr (spiffs * fs, spiffs_fd * fd, spiffs_obj_id obj_id, spiffs_page_ix objix_hdr_pix, u8_t * new_objix_hdr_data, const u8_t name[], const u8_t meta[], u32_t size, spiffs_page_ix * new_pix)
References _spiffs_rd, spiffs_fd::file_nbr, spiffs_fd::objix_hdr_pix, spiffs_dirent::size, spiffs_cb_object_event(), SPIFFS_CFG_LOG_PAGE_SZ, SPIFFS_CHECK_RES, SPIFFS_EV_IX_UPD, SPIFFS_EV_IX_UPD_HDR, SPIFFS_OBJ_ID_IX_FLAG, SPIFFS_OBJ_META_LEN, SPIFFS_OBJ_NAME_LEN, SPIFFS_OK, SPIFFS_OP_C_READ, SPIFFS_OP_T_OBJ_IX, spiffs_page_move(), spiffs_page_object_ix, spiffs_page_object_ix_header, SPIFFS_PAGE_TO_PADDR, SPIFFS_VALIDATE_OBJIX, and spiffs_t::work.
Referenced by SPIFFS_fupdate_meta(), spiffs_gc_clean(), spiffs_object_modify(), SPIFFS_rename(), and SPIFFS_update_meta().
spiffs_page_allocate_data()
s32_t spiffs_page_allocate_data (spiffs * fs, spiffs_obj_id obj_id, spiffs_page_header * ph, u8_t * data, u32_t len, u32_t page_offs, u8_t finalize, spiffs_page_ix * pix)
References _spiffs_wr, spiffs_t::free_cursor_block_ix, spiffs_t::free_cursor_obj_lu_entry, SPIFFS_BLOCK_TO_PADDR, SPIFFS_CHECK_RES, SPIFFS_OBJ_LOOKUP_ENTRY_TO_PADDR, SPIFFS_OBJ_LOOKUP_ENTRY_TO_PIX, spiffs_obj_lu_find_free(), SPIFFS_OK, SPIFFS_OP_C_UPDT, SPIFFS_OP_T_OBJ_DA, SPIFFS_OP_T_OBJ_LU, spiffs_page_header, SPIFFS_PH_FLAG_FINAL, SPIFFS_PH_FLAG_USED, and spiffs_t::stats_p_allocated.
spiffs_page_consistency_check()
s32_t spiffs_page_consistency_check (spiffs * fs)
References CHECK_CB, SPIFFS_CHECK_PAGE, and SPIFFS_CHECK_PROGRESS.
Referenced by SPIFFS_check().
spiffs_page_delete()
s32_t spiffs_page_delete (spiffs * fs, spiffs_page_ix pix)
References _spiffs_wr, SPIFFS_BLOCK_FOR_PAGE, SPIFFS_BLOCK_TO_PADDR, SPIFFS_CHECK_RES, SPIFFS_OBJ_ID_DELETED, SPIFFS_OBJ_LOOKUP_ENTRY_FOR_PAGE, SPIFFS_OP_C_DELE, SPIFFS_OP_T_OBJ_DA, SPIFFS_OP_T_OBJ_LU, spiffs_page_header, SPIFFS_PAGE_TO_PADDR, SPIFFS_PH_FLAG_DELET, SPIFFS_PH_FLAG_USED, spiffs_t::stats_p_allocated, and spiffs_t::stats_p_deleted.
Referenced by spiffs_gc_clean(), and spiffs_page_move().
spiffs_page_move()
s32_t spiffs_page_move (spiffs * fs, spiffs_file fh, u8_t * page_data, spiffs_obj_id obj_id, spiffs_page_header * page_hdr, spiffs_page_ix src_pix, spiffs_page_ix * dst_pix)
References _spiffs_wr, spiffs_t::free_cursor_block_ix, spiffs_t::free_cursor_obj_lu_entry, SPIFFS_BLOCK_FOR_PAGE, SPIFFS_BLOCK_TO_PADDR, SPIFFS_CFG_LOG_PAGE_SZ, SPIFFS_CHECK_RES, SPIFFS_OBJ_LOOKUP_ENTRY_FOR_PAGE, SPIFFS_OBJ_LOOKUP_ENTRY_TO_PIX, spiffs_obj_lu_find_free(), SPIFFS_OP_C_UPDT, SPIFFS_OP_T_OBJ_DA, SPIFFS_OP_T_OBJ_LU, spiffs_page_delete(), spiffs_page_header, SPIFFS_PAGE_TO_PADDR, SPIFFS_PH_FLAG_FINAL, SPIFFS_PH_FLAG_USED, spiffs_phys_cpy(), and spiffs_t::stats_p_allocated.
Referenced by spiffs_gc_clean(), and spiffs_object_update_index_hdr().
spiffs_phys_count_free_blocks()
s32_t spiffs_phys_count_free_blocks (spiffs * fs)
spiffs_phys_cpy()
s32_t spiffs_phys_cpy (spiffs * fs, spiffs_file fh, u32_t dst, u32_t src, u32_t len)
References _spiffs_rd, _spiffs_wr, MIN, SPIFFS_CHECK_RES, SPIFFS_COPY_BUFFER_STACK, SPIFFS_OK, SPIFFS_OP_C_MOVD, SPIFFS_OP_C_MOVS, and SPIFFS_OP_T_OBJ_DA.
Referenced by spiffs_page_move().
spiffs_phys_rd()
s32_t spiffs_phys_rd (spiffs * fs, u32_t addr, u32_t len, u8_t * dst)
spiffs_phys_wr()
s32_t spiffs_phys_wr (spiffs * fs, u32_t addr, u32_t len, u8_t * src)
Variable Documentation
spiffs_page_header
spiffs_page_header
spiffs_page_object_ix
spiffs_page_object_ix
spiffs_page_object_ix_header
spiffs_page_object_ix_header