Projekt Ei: HardwareLife/Lcd/ESP32_TFT_library/components/spiffs/spiffs_gc.c File Reference
spiffs_gc.c File Reference
#include "spiffs.h"
#include "spiffs_nucleus.h"
Classes
struct spiffs_gc
Enumerations
enum spiffs_gc_clean_state {
FIND_OBJ_DATA, MOVE_OBJ_DATA, MOVE_OBJ_IX, FINISHED,
FIND_OBJ_DATA, MOVE_OBJ_DATA, MOVE_OBJ_IX, FINISHED
}
Functions
s32_t spiffs_gc_quick (spiffs *fs, u16_t max_free_pages)
s32_t spiffs_gc_check (spiffs *fs, u32_t len)
s32_t spiffs_gc_erase_page_stats (spiffs *fs, spiffs_block_ix bix)
s32_t spiffs_gc_find_candidate (spiffs *fs, spiffs_block_ix **block_candidates, int *candidate_count, char fs_crammed)
s32_t spiffs_gc_clean (spiffs *fs, spiffs_block_ix bix)
Class Documentation
spiffs_gc
struct spiffs_gc
Class Members
spiffs_page_ix cur_data_pix
spiffs_obj_id cur_obj_id
spiffs_page_ix cur_objix_pix
spiffs_span_ix cur_objix_spix
u8_t obj_id_found
spiffs_gc_clean_state state
int stored_scan_entry_index
Enumeration Type Documentation
spiffs_gc_clean_state
enum spiffs_gc_clean_state
Enumerator
FIND_OBJ_DATA
MOVE_OBJ_DATA
MOVE_OBJ_IX
FINISHED
FIND_OBJ_DATA
MOVE_OBJ_DATA
MOVE_OBJ_IX
FINISHED
Function Documentation
spiffs_gc_check()
s32_t spiffs_gc_check (spiffs * fs, u32_t len)
References _SPIPRIi, spiffs_t::block_count, spiffs_t::cleaning, spiffs_t::free_blocks, SPIFFS_CHECK_RES, SPIFFS_DATA_PAGE_SIZE, SPIFFS_ERR_FULL, spiffs_gc_clean(), SPIFFS_GC_DBG, spiffs_gc_erase_page_stats(), spiffs_gc_find_candidate(), SPIFFS_OBJ_LOOKUP_PAGES, SPIFFS_OK, SPIFFS_PAGES_PER_BLOCK, spiffs_t::stats_p_allocated, and spiffs_t::stats_p_deleted.
spiffs_gc_clean()
s32_t spiffs_gc_clean (spiffs * fs, spiffs_block_ix bix)
References _spiffs_rd, _SPIPRIbl, _SPIPRIi, _SPIPRIid, _SPIPRIpg, _SPIPRIsp, spiffs_t::block_count, FIND_OBJ_DATA, FINISHED, spiffs_t::free_cursor_block_ix, spiffs_t::free_cursor_obj_lu_entry, spiffs_t::lu_work, MOVE_OBJ_DATA, MOVE_OBJ_IX, spiffs_dirent::obj_id, spiffs_cb_object_event(), SPIFFS_CFG_LOG_BLOCK_SZ, SPIFFS_CFG_LOG_PAGE_SZ, SPIFFS_CHECK_RES, SPIFFS_ERR_NOT_FOUND, SPIFFS_EV_IX_DEL, SPIFFS_EV_IX_MOV, SPIFFS_EV_IX_UPD, SPIFFS_GC_DBG, SPIFFS_OBJ_ID_DELETED, SPIFFS_OBJ_ID_FREE, SPIFFS_OBJ_ID_IX_FLAG, SPIFFS_OBJ_IX_ENTRY, SPIFFS_OBJ_IX_ENTRY_SPAN_IX, SPIFFS_OBJ_LOOKUP_ENTRY_TO_PIX, SPIFFS_OBJ_LOOKUP_PAGES, spiffs_obj_lu_find_id_and_span(), spiffs_object_update_index_hdr(), SPIFFS_OK, SPIFFS_OP_C_READ, SPIFFS_OP_T_OBJ_LU, SPIFFS_OP_T_OBJ_LU2, spiffs_page_delete(), spiffs_page_header, spiffs_page_move(), spiffs_page_object_ix, spiffs_page_object_ix_header, SPIFFS_PAGE_TO_PADDR, SPIFFS_PAGES_PER_BLOCK, SPIFFS_PH_FLAG_DELET, SPIFFS_VALIDATE_OBJIX, and spiffs_t::work.
spiffs_gc_erase_page_stats()
s32_t spiffs_gc_erase_page_stats (spiffs * fs, spiffs_block_ix bix)
References _spiffs_rd, _SPIPRIi, spiffs_t::lu_work, spiffs_dirent::obj_id, SPIFFS_CFG_LOG_BLOCK_SZ, SPIFFS_CFG_LOG_PAGE_SZ, SPIFFS_GC_DBG, SPIFFS_OBJ_ID_DELETED, SPIFFS_OBJ_ID_FREE, SPIFFS_OBJ_LOOKUP_PAGES, SPIFFS_OK, SPIFFS_OP_C_READ, SPIFFS_OP_T_OBJ_LU, SPIFFS_PAGE_TO_PADDR, SPIFFS_PAGES_PER_BLOCK, spiffs_t::stats_p_allocated, and spiffs_t::stats_p_deleted.
spiffs_gc_find_candidate()
s32_t spiffs_gc_find_candidate (spiffs * fs, spiffs_block_ix ** block_candidates, int * candidate_count, char fs_crammed)
References _spiffs_rd, _SPIPRIbl, _SPIPRIi, spiffs_t::block_count, spiffs_t::lu_work, spiffs_t::max_erase_count, MIN, spiffs_dirent::obj_id, SPIFFS_CFG_LOG_BLOCK_SZ, SPIFFS_CFG_LOG_PAGE_SZ, SPIFFS_CHECK_RES, SPIFFS_ERASE_COUNT_PADDR, SPIFFS_GC_DBG, SPIFFS_GC_HEUR_W_DELET, SPIFFS_GC_HEUR_W_ERASE_AGE, SPIFFS_GC_HEUR_W_USED, SPIFFS_OBJ_ID_DELETED, SPIFFS_OBJ_ID_FREE, SPIFFS_OBJ_LOOKUP_PAGES, SPIFFS_OK, SPIFFS_OP_C_READ, SPIFFS_OP_T_OBJ_LU, SPIFFS_OP_T_OBJ_LU2, SPIFFS_PAGE_TO_PADDR, SPIFFS_PAGES_PER_BLOCK, and spiffs_t::work.
spiffs_gc_quick()
s32_t spiffs_gc_quick (spiffs * fs, u16_t max_free_pages)
References _spiffs_rd, spiffs_t::block_count, spiffs_t::lu_work, spiffs_dirent::obj_id, SPIFFS_CFG_LOG_PAGE_SZ, SPIFFS_GC_DBG, SPIFFS_OBJ_ID_DELETED, SPIFFS_OBJ_ID_FREE, SPIFFS_OBJ_LOOKUP_PAGES, SPIFFS_OK, SPIFFS_OP_C_READ, SPIFFS_OP_T_OBJ_LU, SPIFFS_PAGE_TO_PADDR, SPIFFS_PAGES_PER_BLOCK, and spiffs_t::stats_p_deleted.