Projekt Ei: HardwareLife/Lcd/ESP32_TFT_library/components/spiffs/spiffs_hydrogen.c File Reference
spiffs_hydrogen.c File Reference
#include "spiffs.h"
#include "spiffs_nucleus.h"
Macros
#define SPIFFS_FH_OFFS(fs, fh) (fh)
#define SPIFFS_FH_UNOFFS(fs, fh) (fh)
Functions
u8_t SPIFFS_mounted (spiffs *fs)
s32_t SPIFFS_format (spiffs *fs)
s32_t SPIFFS_probe_fs (spiffs_config *config)
s32_t SPIFFS_mount (spiffs *fs, spiffs_config *config, u8_t *work, u8_t *fd_space, u32_t fd_space_size, void *cache, u32_t cache_size, spiffs_check_callback check_cb_f)
void SPIFFS_unmount (spiffs *fs)
s32_t SPIFFS_errno (spiffs *fs)
void SPIFFS_clearerr (spiffs *fs)
s32_t SPIFFS_creat (spiffs *fs, const char *path, spiffs_mode mode)
spiffs_file SPIFFS_open (spiffs *fs, const char *path, spiffs_flags flags, spiffs_mode mode)
spiffs_file SPIFFS_open_by_dirent (spiffs *fs, struct spiffs_dirent *e, spiffs_flags flags, spiffs_mode mode)
spiffs_file SPIFFS_open_by_page (spiffs *fs, spiffs_page_ix page_ix, spiffs_flags flags, spiffs_mode mode)
s32_t SPIFFS_read (spiffs *fs, spiffs_file fh, void *buf, s32_t len)
s32_t SPIFFS_write (spiffs *fs, spiffs_file fh, void *buf, s32_t len)
s32_t SPIFFS_lseek (spiffs *fs, spiffs_file fh, s32_t offs, int whence)
s32_t SPIFFS_remove (spiffs *fs, const char *path)
s32_t SPIFFS_fremove (spiffs *fs, spiffs_file fh)
s32_t SPIFFS_stat (spiffs *fs, const char *path, spiffs_stat *s)
s32_t SPIFFS_fstat (spiffs *fs, spiffs_file fh, spiffs_stat *s)
s32_t SPIFFS_fflush (spiffs *fs, spiffs_file fh)
s32_t SPIFFS_close (spiffs *fs, spiffs_file fh)
s32_t SPIFFS_rename (spiffs *fs, const char *old_path, const char *new_path)
s32_t SPIFFS_update_meta (spiffs *fs, const char *name, const void *meta)
s32_t SPIFFS_fupdate_meta (spiffs *fs, spiffs_file fh, const void *meta)
spiffs_DIR * SPIFFS_opendir (spiffs *fs, const char *name, spiffs_DIR *d)
struct spiffs_dirent * SPIFFS_readdir (spiffs_DIR *d, struct spiffs_dirent *e)
s32_t SPIFFS_closedir (spiffs_DIR *d)
s32_t SPIFFS_check (spiffs *fs)
s32_t SPIFFS_info (spiffs *fs, u32_t *total, u32_t *used)
s32_t SPIFFS_gc_quick (spiffs *fs, u16_t max_free_pages)
s32_t SPIFFS_gc (spiffs *fs, u32_t size)
s32_t SPIFFS_eof (spiffs *fs, spiffs_file fh)
s32_t SPIFFS_tell (spiffs *fs, spiffs_file fh)
s32_t SPIFFS_set_file_callback_func (spiffs *fs, spiffs_file_callback cb_func)
s32_t SPIFFS_ix_map (spiffs *fs, spiffs_file fh, spiffs_ix_map *map, u32_t offset, u32_t len, spiffs_page_ix *map_buf)
s32_t SPIFFS_ix_unmap (spiffs *fs, spiffs_file fh)
s32_t SPIFFS_ix_remap (spiffs *fs, spiffs_file fh, u32_t offset)
s32_t SPIFFS_bytes_to_ix_map_entries (spiffs *fs, u32_t bytes)
s32_t SPIFFS_ix_map_entries_to_bytes (spiffs *fs, u32_t map_page_ix_entries)
Macro Definition Documentation
SPIFFS_FH_OFFS
#define SPIFFS_FH_OFFS (fs, fh) (fh)
Referenced by SPIFFS_open(), SPIFFS_open_by_dirent(), and SPIFFS_open_by_page().
SPIFFS_FH_UNOFFS
#define SPIFFS_FH_UNOFFS (fs, fh) (fh)
Referenced by SPIFFS_close(), SPIFFS_eof(), SPIFFS_fflush(), SPIFFS_fremove(), SPIFFS_fstat(), SPIFFS_fupdate_meta(), SPIFFS_ix_map(), SPIFFS_ix_remap(), SPIFFS_ix_unmap(), SPIFFS_lseek(), SPIFFS_tell(), and SPIFFS_write().
Function Documentation
SPIFFS_bytes_to_ix_map_entries()
s32_t SPIFFS_bytes_to_ix_map_entries (spiffs * fs, u32_t bytes)
Utility function to get number of spiffs_page_ix entries a map buffer must contain on order to map given amount of file data in bytes. See function SPIFFS_ix_map and SPIFFS_ix_map_entries_to_bytes.
Parameters
fs the file system struct
bytes number of file data bytes to map
Returns
needed number of elements in a spiffs_page_ix array needed to map given amount of bytes in a file
References SPIFFS_API_CHECK_CFG, and SPIFFS_DATA_PAGE_SIZE.
SPIFFS_check()
s32_t SPIFFS_check (spiffs * fs)
Runs a consistency check on given filesystem.
Parameters
fs the file system struct
References SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_ERR_RO_NOT_IMPL, SPIFFS_LOCK, spiffs_lookup_consistency_check(), spiffs_obj_lu_scan(), spiffs_object_index_consistency_check(), spiffs_page_consistency_check(), and SPIFFS_UNLOCK.
SPIFFS_clearerr()
void SPIFFS_clearerr (spiffs * fs)
Clears last error.
Parameters
fs the file system struct
References spiffs_t::err_code, and SPIFFS_OK.
SPIFFS_close()
s32_t SPIFFS_close (spiffs * fs, spiffs_file fh)
Closes a filehandle. If there are pending write operations, these are finalized before closing.
Parameters
fs the file system struct
fh the filehandle of the file to close
References SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_FH_UNOFFS, SPIFFS_LOCK, and SPIFFS_OK.
Referenced by addDir(), addFile(), and unpackFile().
SPIFFS_closedir()
s32_t SPIFFS_closedir (spiffs_DIR * d)
Closes a directory stream
Parameters
d the directory stream to close
References spiffs_DIR::fs, SPIFFS_API_CHECK_CFG, and SPIFFS_API_CHECK_MOUNT.
Referenced by listFiles(), and unpackFiles().
SPIFFS_creat()
s32_t SPIFFS_creat (spiffs * fs, const char * path, spiffs_mode mode)
Creates a new file.
Parameters
fs the file system struct
path the path of the new file
mode ignored, for posix compliance
References spiffs_dirent::obj_id, SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_API_CHECK_RES, SPIFFS_API_CHECK_RES_UNLOCK, SPIFFS_ERR_NAME_TOO_LONG, SPIFFS_ERR_RO_NOT_IMPL, SPIFFS_LOCK, spiffs_obj_lu_find_free_obj_id(), SPIFFS_OBJ_NAME_LEN, spiffs_object_create(), SPIFFS_TYPE_FILE, and SPIFFS_UNLOCK.
SPIFFS_eof()
s32_t SPIFFS_eof (spiffs * fs, spiffs_file fh)
Check if EOF reached.
Parameters
fs the file system struct
fh the filehandle of the file to check
References SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_API_CHECK_RES_UNLOCK, spiffs_fd_get(), SPIFFS_FH_UNOFFS, and SPIFFS_LOCK.
SPIFFS_errno()
s32_t SPIFFS_errno (spiffs * fs)
Returns last error of last file operation.
Parameters
fs the file system struct
References spiffs_t::err_code.
SPIFFS_fflush()
s32_t SPIFFS_fflush (spiffs * fs, spiffs_file fh)
Flushes all pending write operations from cache for given file
Parameters
fs the file system struct
fh the filehandle of the file to flush
References SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_FH_UNOFFS, SPIFFS_LOCK, and SPIFFS_OK.
SPIFFS_format()
s32_t SPIFFS_format (spiffs * fs)
Formats the entire file system. All data will be lost. The filesystem must not be mounted when calling this.
NB: formatting is awkward. Due to backwards compatibility, SPIFFS_mount MUST be called prior to formatting in order to configure the filesystem. If SPIFFS_mount succeeds, SPIFFS_unmount must be called before calling SPIFFS_format. If SPIFFS_mount fails, SPIFFS_format can be called directly without calling SPIFFS_unmount first.
Parameters
fs the file system struct
References spiffs_t::err_code, spiffs_t::max_erase_count, SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_RES_UNLOCK, SPIFFS_CHECK_MOUNT, spiffs_erase_block(), SPIFFS_ERR_ERASE_FAIL, SPIFFS_ERR_MOUNTED, SPIFFS_ERR_RO_NOT_IMPL, SPIFFS_LOCK, SPIFFS_OK, and SPIFFS_UNLOCK.
Referenced by spiffsFormat().
SPIFFS_fremove()
s32_t SPIFFS_fremove (spiffs * fs, spiffs_file fh)
Removes a file by filehandle
Parameters
fs the file system struct
fh the filehandle of the file to remove
References spiffs_fd::flags, SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_API_CHECK_RES_UNLOCK, spiffs_cache_fd_release(), SPIFFS_ERR_NOT_WRITABLE, SPIFFS_ERR_RO_NOT_IMPL, spiffs_fd_get(), SPIFFS_FH_UNOFFS, SPIFFS_LOCK, SPIFFS_O_WRONLY, spiffs_object_truncate(), and SPIFFS_UNLOCK.
SPIFFS_fstat()
s32_t SPIFFS_fstat (spiffs * fs, spiffs_file fh, spiffs_stat * s)
Gets file status by filehandle
Parameters
fs the file system struct
fh the filehandle of the file to stat
s the stat struct to populate
References SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_API_CHECK_RES_UNLOCK, spiffs_fd_get(), SPIFFS_FH_UNOFFS, and SPIFFS_LOCK.
SPIFFS_fupdate_meta()
s32_t SPIFFS_fupdate_meta (spiffs * fs, spiffs_file fh, const void * meta)
Updates file's metadata
Parameters
fs the file system struct
fh file handle of the file
meta new metadata. must be SPIFFS_OBJ_META_LEN bytes long.
References spiffs_fd::flags, spiffs_fd::obj_id, spiffs_fd::objix_hdr_pix, SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_API_CHECK_RES_UNLOCK, SPIFFS_ERR_NOT_WRITABLE, SPIFFS_ERR_RO_NOT_IMPL, spiffs_fd_get(), SPIFFS_FH_UNOFFS, SPIFFS_LOCK, SPIFFS_O_WRONLY, spiffs_object_update_index_hdr(), and SPIFFS_UNLOCK.
SPIFFS_gc()
s32_t SPIFFS_gc (spiffs * fs, u32_t size)
Will try to make room for given amount of bytes in the filesystem by moving pages and erasing blocks. If it is physically impossible, err_no will be set to SPIFFS_ERR_FULL. If there already is this amount (or more) of free space, SPIFFS_gc will silently return. It is recommended to call SPIFFS_info before invoking this method in order to determine what amount of bytes to give.
NB: the garbage collector is automatically called when spiffs needs free pages. The reason for this function is to give possibility to do background tidying when user knows the system is idle.
Use with care.
Parameters
fs the file system struct
size amount of bytes that should be freed
References SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_API_CHECK_RES_UNLOCK, SPIFFS_ERR_RO_NOT_IMPL, spiffs_gc_check(), SPIFFS_LOCK, and SPIFFS_UNLOCK.
SPIFFS_gc_quick()
s32_t SPIFFS_gc_quick (spiffs * fs, u16_t max_free_pages)
Tries to find a block where most or all pages are deleted, and erase that block if found. Does not care for wear levelling. Will not move pages around. If parameter max_free_pages are set to 0, only blocks with only deleted pages will be selected.
NB: the garbage collector is automatically called when spiffs needs free pages. The reason for this function is to give possibility to do background tidying when user knows the system is idle.
Use with care.
Setting max_free_pages to anything larger than zero will eventually wear flash more as a block containing free pages can be erased.
Will set err_no to SPIFFS_OK if a block was found and erased, SPIFFS_ERR_NO_DELETED_BLOCK if no matching block was found, or other error.
Parameters
fs the file system struct
max_free_pages maximum number allowed free pages in block
References SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_API_CHECK_RES_UNLOCK, SPIFFS_ERR_RO_NOT_IMPL, spiffs_gc_quick(), SPIFFS_LOCK, and SPIFFS_UNLOCK.
SPIFFS_info()
s32_t SPIFFS_info (spiffs * fs, u32_t * total, u32_t * used)
Returns number of total bytes available and number of used bytes. This is an estimation, and depends on if there a many files with little data or few files with much data. NB: If used number of bytes exceeds total bytes, a SPIFFS_check should run. This indicates a power loss in midst of things. In worst case (repeated powerlosses in mending or gc) you might have to delete some files.
Parameters
fs the file system struct
total total number of bytes in filesystem
used used number of bytes in filesystem
References spiffs_t::block_count, SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_DATA_PAGE_SIZE, SPIFFS_LOCK, SPIFFS_OBJ_LOOKUP_PAGES, SPIFFS_OK, SPIFFS_PAGES_PER_BLOCK, SPIFFS_UNLOCK, and spiffs_t::stats_p_allocated.
Referenced by spiffs_fs_stat().
SPIFFS_ix_map()
s32_t SPIFFS_ix_map (spiffs * fs, spiffs_file fh, spiffs_ix_map * map, u32_t offset, u32_t len, spiffs_page_ix * map_buf)
Maps the first level index lookup to a given memory map. This will make reading big files faster, as the memory map will be used for looking up data pages instead of searching for the indices on the physical medium. When mapping, all affected indicies are found and the information is copied to the array. Whole file or only parts of it may be mapped. The index map will cover file contents from argument offset until and including arguments (offset+len). It is valid to map a longer range than the current file size. The map will then be populated when the file grows. On garbage collections and file data page movements, the map array will be automatically updated. Do not tamper with the map array, as this contains the references to the data pages. Modifying it from outside will corrupt any future readings using this file descriptor. The map will no longer be used when the file descriptor closed or the file is unmapped. This can be useful to get faster and more deterministic timing when reading large files, or when seeking and reading a lot within a file.
Parameters
fs the file system struct
fh the file handle of the file to map
map a spiffs_ix_map struct, describing the index map
offset absolute file offset where to start the index map
len length of the mapping in actual file bytes
map_buf the array buffer for the look up data - number of required elements in the array can be derived from function SPIFFS_bytes_to_ix_map_entries given the length
References spiffs_ix_map::end_spix, spiffs_ix_map::map_buf, spiffs_ix_map::offset, SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_API_CHECK_RES_UNLOCK, SPIFFS_DATA_PAGE_SIZE, SPIFFS_ERR_IX_MAP_MAPPED, spiffs_fd_get(), SPIFFS_FH_UNOFFS, SPIFFS_LOCK, spiffs_populate_ix_map(), SPIFFS_UNLOCK, and spiffs_ix_map::start_spix.
SPIFFS_ix_map_entries_to_bytes()
s32_t SPIFFS_ix_map_entries_to_bytes (spiffs * fs, u32_t map_page_ix_entries)
Utility function to amount of file data bytes that can be mapped when mapping a file with buffer having given number of spiffs_page_ix entries. See function SPIFFS_ix_map and SPIFFS_bytes_to_ix_map_entries.
Parameters
fs the file system struct
map_page_ix_entries number of entries in a spiffs_page_ix array
Returns
amount of file data in bytes that can be mapped given a map buffer having given amount of spiffs_page_ix entries
References _spiffs_rd, _SPIPRIbl, _SPIPRIi, spiffs_t::block_count, spiffs_t::err_code, spiffs_t::free_blocks, spiffs_t::lu_work, spiffs_t::max_erase_count, SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_CFG_LOG_BLOCK_SZ, SPIFFS_CFG_LOG_PAGE_SZ, SPIFFS_CHECK_RES, SPIFFS_DATA_PAGE_SIZE, SPIFFS_ERASE_COUNT_PADDR, SPIFFS_info(), SPIFFS_LOCK, SPIFFS_OBJ_ID_DELETED, SPIFFS_OBJ_ID_FREE, SPIFFS_OBJ_ID_IX_FLAG, SPIFFS_OBJ_LOOKUP_PAGES, SPIFFS_OK, SPIFFS_OP_C_READ, SPIFFS_OP_T_OBJ_LU, SPIFFS_OP_T_OBJ_LU2, SPIFFS_PAGE_TO_PADDR, SPIFFS_PAGES_PER_BLOCK, SPIFFS_UNLOCK, spiffs_t::stats_p_allocated, and spiffs_t::stats_p_deleted.
SPIFFS_ix_remap()
s32_t SPIFFS_ix_remap (spiffs * fs, spiffs_file fh, u32_t offs)
Moves the offset for the index map given in function SPIFFS_ix_map. Parts or all of the map buffer will repopulated.
Parameters
fs the file system struct
fh the mapped file handle of the file to remap
offset new absolute file offset where to start the index map
References spiffs_ix_map::end_spix, spiffs_ix_map::map_buf, spiffs_ix_map::offset, SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_API_CHECK_RES_UNLOCK, SPIFFS_DATA_PAGE_SIZE, SPIFFS_ERR_IX_MAP_UNMAPPED, spiffs_fd_get(), SPIFFS_FH_UNOFFS, SPIFFS_LOCK, SPIFFS_OK, spiffs_populate_ix_map(), SPIFFS_UNLOCK, and spiffs_ix_map::start_spix.
SPIFFS_ix_unmap()
s32_t SPIFFS_ix_unmap (spiffs * fs, spiffs_file fh)
Unmaps the index lookup from this filehandle. All future readings will proceed as normal, requiring reading of the first level indices from physical media. The map and map buffer given in function SPIFFS_ix_map will no longer be referenced by spiffs. It is not strictly necessary to unmap a file before closing it, as closing a file will automatically unmap it.
Parameters
fs the file system struct
fh the file handle of the file to unmap
References SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_API_CHECK_RES_UNLOCK, SPIFFS_ERR_IX_MAP_UNMAPPED, spiffs_fd_get(), SPIFFS_FH_UNOFFS, SPIFFS_LOCK, and SPIFFS_UNLOCK.
SPIFFS_lseek()
s32_t SPIFFS_lseek (spiffs * fs, spiffs_file fh, s32_t offs, int whence)
Moves the read/write file offset. Resulting offset is returned or negative if error. lseek(fs, fd, 0, SPIFFS_SEEK_CUR) will thus return current offset.
Parameters
fs the file system struct
fh the filehandle
offs how much/where to move the offset
whence if SPIFFS_SEEK_SET, the file offset shall be set to offset bytes if SPIFFS_SEEK_CUR, the file offset shall be set to its current location plus offset if SPIFFS_SEEK_END, the file offset shall be set to the size of the file plus offse, which should be negative
References SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_API_CHECK_RES_UNLOCK, spiffs_fd_get(), SPIFFS_FH_UNOFFS, and SPIFFS_LOCK.
SPIFFS_mount()
s32_t SPIFFS_mount (spiffs * fs, spiffs_config * config, u8_t * work, u8_t * fd_space, u32_t fd_space_size, void * cache, u32_t cache_size, spiffs_check_callback check_cb_f)
Initializes the file system dynamic parameters and mounts the filesystem. If SPIFFS_USE_MAGIC is enabled the mounting may fail with SPIFFS_ERR_NOT_A_FS if the flash does not contain a recognizable file system. In this case, SPIFFS_format must be called prior to remounting.
Parameters
fs the file system struct
config the physical and logical configuration of the file system
work a memory work buffer comprising 2*config->log_page_size bytes used throughout all file system operations
fd_space memory for file descriptors
fd_space_size memory size of file descriptors
cache memory for cache, may be null
cache_size memory size of cache
check_cb_f callback function for reporting during consistency checks
References _SPIPRIi, spiffs_t::block_count, spiffs_t::cache, spiffs_t::cache_size, spiffs_t::cfg, spiffs_t::check_cb_f, spiffs_t::config_magic, spiffs_t::fd_count, spiffs_t::fd_space, spiffs_t::free_blocks, spiffs_t::lu_work, spiffs_t::mounted, SPIFFS_API_CHECK_RES_UNLOCK, spiffs_cache_init(), SPIFFS_CFG_LOG_BLOCK_SZ, SPIFFS_CFG_LOG_PAGE_SZ, SPIFFS_CFG_PHYS_SZ, SPIFFS_CHECK_MAGIC_POSSIBLE, SPIFFS_CONFIG_MAGIC, SPIFFS_DBG, SPIFFS_ERR_MAGIC_NOT_POSSIBLE, SPIFFS_LOCK, SPIFFS_OBJ_HDR_IX_LEN, SPIFFS_OBJ_IX_LEN, SPIFFS_OBJ_LOOKUP_PAGES, spiffs_obj_lu_scan(), SPIFFS_OK, spiffs_page_header, SPIFFS_PAGES_PER_BLOCK, SPIFFS_UNLOCK, spiffs_t::user_data, and spiffs_t::work.
SPIFFS_mounted()
u8_t SPIFFS_mounted (spiffs * fs)
Returns nonzero if spiffs is mounted, or zero if unmounted.
Parameters
fs the file system struct
References SPIFFS_CHECK_MOUNT.
Referenced by spiffsMount(), and spiffsUnmount().
SPIFFS_open()
spiffs_file SPIFFS_open (spiffs * fs, const char * path, spiffs_flags flags, spiffs_mode mode)
Opens/creates a file.
Parameters
fs the file system struct
path the path of the new file
flags the flags for the open command, can be combinations of SPIFFS_O_APPEND, SPIFFS_O_TRUNC, SPIFFS_O_CREAT, SPIFFS_O_RDONLY, SPIFFS_O_WRONLY, SPIFFS_O_RDWR, SPIFFS_O_DIRECT, SPIFFS_O_EXCL
mode ignored, for posix compliance
References spiffs_fd::fdoffset, spiffs_fd::file_nbr, spiffs_dirent::obj_id, spiffs_dirent::pix, SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_API_CHECK_RES, SPIFFS_API_CHECK_RES_UNLOCK, SPIFFS_CREAT, SPIFFS_ERR_FILE_EXISTS, SPIFFS_ERR_NAME_TOO_LONG, SPIFFS_ERR_NOT_FOUND, spiffs_fd_find_new(), spiffs_fd_return(), SPIFFS_FH_OFFS, SPIFFS_LOCK, SPIFFS_O_CREAT, SPIFFS_O_EXCL, SPIFFS_O_TRUNC, spiffs_obj_lu_find_free_obj_id(), SPIFFS_OBJ_NAME_LEN, spiffs_object_create(), spiffs_object_find_object_index_header_by_name(), spiffs_object_open_by_page(), spiffs_object_truncate(), SPIFFS_OK, SPIFFS_TRUNC, SPIFFS_TYPE_FILE, SPIFFS_UNLOCK, and SPIFFS_WRONLY.
Referenced by addDir(), addFile(), and unpackFile().
SPIFFS_open_by_dirent()
spiffs_file SPIFFS_open_by_dirent (spiffs * fs, struct spiffs_dirent * e, spiffs_flags flags, spiffs_mode mode)
Opens a file by given dir entry. Optimization purposes, when traversing a file system with SPIFFS_readdir a normal SPIFFS_open would need to traverse the filesystem again to find the file, whilst SPIFFS_open_by_dirent already knows where the file resides.
Parameters
fs the file system struct
e the dir entry to the file
flags the flags for the open command, can be combinations of SPIFFS_APPEND, SPIFFS_TRUNC, SPIFFS_CREAT, SPIFFS_RD_ONLY, SPIFFS_WR_ONLY, SPIFFS_RDWR, SPIFFS_DIRECT. SPIFFS_CREAT will have no effect in this case.
mode ignored, for posix compliance
References spiffs_fd::fdoffset, spiffs_fd::file_nbr, spiffs_dirent::pix, SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_API_CHECK_RES_UNLOCK, spiffs_fd_find_new(), spiffs_fd_return(), SPIFFS_FH_OFFS, SPIFFS_LOCK, SPIFFS_O_TRUNC, spiffs_object_open_by_page(), spiffs_object_truncate(), SPIFFS_OK, and SPIFFS_UNLOCK.
SPIFFS_open_by_page()
spiffs_file SPIFFS_open_by_page (spiffs * fs, spiffs_page_ix page_ix, spiffs_flags flags, spiffs_mode mode)
Opens a file by given page index. Optimization purposes, opens a file by directly pointing to the page index in the spi flash. If the page index does not point to a file header SPIFFS_ERR_NOT_A_FILE is returned.
Parameters
fs the file system struct
page_ix the page index
flags the flags for the open command, can be combinations of SPIFFS_APPEND, SPIFFS_TRUNC, SPIFFS_CREAT, SPIFFS_RD_ONLY, SPIFFS_WR_ONLY, SPIFFS_RDWR, SPIFFS_DIRECT. SPIFFS_CREAT will have no effect in this case.
mode ignored, for posix compliance
References spiffs_fd::fdoffset, spiffs_fd::file_nbr, SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_API_CHECK_RES_UNLOCK, SPIFFS_ERR_DELETED, SPIFFS_ERR_INDEX_SPAN_MISMATCH, SPIFFS_ERR_IS_FREE, SPIFFS_ERR_NOT_A_FILE, SPIFFS_ERR_NOT_FINALIZED, SPIFFS_ERR_NOT_INDEX, spiffs_fd_find_new(), spiffs_fd_return(), SPIFFS_FH_OFFS, SPIFFS_IS_LOOKUP_PAGE, SPIFFS_LOCK, SPIFFS_O_TRUNC, spiffs_object_open_by_page(), spiffs_object_truncate(), SPIFFS_OK, and SPIFFS_UNLOCK.
SPIFFS_opendir()
spiffs_DIR* SPIFFS_opendir (spiffs * fs, const char * name, spiffs_DIR * d)
Opens a directory stream corresponding to the given name. The stream is positioned at the first entry in the directory. On hydrogen builds the name argument is ignored as hydrogen builds always correspond to a flat file structure - no directories.
Parameters
fs the file system struct
name the name of the directory
d pointer the directory stream to be populated
References SPIFFS_CHECK_CFG.
Referenced by listFiles(), and unpackFiles().
SPIFFS_probe_fs()
s32_t SPIFFS_probe_fs (spiffs_config * config)
Special function. This takes a spiffs config struct and returns the number of blocks this file system was formatted with. This function relies on that following info is set correctly in given config struct:
phys_addr, log_page_size, and log_block_size.
Also, hal_read_f must be set in the config struct.
One must be sure of the correct page size and that the physical address is correct in the probed file system when calling this function. It is not checked if the phys_addr actually points to the start of the file system, so one might get a false positive if entering a phys_addr somewhere in the middle of the file system at block boundary. In addition, it is not checked if the page size is actually correct. If it is not, weird file system sizes will be returned.
If this function detects a file system it returns the assumed file system size, which can be used to set the phys_size.
Otherwise, it returns an error indicating why it is not regarded as a file system.
Note: this function is not protected with SPIFFS_LOCK and SPIFFS_UNLOCK macros. It returns the error code directly, instead of as read by SPIFFS_errno.
Parameters
config essential parts of the physical and logical configuration of the file system.
References spiffs_probe().
SPIFFS_read()
s32_t SPIFFS_read (spiffs * fs, spiffs_file fh, void * buf, s32_t len)
Reads from given filehandle.
Parameters
fs the file system struct
fh the filehandle
buf where to put read data
len how much to read
Returns
number of bytes read, or -1 if error
Referenced by unpackFile().
SPIFFS_readdir()
struct spiffs_dirent* SPIFFS_readdir (spiffs_DIR * d, struct spiffs_dirent * e)
Reads a directory into given spifs_dirent struct.
Parameters
d pointer to the directory stream
e the dirent struct to be populated
Returns
null if error or end of stream, else given dirent is returned
References spiffs_DIR::block, spiffs_DIR::entry, spiffs_t::err_code, spiffs_DIR::fs, SPIFFS_CHECK_MOUNT, SPIFFS_ERR_NOT_MOUNTED, SPIFFS_LOCK, spiffs_obj_lu_find_entry_visitor(), and SPIFFS_VIS_NO_WRAP.
Referenced by listFiles(), and unpackFiles().
SPIFFS_remove()
s32_t SPIFFS_remove (spiffs * fs, const char * path)
Removes a file by path
Parameters
fs the file system struct
path the path of the file to remove
References spiffs_fd::file_nbr, spiffs_dirent::pix, SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_API_CHECK_RES, SPIFFS_API_CHECK_RES_UNLOCK, SPIFFS_ERR_NAME_TOO_LONG, SPIFFS_ERR_RO_NOT_IMPL, spiffs_fd_find_new(), spiffs_fd_return(), SPIFFS_LOCK, SPIFFS_OBJ_NAME_LEN, spiffs_object_find_object_index_header_by_name(), spiffs_object_open_by_page(), spiffs_object_truncate(), SPIFFS_OK, and SPIFFS_UNLOCK.
SPIFFS_rename()
s32_t SPIFFS_rename (spiffs * fs, const char * old, const char * newPath)
Renames a file
Parameters
fs the file system struct
old path of file to rename
newPath new path of file
References spiffs_fd::file_nbr, spiffs_fd::obj_id, spiffs_fd::objix_hdr_pix, SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_API_CHECK_RES, SPIFFS_API_CHECK_RES_UNLOCK, SPIFFS_ERR_CONFLICTING_NAME, SPIFFS_ERR_NAME_TOO_LONG, SPIFFS_ERR_NOT_FOUND, SPIFFS_ERR_RO_NOT_IMPL, spiffs_fd_find_new(), spiffs_fd_return(), spiffs_fd_temporal_cache_rehash(), SPIFFS_LOCK, SPIFFS_OBJ_NAME_LEN, spiffs_object_find_object_index_header_by_name(), spiffs_object_open_by_page(), spiffs_object_update_index_hdr(), SPIFFS_OK, and SPIFFS_UNLOCK.
SPIFFS_set_file_callback_func()
s32_t SPIFFS_set_file_callback_func (spiffs * fs, spiffs_file_callback cb_func)
Registers a callback function that keeps track on operations on file headers. Do note, that this callback is called from within internal spiffs mechanisms. Any operations on the actual file system being callbacked from in this callback will mess things up for sure - do not do this. This can be used to track where files are and move around during garbage collection, which in turn can be used to build location tables in ram. Used in conjuction with SPIFFS_open_by_page this may improve performance when opening a lot of files. Must be invoked after mount.
Parameters
fs the file system struct
cb_func the callback on file operations
References spiffs_t::file_cb_f, SPIFFS_LOCK, and SPIFFS_UNLOCK.
SPIFFS_stat()
s32_t SPIFFS_stat (spiffs * fs, const char * path, spiffs_stat * s)
Gets file status by path
Parameters
fs the file system struct
path the path of the file to stat
s the stat struct to populate
References spiffs_dirent::pix, SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_API_CHECK_RES, SPIFFS_API_CHECK_RES_UNLOCK, SPIFFS_ERR_NAME_TOO_LONG, SPIFFS_LOCK, SPIFFS_OBJ_NAME_LEN, and spiffs_object_find_object_index_header_by_name().
SPIFFS_tell()
s32_t SPIFFS_tell (spiffs * fs, spiffs_file fh)
Get position in file.
Parameters
fs the file system struct
fh the filehandle of the file to check
References SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_API_CHECK_RES_UNLOCK, spiffs_fd_get(), SPIFFS_FH_UNOFFS, and SPIFFS_LOCK.
SPIFFS_unmount()
void SPIFFS_unmount (spiffs * fs)
Unmounts the file system. All file handles will be flushed of any cached writes and closed.
Parameters
fs the file system struct
References spiffs_t::fd_count, spiffs_t::fd_space, spiffs_fd::file_nbr, SPIFFS_CHECK_CFG, SPIFFS_CHECK_MOUNT, and SPIFFS_LOCK.
Referenced by spiffs_unmount(), spiffsFormat(), and spiffsUnmount().
SPIFFS_update_meta()
s32_t SPIFFS_update_meta (spiffs * fs, const char * name, const void * meta)
Updates file's metadata
Parameters
fs the file system struct
path path to the file
meta new metadata. must be SPIFFS_OBJ_META_LEN bytes long.
References spiffs_fd::file_nbr, spiffs_fd::obj_id, spiffs_fd::objix_hdr_pix, spiffs_dirent::pix, SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_API_CHECK_RES_UNLOCK, SPIFFS_ERR_RO_NOT_IMPL, spiffs_fd_find_new(), spiffs_fd_return(), SPIFFS_LOCK, spiffs_object_find_object_index_header_by_name(), spiffs_object_open_by_page(), spiffs_object_update_index_hdr(), SPIFFS_OK, and SPIFFS_UNLOCK.
Referenced by addDir(), and addFile().
SPIFFS_write()
s32_t SPIFFS_write (spiffs * fs, spiffs_file fh, void * buf, s32_t len)
Writes to given filehandle.
Parameters
fs the file system struct
fh the filehandle
buf the data to write
len how much to write
Returns
number of bytes written, or -1 if error
References _SPIPRIfd, _SPIPRIi, _SPIPRIid, _SPIPRIpg, spiffs_fd::fdoffset, spiffs_fd::file_nbr, spiffs_fd::flags, MAX, spiffs_fd::obj_id, spiffs_fd::offset, spiffs_fd::size, SPIFFS_API_CHECK_CFG, SPIFFS_API_CHECK_MOUNT, SPIFFS_API_CHECK_RES_UNLOCK, SPIFFS_CACHE_DBG, spiffs_cache_page_get_by_fd(), SPIFFS_CFG_LOG_PAGE_SZ, SPIFFS_ERR_NOT_WRITABLE, SPIFFS_ERR_RO_NOT_IMPL, spiffs_fd_get(), SPIFFS_FH_UNOFFS, SPIFFS_LOCK, SPIFFS_O_APPEND, SPIFFS_O_DIRECT, SPIFFS_O_WRONLY, and SPIFFS_UNDEFINED_LEN.
Referenced by addFile().