Projekt Ei: HardwareLife/Lcd/ESP32_TFT_library/components/tft/tft.c File Reference
tft.c File Reference
#include <stdio.h>
#include <errno.h>
#include <sys/stat.h>
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_system.h"
#include "tft.h"
#include "time.h"
#include <math.h>
#include "esp32/rom/tjpgd.h"
#include "esp_heap_caps.h"
#include "tftspi.h"
Classes
struct propFont
struct JPGIODEV
Macros
#define DEG_TO_RAD 0.01745329252
#define RAD_TO_DEG 57.295779513
#define deg_to_rad 0.01745329252 + 3.14159265359
#define swap(a, b) { int16_t t = a; a = b; b = t; }
#define constrain(amt, low, high) ((amt)<(low)?(low):((amt)>(high)?(high):(amt)))
#define max(A, B) ((A) > (B) ? (A):(B))
#define min(A, B) ((A) < (B) ? (A):(B))
Functions
int TFT_compare_colors (color_t c1, color_t c2)
void TFT_drawPixel (int16_t x, int16_t y, color_t color, uint8_t sel)
color_t TFT_readPixel (int16_t x, int16_t y)
void TFT_drawFastVLine (int16_t x, int16_t y, int16_t h, color_t color)
void TFT_drawFastHLine (int16_t x, int16_t y, int16_t w, color_t color)
void TFT_drawLine (int16_t x0, int16_t y0, int16_t x1, int16_t y1, color_t color)
void TFT_fillRect (int16_t x, int16_t y, int16_t w, int16_t h, color_t color)
void TFT_fillScreen (color_t color)
void TFT_fillWindow (color_t color)
void TFT_drawRect (uint16_t x1, uint16_t y1, uint16_t w, uint16_t h, color_t color)
void TFT_drawRoundRect (int16_t x, int16_t y, uint16_t w, uint16_t h, uint16_t r, color_t color)
void TFT_fillRoundRect (int16_t x, int16_t y, uint16_t w, uint16_t h, uint16_t r, color_t color)
void TFT_drawLineByAngle (uint16_t x, uint16_t y, uint16_t start, uint16_t len, uint16_t angle, color_t color)
void TFT_drawTriangle (uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, color_t color)
void TFT_fillTriangle (uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, color_t color)
void TFT_drawCircle (int16_t x, int16_t y, int radius, color_t color)
void TFT_fillCircle (int16_t x, int16_t y, int radius, color_t color)
void TFT_drawEllipse (uint16_t x0, uint16_t y0, uint16_t rx, uint16_t ry, color_t color, uint8_t option)
void TFT_fillEllipse (uint16_t x0, uint16_t y0, uint16_t rx, uint16_t ry, color_t color, uint8_t option)
void TFT_drawArc (uint16_t cx, uint16_t cy, uint16_t r, uint16_t th, float start, float end, color_t color, color_t fillcolor)
void TFT_drawPolygon (int cx, int cy, int sides, int diameter, color_t color, color_t fill, int rot, uint8_t th)
int compile_font_file (char *fontfile, uint8_t dbg)
void getFontCharacters (uint8_t *buf)
void TFT_setFont (uint8_t font, const char *font_file)
int TFT_getStringWidth (char *str)
void TFT_clearStringRect (int x, int y, char *str)
void TFT_print (char *st, int x, int y)
void TFT_setRotation (uint8_t rot)
void TFT_invertDisplay (const uint8_t mode)
void TFT_setGammaCurve (uint8_t gm)
color_t HSBtoRGB (float _hue, float _sat, float _brightness)
void TFT_setclipwin (uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2)
void TFT_resetclipwin ()
void set_7seg_font_atrib (uint8_t l, uint8_t w, int outline, color_t color)
int TFT_getfontsize (int *width, int *height)
int TFT_getfontheight ()
void TFT_saveClipWin ()
void TFT_restoreClipWin ()
void TFT_jpg_image (int x, int y, uint8_t scale, char *fname, uint8_t *buf, int size)
int TFT_bmp_image (int x, int y, uint8_t scale, char *fname, uint8_t *imgbuf, int size)
int TFT_read_touch (int *x, int *y, uint8_t raw)
Variables
uint8_t tft_SmallFont []
uint8_t tft_DefaultFont []
uint8_t tft_Dejavu18 []
uint8_t tft_Dejavu24 []
uint8_t tft_Ubuntu16 []
uint8_t tft_Comic24 []
uint8_t tft_minya24 []
uint8_t tft_tooney32 []
uint8_t tft_def_small []
const color_t TFT_BLACK = { 0, 0, 0 }
const color_t TFT_NAVY = { 0, 0, 128 }
const color_t TFT_DARKGREEN = { 0, 128, 0 }
const color_t TFT_DARKCYAN = { 0, 128, 128 }
const color_t TFT_MAROON = { 128, 0, 0 }
const color_t TFT_PURPLE = { 128, 0, 128 }
const color_t TFT_OLIVE = { 128, 128, 0 }
const color_t TFT_LIGHTGREY = { 192, 192, 192 }
const color_t TFT_DARKGREY = { 128, 128, 128 }
const color_t TFT_BLUE = { 0, 0, 255 }
const color_t TFT_GREEN = { 0, 255, 0 }
const color_t TFT_CYAN = { 0, 255, 255 }
const color_t TFT_RED = { 252, 0, 0 }
const color_t TFT_MAGENTA = { 252, 0, 255 }
const color_t TFT_YELLOW = { 252, 252, 0 }
const color_t TFT_WHITE = { 252, 252, 252 }
const color_t TFT_ORANGE = { 252, 164, 0 }
const color_t TFT_GREENYELLOW = { 172, 252, 44 }
const color_t TFT_PINK = { 252, 192, 202 }
uint8_t orientation = LANDSCAPE
uint16_t font_rotate = 0
uint8_t font_transparent = 0
uint8_t font_forceFixed = 0
uint8_t text_wrap = 0
color_t _fg = { 0, 255, 0}
color_t _bg = { 0, 0, 0}
uint8_t image_debug = 0
float _angleOffset = DEFAULT_ANGLE_OFFSET
int TFT_X = 0
int TFT_Y = 0
uint32_t tp_calx = 7472920
uint32_t tp_caly = 122224794
dispWin_t dispWin
Font cfont
uint8_t font_buffered_char = 1
uint8_t font_line_space = 0
Class Documentation
propFont
struct propFont
Class Members
int adjYOffset
uint8_t charCode
uint16_t dataPtr
int height
int width
int xDelta
int xOffset
JPGIODEV
struct JPGIODEV
Class Members
uint32_t bufptr
uint32_t bufsize
FILE * fhndl
color_t * linbuf[2]
uint8_t linbuf_idx
uint8_t * membuff
int x
int y
Macro Definition Documentation
constrain
#define constrain (amt, low, high) ((amt)<(low)?(low):((amt)>(high)?(high):(amt)))
DEG_TO_RAD
#define DEG_TO_RAD 0.01745329252
deg_to_rad
#define deg_to_rad 0.01745329252 + 3.14159265359
Referenced by TFT_drawPolygon().
max
#define max (A, B) ((A) > (B) ? (A):(B))
min
#define min (A, B) ((A) < (B) ? (A):(B))
RAD_TO_DEG
#define RAD_TO_DEG 57.295779513
swap
#define swap (a, b) { int16_t t = a; a = b; b = t; }
Function Documentation
compile_font_file()
int compile_font_file (char * fontfile, uint8_t dbg)
getFontCharacters()
void getFontCharacters (uint8_t * buf)
References Font::bitmap, Font::font, Font::numchars, Font::offset, and Font::x_size.
HSBtoRGB()
color_t HSBtoRGB (float _hue, float _sat, float _brightness)
References color_t.
set_7seg_font_atrib()
void set_7seg_font_atrib (uint8_t l, uint8_t w, int outline, color_t color)
References Font::bitmap, Font::color, Font::offset, w, Font::x_size, and Font::y_size.
TFT_bmp_image()
int TFT_bmp_image (int x, int y, uint8_t scale, char * fname, uint8_t * imgbuf, int size)
References BOTTOM, CENTER, color_t, disp_deselect(), disp_select(), image_debug, RIGHT, send_data(), spi_lobo_device_deselect(), spi_lobo_device_select(), touch_get_data(), ts_spi, wait_trans_finish(), dispWin_t::x1, dispWin_t::x2, dispWin_t::y1, and dispWin_t::y2.
TFT_clearStringRect()
void TFT_clearStringRect (int x, int y, char * str)
References _bg, TFT_fillRect(), TFT_getfontheight(), TFT_getStringWidth(), w, dispWin_t::x1, and dispWin_t::y1.
TFT_compare_colors()
int TFT_compare_colors (color_t c1, color_t c2)
Referenced by TFT_drawArc(), and TFT_drawPolygon().
TFT_drawArc()
void TFT_drawArc (uint16_t cx, uint16_t cy, uint16_t r, uint16_t th, float start, float end, color_t color, color_t fillcolor)
References r, TFT_compare_colors(), dispWin_t::x1, and dispWin_t::y1.
TFT_drawCircle()
void TFT_drawCircle (int16_t x, int16_t y, int radius, color_t color)
References disp_select(), dispWin_t::x1, and dispWin_t::y1.
TFT_drawEllipse()
void TFT_drawEllipse (uint16_t x0, uint16_t y0, uint16_t rx, uint16_t ry, color_t color, uint8_t option)
References dispWin_t::x1, and dispWin_t::y1.
TFT_drawFastHLine()
void TFT_drawFastHLine (int16_t x, int16_t y, int16_t w, color_t color)
TFT_drawFastVLine()
void TFT_drawFastVLine (int16_t x, int16_t y, int16_t h, color_t color)
TFT_drawLine()
void TFT_drawLine (int16_t x0, int16_t y0, int16_t x1, int16_t y1, color_t color)
TFT_drawLineByAngle()
void TFT_drawLineByAngle (uint16_t x, uint16_t y, uint16_t start, uint16_t len, uint16_t angle, color_t color)
References dispWin_t::x1, and dispWin_t::y1.
TFT_drawPixel()
void TFT_drawPixel (int16_t x, int16_t y, color_t color, uint8_t sel)
TFT_drawPolygon()
void TFT_drawPolygon (int cx, int cy, int sides, int diameter, color_t color, color_t fill, int rot, uint8_t th)
References _angleOffset, deg_to_rad, MAX_POLIGON_SIDES, MIN_POLIGON_SIDES, TFT_compare_colors(), dispWin_t::x1, and dispWin_t::y1.
TFT_drawRect()
void TFT_drawRect (uint16_t x1, uint16_t y1, uint16_t w, uint16_t h, color_t color)
TFT_drawRoundRect()
void TFT_drawRoundRect (int16_t x, int16_t y, uint16_t w, uint16_t h, uint16_t r, color_t color)
References dispWin_t::x1, and dispWin_t::y1.
TFT_drawTriangle()
void TFT_drawTriangle (uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, color_t color)
References dispWin_t::x1, and dispWin_t::y1.
TFT_fillCircle()
void TFT_fillCircle (int16_t x, int16_t y, int radius, color_t color)
References dispWin_t::x1, and dispWin_t::y1.
Referenced by Face::smile().
TFT_fillEllipse()
void TFT_fillEllipse (uint16_t x0, uint16_t y0, uint16_t rx, uint16_t ry, color_t color, uint8_t option)
References dispWin_t::x1, and dispWin_t::y1.
TFT_fillRect()
void TFT_fillRect (int16_t x, int16_t y, int16_t w, int16_t h, color_t color)
Referenced by TFT_clearStringRect().
TFT_fillRoundRect()
void TFT_fillRoundRect (int16_t x, int16_t y, uint16_t w, uint16_t h, uint16_t r, color_t color)
References dispWin_t::x1, and dispWin_t::y1.
TFT_fillScreen()
void TFT_fillScreen (color_t color)
References _height, _width, and TFT_pushColorRep().
Referenced by TFT_setRotation().
TFT_fillTriangle()
void TFT_fillTriangle (uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, color_t color)
TFT_fillWindow()
void TFT_fillWindow (color_t color)
References TFT_pushColorRep(), dispWin_t::x1, dispWin_t::x2, dispWin_t::y1, and dispWin_t::y2.
Referenced by Face::Face().
TFT_getfontheight()
int TFT_getfontheight ()
References Font::bitmap, and Font::y_size.
Referenced by TFT_clearStringRect().
TFT_getfontsize()
int TFT_getfontsize (int * width, int * height)
References Font::bitmap, Font::max_x_size, Font::x_size, and Font::y_size.
TFT_getStringWidth()
int TFT_getStringWidth (char * str)
References Font::bitmap.
Referenced by TFT_clearStringRect().
TFT_invertDisplay()
void TFT_invertDisplay (const uint8_t mode)
References disp_spi_transfer_cmd(), INVERT_ON, TFT_INVOFF, and TFT_INVONN.
Referenced by TftDisplayBackend().
TFT_jpg_image()
void TFT_jpg_image (int x, int y, uint8_t scale, char * fname, uint8_t * buf, int size)
References JPGIODEV::bufptr, JPGIODEV::bufsize, JPGIODEV::fhndl, image_debug, JPGIODEV::linbuf, JPGIODEV::linbuf_idx, and JPGIODEV::membuff.
TFT_print()
void TFT_print (char * st, int x, int y)
References Font::bitmap, CENTER, font_rotate, and LASTX.
Referenced by TopLine::print().
TFT_read_touch()
int TFT_read_touch (int * x, int * y, uint8_t raw)
References _height, _width, LANDSCAPE, LANDSCAPE_FLIP, orientation, PORTRAIT, PORTRAIT_FLIP, stmpe610_get_touch(), tp_calx, TP_CALX_STMPE610, TP_CALX_XPT2046, tp_caly, TP_CALY_STMPE610, TP_CALY_XPT2046, and ts_spi.
TFT_readPixel()
color_t TFT_readPixel (int16_t x, int16_t y)
References readPixel(), TFT_BLACK, dispWin_t::x1, dispWin_t::x2, dispWin_t::y1, and dispWin_t::y2.
TFT_resetclipwin()
void TFT_resetclipwin ()
References _height, _width, dispWin_t::x1, dispWin_t::x2, dispWin_t::y1, and dispWin_t::y2.
Referenced by app_main(), and tft_demo().
TFT_restoreClipWin()
void TFT_restoreClipWin ()
References dispWin_t::x1, dispWin_t::x2, dispWin_t::y1, and dispWin_t::y2.
TFT_saveClipWin()
void TFT_saveClipWin ()
References dispWin_t::x1, dispWin_t::x2, dispWin_t::y1, and dispWin_t::y2.
TFT_setclipwin()
void TFT_setclipwin (uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2)
References _height, _width, dispWin_t::x1, dispWin_t::x2, dispWin_t::y1, and dispWin_t::y2.
TFT_setFont()
void TFT_setFont (uint8_t font, const char * font_file)
References _fg, Font::bitmap, Font::color, Font::font, FONT_7SEG, Font::offset, USER_FONT, Font::x_size, and Font::y_size.
Referenced by app_main(), TopLine::print(), and TftDisplayBackend().
TFT_setGammaCurve()
void TFT_setGammaCurve (uint8_t gm)
References disp_spi_transfer_cmd_data(), and TFT_CMD_GAMMASET.
Referenced by app_main().
TFT_setRotation()
void TFT_setRotation (uint8_t rot)
References _bg, _height, _tft_setRotation(), _width, disp_deselect(), disp_select(), disp_spi_transfer_cmd_data(), orientation, TFT_fillScreen(), TFT_MADCTL, dispWin_t::x1, dispWin_t::x2, dispWin_t::y1, and dispWin_t::y2.
Referenced by app_main(), and TftDisplayBackend().
Variable Documentation
_angleOffset
float _angleOffset = DEFAULT_ANGLE_OFFSET
Referenced by TFT_drawPolygon().
_bg
color_t _bg = { 0, 0, 0}
Referenced by TFT_clearStringRect(), and TFT_setRotation().
_fg
color_t _fg = { 0, 255, 0}
Referenced by TopLine::print(), and TFT_setFont().
cfont
Font cfont
Initial value:
= {
    .font = tft_DefaultFont,
    .x_size = 0,
    .y_size = 0x0B,
    .offset = 0,
    .numchars = 95,
    .bitmap = 1,
}
dispWin
dispWin_t dispWin
Initial value:
= {
  .x1 = 0,
  .y1 = 0,
  .x2 = DEFAULT_TFT_DISPLAY_WIDTH,
  .y2 = DEFAULT_TFT_DISPLAY_HEIGHT,
}
font_buffered_char
uint8_t font_buffered_char = 1
font_forceFixed
uint8_t font_forceFixed = 0
Referenced by app_main(), and tft_demo().
font_line_space
uint8_t font_line_space = 0
font_rotate
uint16_t font_rotate = 0
Referenced by app_main(), tft_demo(), and TFT_print().
font_transparent
uint8_t font_transparent = 0
Referenced by app_main(), and tft_demo().
image_debug
uint8_t image_debug = 0
Referenced by TFT_bmp_image(), tft_demo(), and TFT_jpg_image().
orientation
uint8_t orientation = LANDSCAPE
Referenced by TFT_read_touch(), and TFT_setRotation().
text_wrap
uint8_t text_wrap = 0
Referenced by app_main(), and tft_demo().
TFT_BLACK
const color_t TFT_BLACK = { 0, 0, 0 }
Referenced by Face::Face(), TopLine::print(), Face::smile(), and TFT_readPixel().
TFT_BLUE
const color_t TFT_BLUE = { 0, 0, 255 }
tft_Comic24
uint8_t tft_Comic24[]
TFT_CYAN
const color_t TFT_CYAN = { 0, 255, 255 }
TFT_DARKCYAN
const color_t TFT_DARKCYAN = { 0, 128, 128 }
TFT_DARKGREEN
const color_t TFT_DARKGREEN = { 0, 128, 0 }
TFT_DARKGREY
const color_t TFT_DARKGREY = { 128, 128, 128 }
tft_def_small
uint8_t tft_def_small[]
tft_DefaultFont
uint8_t tft_DefaultFont[]
tft_Dejavu18
uint8_t tft_Dejavu18[]
tft_Dejavu24
uint8_t tft_Dejavu24[]
TFT_GREEN
const color_t TFT_GREEN = { 0, 255, 0 }
TFT_GREENYELLOW
const color_t TFT_GREENYELLOW = { 172, 252, 44 }
TFT_LIGHTGREY
const color_t TFT_LIGHTGREY = { 192, 192, 192 }
TFT_MAGENTA
const color_t TFT_MAGENTA = { 252, 0, 255 }
TFT_MAROON
const color_t TFT_MAROON = { 128, 0, 0 }
tft_minya24
uint8_t tft_minya24[]
TFT_NAVY
const color_t TFT_NAVY = { 0, 0, 128 }
TFT_OLIVE
const color_t TFT_OLIVE = { 128, 128, 0 }
Referenced by TopLine::print().
TFT_ORANGE
const color_t TFT_ORANGE = { 252, 164, 0 }
TFT_PINK
const color_t TFT_PINK = { 252, 192, 202 }
TFT_PURPLE
const color_t TFT_PURPLE = { 128, 0, 128 }
TFT_RED
const color_t TFT_RED = { 252, 0, 0 }
tft_SmallFont
uint8_t tft_SmallFont[]
tft_tooney32
uint8_t tft_tooney32[]
tft_Ubuntu16
uint8_t tft_Ubuntu16[]
TFT_WHITE
const color_t TFT_WHITE = { 252, 252, 252 }
Referenced by Face::smile().
TFT_X
int TFT_X = 0
TFT_Y
int TFT_Y = 0
TFT_YELLOW
const color_t TFT_YELLOW = { 252, 252, 0 }
tp_calx
uint32_t tp_calx = 7472920
Referenced by TFT_read_touch().
tp_caly
uint32_t tp_caly = 122224794
Referenced by TFT_read_touch().