Projekt Ei: HardwareLife/Lcd/ESP32_TFT_library/main/tft_demo.c File Reference
tft_demo.c File Reference
#include <time.h>
#include <errno.h>
#include <sys/fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_system.h"
#include "driver/gpio.h"
#include "esp_heap_caps.h"
#include "tftspi.h"
#include "tft.h"
#include "spiffs_vfs.h"
Macros
#define SPI_BUS TFT_HSPI_HOST
#define GDEMO_TIME 1000
#define GDEMO_INFO_TIME 5000
Functions
void tft_demo ()
void app_main ()
Macro Definition Documentation
GDEMO_INFO_TIME
#define GDEMO_INFO_TIME 5000
GDEMO_TIME
#define GDEMO_TIME 1000
SPI_BUS
#define SPI_BUS TFT_HSPI_HOST
Referenced by app_main().
Function Documentation
app_main()
void app_main (void)
References _height, _width, spi_lobo_device_interface_config_t::clock_speed_hz, DEFAULT_DISP_TYPE, DEFAULT_FONT, DEFAULT_GAMMA_CURVE, DEFAULT_SPI_CLOCK, DEFAULT_TFT_DISPLAY_HEIGHT, DEFAULT_TFT_DISPLAY_WIDTH, disp_spi, ESP_ERROR_CHECK, find_rd_speed(), font_forceFixed, font_rotate, font_transparent, gray_scale, LB_SPI_DEVICE_HALFDUPLEX, max_rdclock, spi_lobo_bus_config_t::miso_io_num, PIN_NUM_CLK, PIN_NUM_CS, PIN_NUM_MISO, PIN_NUM_MOSI, PIN_NUM_TCS, PORTRAIT, SPI_BUS, spi_lobo_bus_add_device(), spi_lobo_device_deselect(), spi_lobo_device_select(), spi_lobo_get_speed(), spi_lobo_set_speed(), spi_lobo_uses_native_pins(), stmpe610_getID(), stmpe610_Init(), STMPE610_SPI_MODE, text_wrap, tft_disp_type, TFT_display_init(), TFT_PinsInit(), TFT_resetclipwin(), TFT_setFont(), TFT_setGammaCurve(), TFT_setRotation(), and ts_spi.
tft_demo()
void tft_demo ()
References DISP_TYPE_ILI9341, DISP_TYPE_ILI9488, DISP_TYPE_ST7735, DISP_TYPE_ST7735B, DISP_TYPE_ST7735R, DISP_TYPE_ST7789V, font_forceFixed, font_rotate, font_transparent, image_debug, PORTRAIT, text_wrap, tft_disp_type, and TFT_resetclipwin().