Projekt Ei: HardwareLife/Lcd/ESP32_TFT_library/components/tft/tftspi.c File Reference
tftspi.c File Reference
#include <string.h>
#include "driver/gpio.h"
#include "tftspi.h"
#include "esp_system.h"
#include "freertos/task.h"
#include "esp_heap_caps.h"
#include "soc/spi_reg.h"
Macros
#define GS_FACT_R 0.2989
#define GS_FACT_G 0.4870
#define GS_FACT_B 0.2140
Functions
esp_err_t IRAM_ATTR wait_trans_finish (uint8_t free_line)
esp_err_t IRAM_ATTR disp_select ()
esp_err_t IRAM_ATTR disp_deselect ()
void IRAM_ATTR disp_spi_transfer_cmd (int8_t cmd)
void IRAM_ATTR disp_spi_transfer_cmd_data (int8_t cmd, uint8_t *data, uint32_t len)
void IRAM_ATTR drawPixel (int16_t x, int16_t y, color_t color, uint8_t sel)
void IRAM_ATTR TFT_pushColorRep (int x1, int y1, int x2, int y2, color_t color, uint32_t len)
void IRAM_ATTR send_data (int x1, int y1, int x2, int y2, uint32_t len, color_t *buf)
int IRAM_ATTR read_data (int x1, int y1, int x2, int y2, int len, uint8_t *buf, uint8_t set_sp)
color_t IRAM_ATTR readPixel (int16_t x, int16_t y)
int IRAM_ATTR touch_get_data (uint8_t type)
uint32_t stmpe610_getID ()
void stmpe610_Init ()
int stmpe610_get_touch (uint16_t *x, uint16_t *y, uint16_t *z)
uint32_t find_rd_speed ()
void _tft_setRotation (uint8_t rot)
void TFT_PinsInit ()
void TFT_display_init ()
Variables
uint8_t gray_scale = 0
uint32_t max_rdclock = 8000000
int _width = DEFAULT_TFT_DISPLAY_WIDTH
int _height = DEFAULT_TFT_DISPLAY_HEIGHT
uint8_t tft_disp_type = DISP_TYPE_ILI9341
spi_lobo_device_handle_t disp_spi = NULL
spi_lobo_device_handle_t ts_spi = NULL
Macro Definition Documentation
GS_FACT_B
#define GS_FACT_B 0.2140
GS_FACT_G
#define GS_FACT_G 0.4870
GS_FACT_R
#define GS_FACT_R 0.2989
Function Documentation
_tft_setRotation()
void _tft_setRotation (uint8_t rot)
References _height, _width, disp_deselect(), disp_select(), disp_spi_transfer_cmd_data(), LANDSCAPE, LANDSCAPE_FLIP, MADCTL_MV, MADCTL_MX, MADCTL_MY, PORTRAIT, PORTRAIT_FLIP, TFT_MADCTL, and TFT_RGB_BGR.
Referenced by TFT_setRotation().
disp_deselect()
esp_err_t IRAM_ATTR disp_deselect ()
References spi_lobo_device_deselect(), and wait_trans_finish().
Referenced by _tft_setRotation(), find_rd_speed(), read_data(), TFT_bmp_image(), and TFT_setRotation().
disp_select()
esp_err_t IRAM_ATTR disp_select ()
References spi_lobo_device_select(), and wait_trans_finish().
Referenced by _tft_setRotation(), drawPixel(), find_rd_speed(), read_data(), TFT_bmp_image(), TFT_display_init(), TFT_drawCircle(), TFT_pushColorRep(), and TFT_setRotation().
disp_spi_transfer_cmd()
void IRAM_ATTR disp_spi_transfer_cmd (int8_t cmd)
References spi_lobo_device_t::host, spi_lobo_host_t::hw, and PIN_NUM_DC.
Referenced by TFT_invertDisplay().
disp_spi_transfer_cmd_data()
void IRAM_ATTR disp_spi_transfer_cmd_data (int8_t cmd, uint8_t * data, uint32_t len)
References spi_lobo_device_t::host, spi_lobo_host_t::hw, and PIN_NUM_DC.
Referenced by _tft_setRotation(), TFT_setGammaCurve(), and TFT_setRotation().
drawPixel()
void IRAM_ATTR drawPixel (int16_t x, int16_t y, color_t color, uint8_t sel)
References spi_lobo_device_t::cfg, color_t, disp_select(), spi_lobo_device_interface_config_t::flags, gray_scale, LB_SPI_DEVICE_HALFDUPLEX, and wait_trans_finish().
find_rd_speed()
uint32_t find_rd_speed ()
References _height, _width, color_t, disp_deselect(), disp_select(), gray_scale, r, read_data(), send_data(), spi_lobo_get_speed(), and spi_lobo_set_speed().
Referenced by app_main(), and TftDisplayBackend().
read_data()
int IRAM_ATTR read_data (int x1, int y1, int x2, int y2, int len, uint8_t * buf, uint8_t set_sp)
References color_t, disp_deselect(), disp_select(), max_rdclock, spi_lobo_get_speed(), and spi_lobo_set_speed().
Referenced by find_rd_speed(), and readPixel().
readPixel()
color_t IRAM_ATTR readPixel (int16_t x, int16_t y)
References color_t, and read_data().
Referenced by TFT_readPixel().
send_data()
void IRAM_ATTR send_data (int x1, int y1, int x2, int y2, uint32_t len, color_t * buf)
Referenced by find_rd_speed(), and TFT_bmp_image().
stmpe610_get_touch()
int stmpe610_get_touch (uint16_t * x, uint16_t * y, uint16_t * z)
Referenced by TFT_read_touch().
stmpe610_getID()
uint32_t stmpe610_getID ()
Referenced by app_main().
stmpe610_Init()
void stmpe610_Init ()
Referenced by app_main().
TFT_display_init()
void TFT_display_init ()
Enable backlight
References disp_select(), DISP_TYPE_ILI9341, PIN_NUM_RST, and tft_disp_type.
Referenced by app_main(), and TftDisplayBackend().
TFT_PinsInit()
void TFT_PinsInit ()
References PIN_BCKL_OFF, PIN_NUM_BCKL, PIN_NUM_CLK, PIN_NUM_CS, PIN_NUM_DC, PIN_NUM_MISO, PIN_NUM_MOSI, PIN_NUM_RST, and PIN_NUM_TCS.
Referenced by app_main(), and TftDisplayBackend().
TFT_pushColorRep()
void IRAM_ATTR TFT_pushColorRep (int x1, int y1, int x2, int y2, color_t color, uint32_t len)
References disp_select().
Referenced by TFT_fillScreen(), and TFT_fillWindow().
touch_get_data()
int IRAM_ATTR touch_get_data (uint8_t type)
References spi_lobo_device_t::host, spi_lobo_host_t::hw, and spi_lobo_device_select().
Referenced by TFT_bmp_image().
wait_trans_finish()
esp_err_t IRAM_ATTR wait_trans_finish (uint8_t free_line)
References spi_lobo_device_t::host, and spi_lobo_host_t::hw.
Referenced by disp_deselect(), disp_select(), drawPixel(), and TFT_bmp_image().
Variable Documentation
_height
int _height = DEFAULT_TFT_DISPLAY_HEIGHT
Referenced by _tft_setRotation(), app_main(), find_rd_speed(), TFT_fillScreen(), TFT_read_touch(), TFT_resetclipwin(), TFT_setclipwin(), and TFT_setRotation().
_width
int _width = DEFAULT_TFT_DISPLAY_WIDTH
Referenced by _tft_setRotation(), app_main(), find_rd_speed(), TFT_fillScreen(), TFT_read_touch(), TFT_resetclipwin(), TFT_setclipwin(), and TFT_setRotation().
disp_spi
spi_lobo_device_handle_t disp_spi = NULL
Referenced by app_main().
gray_scale
uint8_t gray_scale = 0
Referenced by app_main(), drawPixel(), and find_rd_speed().
max_rdclock
uint32_t max_rdclock = 8000000
Referenced by app_main(), read_data(), and TftDisplayBackend().
tft_disp_type
uint8_t tft_disp_type = DISP_TYPE_ILI9341
Referenced by app_main(), tft_demo(), and TFT_display_init().
ts_spi
spi_lobo_device_handle_t ts_spi = NULL
Referenced by app_main(), TFT_bmp_image(), and TFT_read_touch().