Projekt Ei: HardwareLife/Lcd/ESP32_TFT_library/components/tft/tftspi.h File Reference
tftspi.h File Reference
#include "spi_master_lobo.h"
#include "sdkconfig.h"
#include "stmpe610.h"
Macros
#define TOUCH_TYPE_NONE 0
#define TOUCH_TYPE_XPT2046 1
#define TOUCH_TYPE_STMPE610 2
#define TP_CALX_XPT2046 7472920
#define TP_CALY_XPT2046 122224794
#define TP_CALX_STMPE610 21368532
#define TP_CALY_STMPE610 11800144
#define PORTRAIT 0
#define LANDSCAPE 1
#define PORTRAIT_FLIP 2
#define LANDSCAPE_FLIP 3
#define DISP_TYPE_ILI9341 0
#define DISP_TYPE_ILI9488 1
#define DISP_TYPE_ST7789V 2
#define DISP_TYPE_ST7735 3
#define DISP_TYPE_ST7735R 4
#define DISP_TYPE_ST7735B 5
#define DISP_TYPE_MAX 6
#define DEFAULT_DISP_TYPE DISP_TYPE_ILI9341
#define DEFAULT_TFT_DISPLAY_WIDTH 320
#define DEFAULT_TFT_DISPLAY_HEIGHT 240
#define DISP_COLOR_BITS_24 0x66
#define DEFAULT_GAMMA_CURVE 0
#define DEFAULT_SPI_CLOCK 26000000
#define TFT_INVERT_ROTATION 0
#define TFT_INVERT_ROTATION1 0
#define TFT_INVERT_ROTATION2 1
#define TFT_RGB_BGR 0x08
#define USE_TOUCH TOUCH_TYPE_NONE
#define PIN_NUM_MISO 19
#define PIN_NUM_MOSI 23
#define PIN_NUM_CLK 18
#define PIN_NUM_CS 14
#define PIN_NUM_DC 27
#define PIN_NUM_TCS 0
#define PIN_NUM_RST 33
#define PIN_NUM_BCKL 32
#define PIN_BCKL_ON 1
#define PIN_BCKL_OFF 0
#define TFT_INVOFF 0x20
#define TFT_INVONN 0x21
#define TFT_DISPOFF 0x28
#define TFT_DISPON 0x29
#define TFT_MADCTL 0x36
#define TFT_PTLAR 0x30
#define TFT_ENTRYM 0xB7
#define TFT_CMD_NOP 0x00
#define TFT_CMD_SWRESET 0x01
#define TFT_CMD_RDDID 0x04
#define TFT_CMD_RDDST 0x09
#define TFT_CMD_SLPIN 0x10
#define TFT_CMD_SLPOUT 0x11
#define TFT_CMD_PTLON 0x12
#define TFT_CMD_NORON 0x13
#define TFT_CMD_RDMODE 0x0A
#define TFT_CMD_RDMADCTL 0x0B
#define TFT_CMD_RDPIXFMT 0x0C
#define TFT_CMD_RDIMGFMT 0x0D
#define TFT_CMD_RDSELFDIAG 0x0F
#define TFT_CMD_GAMMASET 0x26
#define TFT_CMD_FRMCTR1 0xB1
#define TFT_CMD_FRMCTR2 0xB2
#define TFT_CMD_FRMCTR3 0xB3
#define TFT_CMD_INVCTR 0xB4
#define TFT_CMD_DFUNCTR 0xB6
#define TFT_CMD_PWCTR1 0xC0
#define TFT_CMD_PWCTR2 0xC1
#define TFT_CMD_PWCTR3 0xC2
#define TFT_CMD_PWCTR4 0xC3
#define TFT_CMD_PWCTR5 0xC4
#define TFT_CMD_VMCTR1 0xC5
#define TFT_CMD_VMCTR2 0xC7
#define TFT_CMD_RDID1 0xDA
#define TFT_CMD_RDID2 0xDB
#define TFT_CMD_RDID3 0xDC
#define TFT_CMD_RDID4 0xDD
#define TFT_CMD_GMCTRP1 0xE0
#define TFT_CMD_GMCTRN1 0xE1
#define TFT_CMD_POWERA 0xCB
#define TFT_CMD_POWERB 0xCF
#define TFT_CMD_POWER_SEQ 0xED
#define TFT_CMD_DTCA 0xE8
#define TFT_CMD_DTCB 0xEA
#define TFT_CMD_PRC 0xF7
#define TFT_CMD_3GAMMA_EN 0xF2
#define ST_CMD_VCOMS 0xBB
#define ST_CMD_FRCTRL2 0xC6
#define ST_CMD_PWCTR1 0xD0
#define ST7735_FRMCTR1 0xB1
#define ST7735_FRMCTR2 0xB2
#define ST7735_FRMCTR3 0xB3
#define ST7735_INVCTR 0xB4
#define ST7735_DISSET5 0xB6
#define ST7735_PWCTR1 0xC0
#define ST7735_PWCTR2 0xC1
#define ST7735_PWCTR3 0xC2
#define ST7735_PWCTR4 0xC3
#define ST7735_PWCTR5 0xC4
#define ST7735_VMCTR1 0xC5
#define ST7735_RDID1 0xDA
#define ST7735_RDID2 0xDB
#define ST7735_RDID3 0xDC
#define ST7735_RDID4 0xDD
#define ST7735_NOP 0x00
#define ST7735_SWRESET 0x01
#define ST7735_RDDID 0x04
#define ST7735_RDDST 0x09
#define ST7735_SLPIN 0x10
#define ST7735_SLPOUT 0x11
#define ST7735_PTLON 0x12
#define ST7735_NORON 0x13
#define ST7735_PWCTR6 0xFC
#define ST7735_GMCTRP1 0xE0
#define ST7735_GMCTRN1 0xE1
#define MADCTL_MY 0x80
#define MADCTL_MX 0x40
#define MADCTL_MV 0x20
#define MADCTL_ML 0x10
#define MADCTL_MH 0x04
#define TFT_CASET 0x2A
#define TFT_PASET 0x2B
#define TFT_RAMWR 0x2C
#define TFT_RAMRD 0x2E
#define TFT_CMD_PIXFMT 0x3A
#define TFT_CMD_DELAY 0x80
Functions
struct __attribute__ ((__packed__))
esp_err_t wait_trans_finish (uint8_t free_line)
void disp_spi_transfer_cmd (int8_t cmd)
void disp_spi_transfer_cmd_data (int8_t cmd, uint8_t *data, uint32_t len)
void drawPixel (int16_t x, int16_t y, color_t color, uint8_t sel)
void send_data (int x1, int y1, int x2, int y2, uint32_t len, color_t *buf)
void TFT_pushColorRep (int x1, int y1, int x2, int y2, color_t data, uint32_t len)
int read_data (int x1, int y1, int x2, int y2, int len, uint8_t *buf, uint8_t set_sp)
color_t readPixel (int16_t x, int16_t y)
int touch_get_data (uint8_t type)
esp_err_t disp_deselect ()
esp_err_t disp_select ()
uint32_t find_rd_speed ()
void _tft_setRotation (uint8_t rot)
void TFT_PinsInit ()
void TFT_display_init ()
void stmpe610_Init ()
int stmpe610_get_touch (uint16_t *x, uint16_t *y, uint16_t *z)
uint32_t stmpe610_getID ()
Variables
uint8_t gray_scale
uint32_t max_rdclock
int _width
int _height
uint8_t tft_disp_type
spi_lobo_device_handle_t disp_spi
spi_lobo_device_handle_t ts_spi
color_t
Macro Definition Documentation
DEFAULT_DISP_TYPE
#define DEFAULT_DISP_TYPE DISP_TYPE_ILI9341
DEFAULT_GAMMA_CURVE
#define DEFAULT_GAMMA_CURVE 0
DEFAULT_SPI_CLOCK
#define DEFAULT_SPI_CLOCK 26000000
DEFAULT_TFT_DISPLAY_HEIGHT
#define DEFAULT_TFT_DISPLAY_HEIGHT 240
DEFAULT_TFT_DISPLAY_WIDTH
#define DEFAULT_TFT_DISPLAY_WIDTH 320
DISP_COLOR_BITS_24
#define DISP_COLOR_BITS_24 0x66
DISP_TYPE_ILI9341
#define DISP_TYPE_ILI9341 0
DISP_TYPE_ILI9488
#define DISP_TYPE_ILI9488 1
Referenced by tft_demo().
DISP_TYPE_MAX
#define DISP_TYPE_MAX 6
DISP_TYPE_ST7735
#define DISP_TYPE_ST7735 3
Referenced by tft_demo().
DISP_TYPE_ST7735B
#define DISP_TYPE_ST7735B 5
Referenced by tft_demo().
DISP_TYPE_ST7735R
#define DISP_TYPE_ST7735R 4
Referenced by tft_demo().
DISP_TYPE_ST7789V
#define DISP_TYPE_ST7789V 2
Referenced by tft_demo().
LANDSCAPE
#define LANDSCAPE 1
LANDSCAPE_FLIP
#define LANDSCAPE_FLIP 3
MADCTL_MH
#define MADCTL_MH 0x04
MADCTL_ML
#define MADCTL_ML 0x10
MADCTL_MV
#define MADCTL_MV 0x20
MADCTL_MX
#define MADCTL_MX 0x40
MADCTL_MY
#define MADCTL_MY 0x80
PIN_BCKL_OFF
#define PIN_BCKL_OFF 0
Referenced by TFT_PinsInit().
PIN_BCKL_ON
#define PIN_BCKL_ON 1
PIN_NUM_BCKL
#define PIN_NUM_BCKL 32
PIN_NUM_CLK
#define PIN_NUM_CLK 18
Referenced by app_main(), and TFT_PinsInit().
PIN_NUM_CS
#define PIN_NUM_CS 14
Referenced by app_main(), and TFT_PinsInit().
PIN_NUM_DC
#define PIN_NUM_DC 27
Referenced by disp_spi_transfer_cmd(), disp_spi_transfer_cmd_data(), and TFT_PinsInit().
PIN_NUM_MISO
#define PIN_NUM_MISO 19
Referenced by app_main(), and TFT_PinsInit().
PIN_NUM_MOSI
#define PIN_NUM_MOSI 23
Referenced by app_main(), and TFT_PinsInit().
PIN_NUM_RST
#define PIN_NUM_RST 33
Referenced by TFT_display_init(), and TFT_PinsInit().
PIN_NUM_TCS
#define PIN_NUM_TCS 0
Referenced by app_main(), and TFT_PinsInit().
PORTRAIT
#define PORTRAIT 0
PORTRAIT_FLIP
#define PORTRAIT_FLIP 2
ST7735_DISSET5
#define ST7735_DISSET5 0xB6
ST7735_FRMCTR1
#define ST7735_FRMCTR1 0xB1
ST7735_FRMCTR2
#define ST7735_FRMCTR2 0xB2
ST7735_FRMCTR3
#define ST7735_FRMCTR3 0xB3
ST7735_GMCTRN1
#define ST7735_GMCTRN1 0xE1
ST7735_GMCTRP1
#define ST7735_GMCTRP1 0xE0
ST7735_INVCTR
#define ST7735_INVCTR 0xB4
ST7735_NOP
#define ST7735_NOP 0x00
ST7735_NORON
#define ST7735_NORON 0x13
ST7735_PTLON
#define ST7735_PTLON 0x12
ST7735_PWCTR1
#define ST7735_PWCTR1 0xC0
ST7735_PWCTR2
#define ST7735_PWCTR2 0xC1
ST7735_PWCTR3
#define ST7735_PWCTR3 0xC2
ST7735_PWCTR4
#define ST7735_PWCTR4 0xC3
ST7735_PWCTR5
#define ST7735_PWCTR5 0xC4
ST7735_PWCTR6
#define ST7735_PWCTR6 0xFC
ST7735_RDDID
#define ST7735_RDDID 0x04
ST7735_RDDST
#define ST7735_RDDST 0x09
ST7735_RDID1
#define ST7735_RDID1 0xDA
ST7735_RDID2
#define ST7735_RDID2 0xDB
ST7735_RDID3
#define ST7735_RDID3 0xDC
ST7735_RDID4
#define ST7735_RDID4 0xDD
ST7735_SLPIN
#define ST7735_SLPIN 0x10
ST7735_SLPOUT
#define ST7735_SLPOUT 0x11
ST7735_SWRESET
#define ST7735_SWRESET 0x01
ST7735_VMCTR1
#define ST7735_VMCTR1 0xC5
ST_CMD_FRCTRL2
#define ST_CMD_FRCTRL2 0xC6
ST_CMD_PWCTR1
#define ST_CMD_PWCTR1 0xD0
ST_CMD_VCOMS
#define ST_CMD_VCOMS 0xBB
TFT_CASET
#define TFT_CASET 0x2A
TFT_CMD_3GAMMA_EN
#define TFT_CMD_3GAMMA_EN 0xF2
TFT_CMD_DELAY
#define TFT_CMD_DELAY 0x80
TFT_CMD_DFUNCTR
#define TFT_CMD_DFUNCTR 0xB6
TFT_CMD_DTCA
#define TFT_CMD_DTCA 0xE8
TFT_CMD_DTCB
#define TFT_CMD_DTCB 0xEA
TFT_CMD_FRMCTR1
#define TFT_CMD_FRMCTR1 0xB1
TFT_CMD_FRMCTR2
#define TFT_CMD_FRMCTR2 0xB2
TFT_CMD_FRMCTR3
#define TFT_CMD_FRMCTR3 0xB3
TFT_CMD_GAMMASET
#define TFT_CMD_GAMMASET 0x26
TFT_CMD_GMCTRN1
#define TFT_CMD_GMCTRN1 0xE1
TFT_CMD_GMCTRP1
#define TFT_CMD_GMCTRP1 0xE0
TFT_CMD_INVCTR
#define TFT_CMD_INVCTR 0xB4
TFT_CMD_NOP
#define TFT_CMD_NOP 0x00
TFT_CMD_NORON
#define TFT_CMD_NORON 0x13
TFT_CMD_PIXFMT
#define TFT_CMD_PIXFMT 0x3A
TFT_CMD_POWER_SEQ
#define TFT_CMD_POWER_SEQ 0xED
TFT_CMD_POWERA
#define TFT_CMD_POWERA 0xCB
TFT_CMD_POWERB
#define TFT_CMD_POWERB 0xCF
TFT_CMD_PRC
#define TFT_CMD_PRC 0xF7
TFT_CMD_PTLON
#define TFT_CMD_PTLON 0x12
TFT_CMD_PWCTR1
#define TFT_CMD_PWCTR1 0xC0
TFT_CMD_PWCTR2
#define TFT_CMD_PWCTR2 0xC1
TFT_CMD_PWCTR3
#define TFT_CMD_PWCTR3 0xC2
TFT_CMD_PWCTR4
#define TFT_CMD_PWCTR4 0xC3
TFT_CMD_PWCTR5
#define TFT_CMD_PWCTR5 0xC4
TFT_CMD_RDDID
#define TFT_CMD_RDDID 0x04
TFT_CMD_RDDST
#define TFT_CMD_RDDST 0x09
TFT_CMD_RDID1
#define TFT_CMD_RDID1 0xDA
TFT_CMD_RDID2
#define TFT_CMD_RDID2 0xDB
TFT_CMD_RDID3
#define TFT_CMD_RDID3 0xDC
TFT_CMD_RDID4
#define TFT_CMD_RDID4 0xDD
TFT_CMD_RDIMGFMT
#define TFT_CMD_RDIMGFMT 0x0D
TFT_CMD_RDMADCTL
#define TFT_CMD_RDMADCTL 0x0B
TFT_CMD_RDMODE
#define TFT_CMD_RDMODE 0x0A
TFT_CMD_RDPIXFMT
#define TFT_CMD_RDPIXFMT 0x0C
TFT_CMD_RDSELFDIAG
#define TFT_CMD_RDSELFDIAG 0x0F
TFT_CMD_SLPIN
#define TFT_CMD_SLPIN 0x10
TFT_CMD_SLPOUT
#define TFT_CMD_SLPOUT 0x11
TFT_CMD_SWRESET
#define TFT_CMD_SWRESET 0x01
TFT_CMD_VMCTR1
#define TFT_CMD_VMCTR1 0xC5
TFT_CMD_VMCTR2
#define TFT_CMD_VMCTR2 0xC7
TFT_DISPOFF
#define TFT_DISPOFF 0x28
TFT_DISPON
#define TFT_DISPON 0x29
TFT_ENTRYM
#define TFT_ENTRYM 0xB7
TFT_INVERT_ROTATION
#define TFT_INVERT_ROTATION 0
TFT_INVERT_ROTATION1
#define TFT_INVERT_ROTATION1 0
TFT_INVERT_ROTATION2
#define TFT_INVERT_ROTATION2 1
TFT_INVOFF
#define TFT_INVOFF 0x20
TFT_INVONN
#define TFT_INVONN 0x21
TFT_MADCTL
#define TFT_MADCTL 0x36
TFT_PASET
#define TFT_PASET 0x2B
TFT_PTLAR
#define TFT_PTLAR 0x30
TFT_RAMRD
#define TFT_RAMRD 0x2E
TFT_RAMWR
#define TFT_RAMWR 0x2C
TFT_RGB_BGR
#define TFT_RGB_BGR 0x08
TOUCH_TYPE_NONE
#define TOUCH_TYPE_NONE 0
TOUCH_TYPE_STMPE610
#define TOUCH_TYPE_STMPE610 2
TOUCH_TYPE_XPT2046
#define TOUCH_TYPE_XPT2046 1
TP_CALX_STMPE610
#define TP_CALX_STMPE610 21368532
Referenced by TFT_read_touch().
TP_CALX_XPT2046
#define TP_CALX_XPT2046 7472920
Referenced by TFT_read_touch().
TP_CALY_STMPE610
#define TP_CALY_STMPE610 11800144
Referenced by TFT_read_touch().
TP_CALY_XPT2046
#define TP_CALY_XPT2046 122224794
Referenced by TFT_read_touch().
USE_TOUCH
#define USE_TOUCH TOUCH_TYPE_NONE
Function Documentation
__attribute__()
struct __attribute__ ((__packed__))
References r.
_tft_setRotation()
void _tft_setRotation (uint8_t rot)
References _height, _width, disp_deselect(), disp_select(), disp_spi_transfer_cmd_data(), LANDSCAPE, LANDSCAPE_FLIP, MADCTL_MV, MADCTL_MX, MADCTL_MY, PORTRAIT, PORTRAIT_FLIP, TFT_MADCTL, and TFT_RGB_BGR.
Referenced by TFT_setRotation().
disp_deselect()
esp_err_t disp_deselect ()
References spi_lobo_device_deselect(), and wait_trans_finish().
Referenced by _tft_setRotation(), find_rd_speed(), read_data(), TFT_bmp_image(), and TFT_setRotation().
disp_select()
esp_err_t disp_select ()
References spi_lobo_device_select(), and wait_trans_finish().
Referenced by _tft_setRotation(), drawPixel(), find_rd_speed(), read_data(), TFT_bmp_image(), TFT_display_init(), TFT_drawCircle(), TFT_pushColorRep(), and TFT_setRotation().
disp_spi_transfer_cmd()
void disp_spi_transfer_cmd (int8_t cmd)
References spi_lobo_device_t::host, spi_lobo_host_t::hw, and PIN_NUM_DC.
Referenced by TFT_invertDisplay().
disp_spi_transfer_cmd_data()
void disp_spi_transfer_cmd_data (int8_t cmd, uint8_t * data, uint32_t len)
References spi_lobo_device_t::host, spi_lobo_host_t::hw, and PIN_NUM_DC.
Referenced by _tft_setRotation(), TFT_setGammaCurve(), and TFT_setRotation().
drawPixel()
void drawPixel (int16_t x, int16_t y, color_t color, uint8_t sel)
References spi_lobo_device_t::cfg, color_t, disp_select(), spi_lobo_device_interface_config_t::flags, gray_scale, LB_SPI_DEVICE_HALFDUPLEX, and wait_trans_finish().
find_rd_speed()
uint32_t find_rd_speed ()
References _height, _width, color_t, disp_deselect(), disp_select(), gray_scale, r, read_data(), send_data(), spi_lobo_get_speed(), and spi_lobo_set_speed().
Referenced by app_main(), and TftDisplayBackend().
read_data()
int read_data (int x1, int y1, int x2, int y2, int len, uint8_t * buf, uint8_t set_sp)
References color_t, disp_deselect(), disp_select(), max_rdclock, spi_lobo_get_speed(), and spi_lobo_set_speed().
Referenced by find_rd_speed(), and readPixel().
readPixel()
color_t readPixel (int16_t x, int16_t y)
References color_t, and read_data().
Referenced by TFT_readPixel().
send_data()
void send_data (int x1, int y1, int x2, int y2, uint32_t len, color_t * buf)
Referenced by find_rd_speed(), and TFT_bmp_image().
stmpe610_get_touch()
int stmpe610_get_touch (uint16_t * x, uint16_t * y, uint16_t * z)
Referenced by TFT_read_touch().
stmpe610_getID()
uint32_t stmpe610_getID ()
Referenced by app_main().
stmpe610_Init()
void stmpe610_Init ()
Referenced by app_main().
TFT_display_init()
void TFT_display_init ()
Enable backlight
References disp_select(), DISP_TYPE_ILI9341, PIN_NUM_RST, and tft_disp_type.
Referenced by app_main(), and TftDisplayBackend().
TFT_PinsInit()
void TFT_PinsInit ()
References PIN_BCKL_OFF, PIN_NUM_BCKL, PIN_NUM_CLK, PIN_NUM_CS, PIN_NUM_DC, PIN_NUM_MISO, PIN_NUM_MOSI, PIN_NUM_RST, and PIN_NUM_TCS.
Referenced by app_main(), and TftDisplayBackend().
TFT_pushColorRep()
void TFT_pushColorRep (int x1, int y1, int x2, int y2, color_t data, uint32_t len)
References disp_select().
Referenced by TFT_fillScreen(), and TFT_fillWindow().
touch_get_data()
int touch_get_data (uint8_t type)
References spi_lobo_device_t::host, spi_lobo_host_t::hw, and spi_lobo_device_select().
Referenced by TFT_bmp_image().
wait_trans_finish()
esp_err_t wait_trans_finish (uint8_t free_line)
References spi_lobo_device_t::host, and spi_lobo_host_t::hw.
Referenced by disp_deselect(), disp_select(), drawPixel(), and TFT_bmp_image().
Variable Documentation
_height
int _height
Referenced by _tft_setRotation(), app_main(), find_rd_speed(), TFT_fillScreen(), TFT_read_touch(), TFT_resetclipwin(), TFT_setclipwin(), and TFT_setRotation().
_width
int _width
Referenced by _tft_setRotation(), app_main(), find_rd_speed(), TFT_fillScreen(), TFT_read_touch(), TFT_resetclipwin(), TFT_setclipwin(), and TFT_setRotation().
color_t
color_t
Referenced by drawPixel(), find_rd_speed(), HSBtoRGB(), read_data(), readPixel(), and TFT_bmp_image().
disp_spi
spi_lobo_device_handle_t disp_spi
gray_scale
uint8_t gray_scale
Referenced by app_main(), drawPixel(), and find_rd_speed().
max_rdclock
uint32_t max_rdclock
Referenced by app_main(), read_data(), and TftDisplayBackend().
tft_disp_type
uint8_t tft_disp_type
Referenced by app_main(), tft_demo(), and TFT_display_init().
ts_spi
spi_lobo_device_handle_t ts_spi
Referenced by app_main(), TFT_bmp_image(), and TFT_read_touch().